//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:44 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_init                       O     1 const
// mav_csrrxx                     O    33
// RDY_mav_csrrxx                 O     1 const
// mav_exception                  O    32
// RDY_mav_exception              O     1 const
// mav_xRET                       O    32 reg
// RDY_mav_xRET                   O     1 const
// RDY_ma_incr_instret            O     1 const
// mv_instret                     O    64 reg
// RDY_mv_instret                 O     1 const
// can_take_interrupt_fst         O     1
// RDY_can_take_interrupt_fst     O     1 const
// can_take_interrupt_snd         O     4 const
// RDY_can_take_interrupt_snd     O     1 const
// csr_write                      O     1
// RDY_csr_write                  O     1 const
// csr_read                       O    33
// RDY_csr_read                   O     1 const
// RDY_save_dpc_dcsr_cause_prv    O     1 const
// get_dpc                        O    32 reg
// get_dcsr                       O    32 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// init_initial_params            I   208 reg
// mav_csrrxx_instr               I    32
// mav_csrrxx_rs1_val             I    32
// mav_exception_epc              I    32
// mav_exception_is_interrupt     I     1
// mav_exception_cause            I     4
// mav_exception_tval             I    32
// set_TIME_t                     I    64
// set_MIP_MTIP_v                 I     1 reg
// csr_write_csr_addr             I    12
// csr_write_csr_val              I    32
// csr_read_csr_addr              I    12
// save_dpc_dcsr_cause_prv_pc     I    32
// save_dpc_dcsr_cause_prv_cause  I     3
// save_dpc_dcsr_cause_prv_prv    I     2
// EN_init                        I     1
// EN_ma_incr_instret             I     1
// EN_save_dpc_dcsr_cause_prv     I     1
// EN_mav_csrrxx                  I     1
// EN_mav_exception               I     1
// EN_mav_xRET                    I     1
// EN_csr_write                   I     1
// EN_csr_read                    I     1 unused
//
// Combinational paths from inputs to outputs:
//   (set_TIME_t, mav_csrrxx_instr) -> mav_csrrxx
//   (set_TIME_t, csr_read_csr_addr) -> csr_read
//   (mav_exception_is_interrupt, mav_exception_cause) -> mav_exception
//   csr_write_csr_addr -> csr_write
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCSRs(CLK,
	      RST_N,

	      init_initial_params,
	      EN_init,
	      RDY_init,

	      mav_csrrxx_instr,
	      mav_csrrxx_rs1_val,
	      EN_mav_csrrxx,
	      mav_csrrxx,
	      RDY_mav_csrrxx,

	      mav_exception_epc,
	      mav_exception_is_interrupt,
	      mav_exception_cause,
	      mav_exception_tval,
	      EN_mav_exception,
	      mav_exception,
	      RDY_mav_exception,

	      EN_mav_xRET,
	      mav_xRET,
	      RDY_mav_xRET,

	      EN_ma_incr_instret,
	      RDY_ma_incr_instret,

	      mv_instret,
	      RDY_mv_instret,

	      set_TIME_t,

	      set_MIP_MTIP_v,

	      can_take_interrupt_fst,
	      RDY_can_take_interrupt_fst,

	      can_take_interrupt_snd,
	      RDY_can_take_interrupt_snd,

	      csr_write_csr_addr,
	      csr_write_csr_val,
	      EN_csr_write,
	      csr_write,
	      RDY_csr_write,

	      csr_read_csr_addr,
	      EN_csr_read,
	      csr_read,
	      RDY_csr_read,

	      save_dpc_dcsr_cause_prv_pc,
	      save_dpc_dcsr_cause_prv_cause,
	      save_dpc_dcsr_cause_prv_prv,
	      EN_save_dpc_dcsr_cause_prv,
	      RDY_save_dpc_dcsr_cause_prv,

	      get_dpc,

	      get_dcsr);
  input  CLK;
  input  RST_N;

  // action method init
  input  [207 : 0] init_initial_params;
  input  EN_init;
  output RDY_init;

  // actionvalue method mav_csrrxx
  input  [31 : 0] mav_csrrxx_instr;
  input  [31 : 0] mav_csrrxx_rs1_val;
  input  EN_mav_csrrxx;
  output [32 : 0] mav_csrrxx;
  output RDY_mav_csrrxx;

  // actionvalue method mav_exception
  input  [31 : 0] mav_exception_epc;
  input  mav_exception_is_interrupt;
  input  [3 : 0] mav_exception_cause;
  input  [31 : 0] mav_exception_tval;
  input  EN_mav_exception;
  output [31 : 0] mav_exception;
  output RDY_mav_exception;

  // actionvalue method mav_xRET
  input  EN_mav_xRET;
  output [31 : 0] mav_xRET;
  output RDY_mav_xRET;

  // action method ma_incr_instret
  input  EN_ma_incr_instret;
  output RDY_ma_incr_instret;

  // value method mv_instret
  output [63 : 0] mv_instret;
  output RDY_mv_instret;

  // action method set_TIME
  input  [63 : 0] set_TIME_t;

  // action method set_MIP_MTIP
  input  set_MIP_MTIP_v;

  // value method can_take_interrupt_fst
  output can_take_interrupt_fst;
  output RDY_can_take_interrupt_fst;

  // value method can_take_interrupt_snd
  output [3 : 0] can_take_interrupt_snd;
  output RDY_can_take_interrupt_snd;

  // actionvalue method csr_write
  input  [11 : 0] csr_write_csr_addr;
  input  [31 : 0] csr_write_csr_val;
  input  EN_csr_write;
  output csr_write;
  output RDY_csr_write;

  // actionvalue method csr_read
  input  [11 : 0] csr_read_csr_addr;
  input  EN_csr_read;
  output [32 : 0] csr_read;
  output RDY_csr_read;

  // action method save_dpc_dcsr_cause_prv
  input  [31 : 0] save_dpc_dcsr_cause_prv_pc;
  input  [2 : 0] save_dpc_dcsr_cause_prv_cause;
  input  [1 : 0] save_dpc_dcsr_cause_prv_prv;
  input  EN_save_dpc_dcsr_cause_prv;
  output RDY_save_dpc_dcsr_cause_prv;

  // value method get_dpc
  output [31 : 0] get_dpc;

  // value method get_dcsr
  output [31 : 0] get_dcsr;

  // signals for module outputs
  wire [63 : 0] mv_instret;
  wire [32 : 0] csr_read, mav_csrrxx;
  wire [31 : 0] get_dcsr, get_dpc, mav_exception, mav_xRET;
  wire [3 : 0] can_take_interrupt_snd;
  wire RDY_can_take_interrupt_fst,
       RDY_can_take_interrupt_snd,
       RDY_csr_read,
       RDY_csr_write,
       RDY_init,
       RDY_ma_incr_instret,
       RDY_mav_csrrxx,
       RDY_mav_exception,
       RDY_mav_xRET,
       RDY_mv_instret,
       RDY_save_dpc_dcsr_cause_prv,
       can_take_interrupt_fst,
       csr_write;

  // inlined wires
  wire [63 : 0] csr_mcycle$port0__write_1,
		csr_mcycle$port1__write_1,
		csr_mcycle$port2__read;
  wire csr_mcycle$EN_port1__write;

  // register crg_csr_TIME
  reg [63 : 0] crg_csr_TIME;
  wire [63 : 0] crg_csr_TIME$D_IN;
  wire crg_csr_TIME$EN;

  // register csr_dcsr
  reg [31 : 0] csr_dcsr;
  reg [31 : 0] csr_dcsr$D_IN;
  wire csr_dcsr$EN;

  // register csr_dpc
  reg [31 : 0] csr_dpc;
  reg [31 : 0] csr_dpc$D_IN;
  wire csr_dpc$EN;

  // register csr_mcause
  reg [31 : 0] csr_mcause;
  reg [31 : 0] csr_mcause$D_IN;
  wire csr_mcause$EN;

  // register csr_mcycle
  reg [63 : 0] csr_mcycle;
  wire [63 : 0] csr_mcycle$D_IN;
  wire csr_mcycle$EN;

  // register csr_mepc
  reg [31 : 0] csr_mepc;
  reg [31 : 0] csr_mepc$D_IN;
  wire csr_mepc$EN;

  // register csr_mie
  reg [31 : 0] csr_mie;
  wire [31 : 0] csr_mie$D_IN;
  wire csr_mie$EN;

  // register csr_minstret
  reg [63 : 0] csr_minstret;
  reg [63 : 0] csr_minstret$D_IN;
  wire csr_minstret$EN;

  // register csr_mip_mtip
  reg csr_mip_mtip;
  wire csr_mip_mtip$D_IN, csr_mip_mtip$EN;

  // register csr_mscratch
  reg [31 : 0] csr_mscratch;
  wire [31 : 0] csr_mscratch$D_IN;
  wire csr_mscratch$EN;

  // register csr_mstatus
  reg [31 : 0] csr_mstatus;
  reg [31 : 0] csr_mstatus$D_IN;
  wire csr_mstatus$EN;

  // register csr_mtval
  reg [31 : 0] csr_mtval;
  reg [31 : 0] csr_mtval$D_IN;
  wire csr_mtval$EN;

  // register csr_mtvec
  reg [31 : 0] csr_mtvec;
  wire [31 : 0] csr_mtvec$D_IN;
  wire csr_mtvec$EN;

  // register rg_flog
  reg [31 : 0] rg_flog;
  wire [31 : 0] rg_flog$D_IN;
  wire rg_flog$EN;

  // rule scheduling signals
  wire CAN_FIRE_RL_rl_count_cycles,
       CAN_FIRE_csr_read,
       CAN_FIRE_csr_write,
       CAN_FIRE_init,
       CAN_FIRE_ma_incr_instret,
       CAN_FIRE_mav_csrrxx,
       CAN_FIRE_mav_exception,
       CAN_FIRE_mav_xRET,
       CAN_FIRE_save_dpc_dcsr_cause_prv,
       CAN_FIRE_set_MIP_MTIP,
       CAN_FIRE_set_TIME,
       WILL_FIRE_RL_rl_count_cycles,
       WILL_FIRE_csr_read,
       WILL_FIRE_csr_write,
       WILL_FIRE_init,
       WILL_FIRE_ma_incr_instret,
       WILL_FIRE_mav_csrrxx,
       WILL_FIRE_mav_exception,
       WILL_FIRE_mav_xRET,
       WILL_FIRE_save_dpc_dcsr_cause_prv,
       WILL_FIRE_set_MIP_MTIP,
       WILL_FIRE_set_TIME;

  // inputs to muxes for submodule ports
  reg [31 : 0] MUX_csr_dcsr$write_1__VAL_3;
  wire [63 : 0] MUX_csr_mcycle$port1__write_1__VAL_1,
		MUX_csr_mcycle$port1__write_1__VAL_2,
		MUX_csr_minstret$write_1__VAL_1,
		MUX_csr_minstret$write_1__VAL_2;
  wire [31 : 0] MUX_csr_dcsr$write_1__VAL_2,
		MUX_csr_mcause$write_1__VAL_2,
		MUX_csr_mepc$write_1__VAL_1,
		MUX_csr_mepc$write_1__VAL_3,
		MUX_csr_mie$write_1__VAL_1,
		MUX_csr_mie$write_1__VAL_2,
		MUX_csr_mstatus$write_1__VAL_1,
		MUX_csr_mstatus$write_1__VAL_4,
		MUX_csr_mtvec$write_1__VAL_1,
		MUX_csr_mtvec$write_1__VAL_2;
  wire MUX_csr_dcsr$write_1__SEL_1,
       MUX_csr_dcsr$write_1__SEL_3,
       MUX_csr_dpc$write_1__SEL_1,
       MUX_csr_dpc$write_1__SEL_3,
       MUX_csr_mcause$write_1__SEL_1,
       MUX_csr_mcause$write_1__SEL_3,
       MUX_csr_mcycle$port1__write_1__SEL_1,
       MUX_csr_mepc$write_1__SEL_1,
       MUX_csr_mepc$write_1__SEL_3,
       MUX_csr_mie$write_1__SEL_1,
       MUX_csr_minstret$write_1__SEL_1,
       MUX_csr_minstret$write_1__SEL_2,
       MUX_csr_mscratch$write_1__SEL_1,
       MUX_csr_mstatus$write_1__SEL_1,
       MUX_csr_mstatus$write_1__SEL_4,
       MUX_csr_mtval$write_1__SEL_1,
       MUX_csr_mtval$write_1__SEL_3,
       MUX_csr_mtvec$write_1__SEL_1;

  // declarations used by system tasks
  // synopsys translate_off
  reg [31 : 0] v__h8964;
  reg [31 : 0] v__h1078;
  reg [31 : 0] v__h1449;
  reg [31 : 0] v__h2501;
  reg [31 : 0] v__h3990;
  reg [31 : 0] v__h4956;
  reg [31 : 0] v__h6752;
  reg [31 : 0] v__h7161;
  reg [31 : 0] v__h7566;
  reg [31 : 0] x__h1111;
  reg [31 : 0] x__h1482;
  reg [31 : 0] x__h2534;
  reg [31 : 0] x__h4023;
  reg [31 : 0] x__h4989;
  reg [31 : 0] x__h6785;
  reg [31 : 0] x__h7194;
  reg [31 : 0] x__h7599;
  reg [31 : 0] x__h8997;
  reg [31 : 0] v__h1070;
  reg [31 : 0] v__h1441;
  reg [31 : 0] v__h2493;
  reg [31 : 0] v__h3982;
  reg [31 : 0] v__h4948;
  reg [31 : 0] v__h6744;
  reg [31 : 0] v__h7153;
  reg [31 : 0] v__h7558;
  reg [31 : 0] v__h8956;
  // synopsys translate_on

  // remaining internal signals
  reg [31 : 0] y__h1700, y__h9196;
  wire [63 : 0] IF_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1_T_ETC___d266,
		x1__h3421,
		x1__h3503,
		x1__h5857,
		x1__h5939,
		x1__h8429,
		x1__h8510,
		x__h3578,
		x__h3658,
		x__h6014,
		x__h6094,
		x__h6448,
		x__h8584,
		x__h8663;
  wire [31 : 0] IF_mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_ETC___d104,
		IF_mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_ETC___d106,
		_theResult____h1312,
		_theResult____h6613,
		_theResult____h7037,
		base__h6614,
		mcause_msb__h6539,
		new_cause_prv__h9897,
		new_mstatus___1__h7088,
		new_mstatus__h7036,
		v_new__h4901,
		x__h3044,
		x__h3194,
		x__h5487,
		x__h5631,
		x__h9912,
		y___1__h3086,
		y___1__h5529,
		y___1__h8102,
		y__h1762,
		y__h5215;
  wire [29 : 0] _0_CONCAT_IF_mav_csrrxx_instr_BITS_13_TO_12_0_E_ETC___d142;
  wire [27 : 0] _0_CONCAT_IF_mav_csrrxx_instr_BITS_13_TO_12_0_E_ETC___d138;
  wire [25 : 0] _0_CONCAT_IF_mav_csrrxx_instr_BITS_13_TO_12_0_E_ETC___d134;
  wire [23 : 0] _0_CONCAT_IF_mav_csrrxx_instr_BITS_13_TO_12_0_E_ETC___d130;
  wire [7 : 0] x__h2177;
  wire [1 : 0] mode__h3216, mode__h5653, mode__h8226;
  wire NOT_mav_csrrxx_instr_BITS_11_TO_7_80_EQ_0_81_7_ETC___d317,
       NOT_mav_csrrxx_instr_BITS_11_TO_7_80_EQ_0_81_7_ETC___d335,
       NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d227,
       NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d258,
       NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d347,
       NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d348,
       _dfoo1,
       mav_csrrxx_instr_BITS_11_TO_7_80_EQ_0_81_OR_ma_ETC___d338,
       mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1_AND__ETC___d224,
       mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1_AND__ETC___d255,
       mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_OR_ETC___d350;

  // action method init
  assign RDY_init = 1'd1 ;
  assign CAN_FIRE_init = 1'd1 ;
  assign WILL_FIRE_init = EN_init ;

  // actionvalue method mav_csrrxx
  assign mav_csrrxx =
	     { (mav_csrrxx_instr[13:12] == 2'b01 ||
		(mav_csrrxx_instr[31:20] == 12'h301 ||
		 mav_csrrxx_instr[31:20] == 12'hF11 ||
		 mav_csrrxx_instr[31:20] == 12'hF12 ||
		 mav_csrrxx_instr[31:20] == 12'hF13 ||
		 mav_csrrxx_instr[31:20] == 12'hF14 ||
		 mav_csrrxx_instr[31:20] == 12'h300 ||
		 mav_csrrxx_instr[31:20] == 12'h310 ||
		 mav_csrrxx_instr[31:20] == 12'h304 ||
		 mav_csrrxx_instr[31:20] == 12'h344 ||
		 mav_csrrxx_instr[31:20] == 12'h305 ||
		 mav_csrrxx_instr[31:20] == 12'h340 ||
		 mav_csrrxx_instr[31:20] == 12'h341 ||
		 mav_csrrxx_instr[31:20] == 12'h342 ||
		 mav_csrrxx_instr[31:20] == 12'h343 ||
		 mav_csrrxx_instr[31:20] == 12'hC00 ||
		 mav_csrrxx_instr[31:20] == 12'hC80 ||
		 mav_csrrxx_instr[31:20] == 12'hB00 ||
		 mav_csrrxx_instr[31:20] == 12'hB80 ||
		 mav_csrrxx_instr[31:20] == 12'hC01 ||
		 mav_csrrxx_instr[31:20] == 12'hC81 ||
		 mav_csrrxx_instr[31:20] == 12'hB02 ||
		 mav_csrrxx_instr[31:20] == 12'hB82 ||
		 mav_csrrxx_instr[31:20] == 12'hC02 ||
		 mav_csrrxx_instr[31:20] == 12'hC82 ||
		 mav_csrrxx_instr[31:20] == 12'h7B0 ||
		 mav_csrrxx_instr[31:20] == 12'h7B1) &&
		mav_csrrxx_instr[19:15] != 5'd0) ?
		 mav_csrrxx_instr[31:20] != 12'h301 &&
		 mav_csrrxx_instr[31:20] != 12'hF11 &&
		 mav_csrrxx_instr[31:20] != 12'hF12 &&
		 mav_csrrxx_instr[31:20] != 12'hF13 &&
		 mav_csrrxx_instr[31:20] != 12'hF14 &&
		 mav_csrrxx_instr[31:20] != 12'h300 &&
		 mav_csrrxx_instr[31:20] != 12'h310 &&
		 mav_csrrxx_instr[31:20] != 12'h304 &&
		 mav_csrrxx_instr[31:20] != 12'h344 &&
		 mav_csrrxx_instr[31:20] != 12'h305 &&
		 mav_csrrxx_instr[31:20] != 12'h340 &&
		 mav_csrrxx_instr[31:20] != 12'h341 &&
		 mav_csrrxx_instr[31:20] != 12'h342 &&
		 mav_csrrxx_instr[31:20] != 12'h343 &&
		 mav_csrrxx_instr[31:20] != 12'hB00 &&
		 mav_csrrxx_instr[31:20] != 12'hB80 &&
		 mav_csrrxx_instr[31:20] != 12'hB02 &&
		 mav_csrrxx_instr[31:20] != 12'hB82 &&
		 mav_csrrxx_instr[31:20] != 12'h7B0 &&
		 mav_csrrxx_instr[31:20] != 12'h7B1 :
		 mav_csrrxx_instr[31:20] != 12'h301 &&
		 mav_csrrxx_instr[31:20] != 12'hF11 &&
		 mav_csrrxx_instr[31:20] != 12'hF12 &&
		 mav_csrrxx_instr[31:20] != 12'hF13 &&
		 mav_csrrxx_instr[31:20] != 12'hF14 &&
		 mav_csrrxx_instr[31:20] != 12'h300 &&
		 mav_csrrxx_instr[31:20] != 12'h310 &&
		 mav_csrrxx_instr[31:20] != 12'h304 &&
		 mav_csrrxx_instr[31:20] != 12'h344 &&
		 mav_csrrxx_instr[31:20] != 12'h305 &&
		 mav_csrrxx_instr[31:20] != 12'h340 &&
		 mav_csrrxx_instr[31:20] != 12'h341 &&
		 mav_csrrxx_instr[31:20] != 12'h342 &&
		 mav_csrrxx_instr[31:20] != 12'h343 &&
		 mav_csrrxx_instr[31:20] != 12'hC00 &&
		 mav_csrrxx_instr[31:20] != 12'hC80 &&
		 mav_csrrxx_instr[31:20] != 12'hB00 &&
		 mav_csrrxx_instr[31:20] != 12'hB80 &&
		 mav_csrrxx_instr[31:20] != 12'hC01 &&
		 mav_csrrxx_instr[31:20] != 12'hC81 &&
		 mav_csrrxx_instr[31:20] != 12'hB02 &&
		 mav_csrrxx_instr[31:20] != 12'hB82 &&
		 mav_csrrxx_instr[31:20] != 12'hC02 &&
		 mav_csrrxx_instr[31:20] != 12'hC82 &&
		 mav_csrrxx_instr[31:20] != 12'h7B0 &&
		 mav_csrrxx_instr[31:20] != 12'h7B1,
	       y__h1700 } ;
  assign RDY_mav_csrrxx = 1'd1 ;
  assign CAN_FIRE_mav_csrrxx = 1'd1 ;
  assign WILL_FIRE_mav_csrrxx = EN_mav_csrrxx ;

  // actionvalue method mav_exception
  assign mav_exception =
	     (csr_mtvec[1:0] == 2'b01 && mav_exception_is_interrupt) ?
	       base__h6614 + { 26'd0, mav_exception_cause, 2'd0 } :
	       base__h6614 ;
  assign RDY_mav_exception = 1'd1 ;
  assign CAN_FIRE_mav_exception = 1'd1 ;
  assign WILL_FIRE_mav_exception = EN_mav_exception ;

  // actionvalue method mav_xRET
  assign mav_xRET = csr_mepc ;
  assign RDY_mav_xRET = 1'd1 ;
  assign CAN_FIRE_mav_xRET = 1'd1 ;
  assign WILL_FIRE_mav_xRET = EN_mav_xRET ;

  // action method ma_incr_instret
  assign RDY_ma_incr_instret = 1'd1 ;
  assign CAN_FIRE_ma_incr_instret = 1'd1 ;
  assign WILL_FIRE_ma_incr_instret = EN_ma_incr_instret ;

  // value method mv_instret
  assign mv_instret = csr_minstret ;
  assign RDY_mv_instret = 1'd1 ;

  // action method set_TIME
  assign CAN_FIRE_set_TIME = 1'd1 ;
  assign WILL_FIRE_set_TIME = 1'd1 ;

  // action method set_MIP_MTIP
  assign CAN_FIRE_set_MIP_MTIP = 1'd1 ;
  assign WILL_FIRE_set_MIP_MTIP = 1'd1 ;

  // value method can_take_interrupt_fst
  assign can_take_interrupt_fst =
	     csr_mip_mtip && csr_mie[7] && csr_mstatus[3] ;
  assign RDY_can_take_interrupt_fst = 1'd1 ;

  // value method can_take_interrupt_snd
  assign can_take_interrupt_snd = 4'd7 ;
  assign RDY_can_take_interrupt_snd = 1'd1 ;

  // actionvalue method csr_write
  assign csr_write =
	     csr_write_csr_addr != 12'h301 && csr_write_csr_addr != 12'hF11 &&
	     csr_write_csr_addr != 12'hF12 &&
	     csr_write_csr_addr != 12'hF13 &&
	     csr_write_csr_addr != 12'hF14 &&
	     csr_write_csr_addr != 12'h300 &&
	     csr_write_csr_addr != 12'h310 &&
	     csr_write_csr_addr != 12'h304 &&
	     csr_write_csr_addr != 12'h344 &&
	     csr_write_csr_addr != 12'h305 &&
	     csr_write_csr_addr != 12'h340 &&
	     csr_write_csr_addr != 12'h341 &&
	     csr_write_csr_addr != 12'h342 &&
	     csr_write_csr_addr != 12'h343 &&
	     csr_write_csr_addr != 12'hB00 &&
	     csr_write_csr_addr != 12'hB80 &&
	     csr_write_csr_addr != 12'hB02 &&
	     csr_write_csr_addr != 12'hB82 &&
	     csr_write_csr_addr != 12'h7B0 &&
	     csr_write_csr_addr != 12'h7B1 ;
  assign RDY_csr_write = 1'd1 ;
  assign CAN_FIRE_csr_write = 1'd1 ;
  assign WILL_FIRE_csr_write = EN_csr_write ;

  // actionvalue method csr_read
  assign csr_read =
	     { csr_read_csr_addr != 12'h301 && csr_read_csr_addr != 12'hF11 &&
	       csr_read_csr_addr != 12'hF12 &&
	       csr_read_csr_addr != 12'hF13 &&
	       csr_read_csr_addr != 12'hF14 &&
	       csr_read_csr_addr != 12'h300 &&
	       csr_read_csr_addr != 12'h310 &&
	       csr_read_csr_addr != 12'h304 &&
	       csr_read_csr_addr != 12'h344 &&
	       csr_read_csr_addr != 12'h305 &&
	       csr_read_csr_addr != 12'h340 &&
	       csr_read_csr_addr != 12'h341 &&
	       csr_read_csr_addr != 12'h342 &&
	       csr_read_csr_addr != 12'h343 &&
	       csr_read_csr_addr != 12'hC00 &&
	       csr_read_csr_addr != 12'hC80 &&
	       csr_read_csr_addr != 12'hB00 &&
	       csr_read_csr_addr != 12'hB80 &&
	       csr_read_csr_addr != 12'hC01 &&
	       csr_read_csr_addr != 12'hC81 &&
	       csr_read_csr_addr != 12'hB02 &&
	       csr_read_csr_addr != 12'hB82 &&
	       csr_read_csr_addr != 12'hC02 &&
	       csr_read_csr_addr != 12'hC82 &&
	       csr_read_csr_addr != 12'h7B0 &&
	       csr_read_csr_addr != 12'h7B1,
	       y__h9196 } ;
  assign RDY_csr_read = 1'd1 ;
  assign CAN_FIRE_csr_read = 1'd1 ;
  assign WILL_FIRE_csr_read = EN_csr_read ;

  // action method save_dpc_dcsr_cause_prv
  assign RDY_save_dpc_dcsr_cause_prv = 1'd1 ;
  assign CAN_FIRE_save_dpc_dcsr_cause_prv = 1'd1 ;
  assign WILL_FIRE_save_dpc_dcsr_cause_prv = EN_save_dpc_dcsr_cause_prv ;

  // value method get_dpc
  assign get_dpc = csr_dpc ;

  // value method get_dcsr
  assign get_dcsr = csr_dcsr ;

  // rule RL_rl_count_cycles
  assign CAN_FIRE_RL_rl_count_cycles = 1'd1 ;
  assign WILL_FIRE_RL_rl_count_cycles = 1'd1 ;

  // inputs to muxes for submodule ports
  assign MUX_csr_dcsr$write_1__SEL_1 =
	     EN_csr_write && csr_write_csr_addr == 12'h7B0 ;
  assign MUX_csr_dcsr$write_1__SEL_3 =
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr[13:12] == 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h7B0 ||
	      mav_csrrxx_instr[13:12] != 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h7B0 &&
	      mav_csrrxx_instr[19:15] != 5'd0) ;
  assign MUX_csr_dpc$write_1__SEL_1 =
	     EN_csr_write && csr_write_csr_addr == 12'h7B1 ;
  assign MUX_csr_dpc$write_1__SEL_3 =
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr[13:12] == 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h7B1 ||
	      mav_csrrxx_instr[13:12] != 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h7B1 &&
	      mav_csrrxx_instr[19:15] != 5'd0) ;
  assign MUX_csr_mcause$write_1__SEL_1 =
	     EN_csr_write && csr_write_csr_addr == 12'h342 ;
  assign MUX_csr_mcause$write_1__SEL_3 =
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr[13:12] == 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h342 ||
	      mav_csrrxx_instr[13:12] != 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h342 &&
	      mav_csrrxx_instr[19:15] != 5'd0) ;
  assign MUX_csr_mcycle$port1__write_1__SEL_1 =
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1_AND__ETC___d224 ||
	      NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d227) ;
  assign MUX_csr_mepc$write_1__SEL_1 =
	     EN_csr_write && csr_write_csr_addr == 12'h341 ;
  assign MUX_csr_mepc$write_1__SEL_3 =
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr[13:12] == 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h341 ||
	      mav_csrrxx_instr[13:12] != 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h341 &&
	      mav_csrrxx_instr[19:15] != 5'd0) ;
  assign MUX_csr_mie$write_1__SEL_1 =
	     EN_csr_write && csr_write_csr_addr == 12'h304 ;
  assign MUX_csr_minstret$write_1__SEL_1 =
	     EN_csr_write &&
	     (csr_write_csr_addr == 12'hB02 ||
	      csr_write_csr_addr == 12'hB82) ;
  assign MUX_csr_minstret$write_1__SEL_2 = EN_mav_csrrxx && _dfoo1 ;
  assign MUX_csr_mscratch$write_1__SEL_1 =
	     EN_csr_write && csr_write_csr_addr == 12'h340 ;
  assign MUX_csr_mstatus$write_1__SEL_1 =
	     EN_csr_write && csr_write_csr_addr == 12'h300 ;
  assign MUX_csr_mstatus$write_1__SEL_4 =
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr[13:12] == 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h300 ||
	      mav_csrrxx_instr[13:12] != 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h300 &&
	      mav_csrrxx_instr[19:15] != 5'd0) ;
  assign MUX_csr_mtval$write_1__SEL_1 =
	     EN_csr_write && csr_write_csr_addr == 12'h343 ;
  assign MUX_csr_mtval$write_1__SEL_3 =
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr[13:12] == 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h343 ||
	      mav_csrrxx_instr[13:12] != 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h343 &&
	      mav_csrrxx_instr[19:15] != 5'd0) ;
  assign MUX_csr_mtvec$write_1__SEL_1 =
	     EN_csr_write && csr_write_csr_addr == 12'h305 ;
  assign MUX_csr_dcsr$write_1__VAL_2 = x__h9912 | new_cause_prv__h9897 ;
  always@(mav_csrrxx_instr or
	  IF_mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_ETC___d106 or
	  _theResult____h1312 or
	  IF_mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_ETC___d104)
  begin
    case (mav_csrrxx_instr[13:12])
      2'b01: MUX_csr_dcsr$write_1__VAL_3 = _theResult____h1312;
      2'b10:
	  MUX_csr_dcsr$write_1__VAL_3 =
	      IF_mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_ETC___d104;
      default: MUX_csr_dcsr$write_1__VAL_3 =
		   IF_mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_ETC___d106;
    endcase
  end
  assign MUX_csr_mcause$write_1__VAL_2 =
	     mcause_msb__h6539 | { 28'd0, mav_exception_cause } ;
  assign MUX_csr_mcycle$port1__write_1__VAL_1 =
	     (mav_csrrxx_instr[13:12] == 2'b01) ?
	       ((mav_csrrxx_instr[31:20] == 12'hB00) ?
		  x1__h3421 :
		  x1__h3503) :
	       ((mav_csrrxx_instr[31:20] == 12'hB00) ?
		  x1__h5857 :
		  x1__h5939) ;
  assign MUX_csr_mcycle$port1__write_1__VAL_2 =
	     (csr_write_csr_addr == 12'hB00) ? x1__h8429 : x1__h8510 ;
  assign MUX_csr_mepc$write_1__VAL_1 = { csr_write_csr_val[31:2], 2'd0 } ;
  assign MUX_csr_mepc$write_1__VAL_3 =
	     { (mav_csrrxx_instr[13:12] == 2'b01) ?
		 _theResult____h1312[31:2] :
		 v_new__h4901[31:2],
	       2'd0 } ;
  assign MUX_csr_mie$write_1__VAL_1 =
	     { 18'd0,
	       csr_write_csr_val[13],
	       1'd0,
	       csr_write_csr_val[11],
	       1'd0,
	       csr_write_csr_val[9],
	       1'd0,
	       csr_write_csr_val[7],
	       1'd0,
	       csr_write_csr_val[5],
	       1'd0,
	       csr_write_csr_val[3],
	       1'd0,
	       csr_write_csr_val[1],
	       1'd0 } ;
  assign MUX_csr_mie$write_1__VAL_2 =
	     { _0_CONCAT_IF_mav_csrrxx_instr_BITS_13_TO_12_0_E_ETC___d142,
	       (mav_csrrxx_instr[13:12] == 2'b01) ?
		 _theResult____h1312[1] :
		 v_new__h4901[1],
	       1'd0 } ;
  assign MUX_csr_minstret$write_1__VAL_1 =
	     (csr_write_csr_addr == 12'hB02) ? x__h8584 : x__h8663 ;
  assign MUX_csr_minstret$write_1__VAL_2 =
	     (mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1_AND__ETC___d255 ||
	      NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d258) ?
	       IF_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1_T_ETC___d266 :
	       x__h6448 ;
  assign MUX_csr_mstatus$write_1__VAL_1 =
	     (csr_write_csr_val[12:11] == 2'b11) ?
	       csr_write_csr_val :
	       y___1__h8102 ;
  assign MUX_csr_mstatus$write_1__VAL_4 =
	     (mav_csrrxx_instr[13:12] == 2'b01) ? x__h3044 : x__h5487 ;
  assign MUX_csr_mtvec$write_1__VAL_1 =
	     { csr_write_csr_val[31:2], mode__h8226 } ;
  assign MUX_csr_mtvec$write_1__VAL_2 =
	     (mav_csrrxx_instr[13:12] == 2'b01) ? x__h3194 : x__h5631 ;

  // inlined wires
  assign csr_mcycle$port0__write_1 = csr_mcycle + 64'd1 ;
  assign csr_mcycle$EN_port1__write =
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1_AND__ETC___d224 ||
	      NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d227) ||
	     EN_csr_write &&
	     (csr_write_csr_addr == 12'hB00 ||
	      csr_write_csr_addr == 12'hB80) ;
  assign csr_mcycle$port1__write_1 =
	     MUX_csr_mcycle$port1__write_1__SEL_1 ?
	       MUX_csr_mcycle$port1__write_1__VAL_1 :
	       MUX_csr_mcycle$port1__write_1__VAL_2 ;
  assign csr_mcycle$port2__read =
	     csr_mcycle$EN_port1__write ?
	       csr_mcycle$port1__write_1 :
	       csr_mcycle$port0__write_1 ;

  // register crg_csr_TIME
  assign crg_csr_TIME$D_IN = set_TIME_t ;
  assign crg_csr_TIME$EN = 1'b1 ;

  // register csr_dcsr
  always@(MUX_csr_dcsr$write_1__SEL_1 or
	  csr_write_csr_val or
	  EN_save_dpc_dcsr_cause_prv or
	  MUX_csr_dcsr$write_1__VAL_2 or
	  MUX_csr_dcsr$write_1__SEL_3 or MUX_csr_dcsr$write_1__VAL_3)
  case (1'b1)
    MUX_csr_dcsr$write_1__SEL_1: csr_dcsr$D_IN = csr_write_csr_val;
    EN_save_dpc_dcsr_cause_prv: csr_dcsr$D_IN = MUX_csr_dcsr$write_1__VAL_2;
    MUX_csr_dcsr$write_1__SEL_3: csr_dcsr$D_IN = MUX_csr_dcsr$write_1__VAL_3;
    default: csr_dcsr$D_IN =
		 32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
  endcase
  assign csr_dcsr$EN =
	     EN_csr_write && csr_write_csr_addr == 12'h7B0 ||
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr[13:12] == 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h7B0 ||
	      mav_csrrxx_instr[13:12] != 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h7B0 &&
	      mav_csrrxx_instr[19:15] != 5'd0) ||
	     EN_save_dpc_dcsr_cause_prv ;

  // register csr_dpc
  always@(MUX_csr_dpc$write_1__SEL_1 or
	  csr_write_csr_val or
	  EN_save_dpc_dcsr_cause_prv or
	  save_dpc_dcsr_cause_prv_pc or
	  MUX_csr_dpc$write_1__SEL_3 or MUX_csr_dcsr$write_1__VAL_3)
  case (1'b1)
    MUX_csr_dpc$write_1__SEL_1: csr_dpc$D_IN = csr_write_csr_val;
    EN_save_dpc_dcsr_cause_prv: csr_dpc$D_IN = save_dpc_dcsr_cause_prv_pc;
    MUX_csr_dpc$write_1__SEL_3: csr_dpc$D_IN = MUX_csr_dcsr$write_1__VAL_3;
    default: csr_dpc$D_IN =
		 32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
  endcase
  assign csr_dpc$EN =
	     EN_csr_write && csr_write_csr_addr == 12'h7B1 ||
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr[13:12] == 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h7B1 ||
	      mav_csrrxx_instr[13:12] != 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h7B1 &&
	      mav_csrrxx_instr[19:15] != 5'd0) ||
	     EN_save_dpc_dcsr_cause_prv ;

  // register csr_mcause
  always@(MUX_csr_mcause$write_1__SEL_1 or
	  csr_write_csr_val or
	  EN_mav_exception or
	  MUX_csr_mcause$write_1__VAL_2 or
	  MUX_csr_mcause$write_1__SEL_3 or MUX_csr_dcsr$write_1__VAL_3)
  case (1'b1)
    MUX_csr_mcause$write_1__SEL_1: csr_mcause$D_IN = csr_write_csr_val;
    EN_mav_exception: csr_mcause$D_IN = MUX_csr_mcause$write_1__VAL_2;
    MUX_csr_mcause$write_1__SEL_3:
	csr_mcause$D_IN = MUX_csr_dcsr$write_1__VAL_3;
    default: csr_mcause$D_IN =
		 32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
  endcase
  assign csr_mcause$EN =
	     EN_csr_write && csr_write_csr_addr == 12'h342 ||
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr[13:12] == 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h342 ||
	      mav_csrrxx_instr[13:12] != 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h342 &&
	      mav_csrrxx_instr[19:15] != 5'd0) ||
	     EN_mav_exception ;

  // register csr_mcycle
  assign csr_mcycle$D_IN = csr_mcycle$port2__read ;
  assign csr_mcycle$EN = 1'b1 ;

  // register csr_mepc
  always@(MUX_csr_mepc$write_1__SEL_1 or
	  MUX_csr_mepc$write_1__VAL_1 or
	  EN_mav_exception or
	  mav_exception_epc or
	  MUX_csr_mepc$write_1__SEL_3 or MUX_csr_mepc$write_1__VAL_3)
  case (1'b1)
    MUX_csr_mepc$write_1__SEL_1: csr_mepc$D_IN = MUX_csr_mepc$write_1__VAL_1;
    EN_mav_exception: csr_mepc$D_IN = mav_exception_epc;
    MUX_csr_mepc$write_1__SEL_3: csr_mepc$D_IN = MUX_csr_mepc$write_1__VAL_3;
    default: csr_mepc$D_IN =
		 32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
  endcase
  assign csr_mepc$EN =
	     EN_csr_write && csr_write_csr_addr == 12'h341 ||
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr[13:12] == 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h341 ||
	      mav_csrrxx_instr[13:12] != 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h341 &&
	      mav_csrrxx_instr[19:15] != 5'd0) ||
	     EN_mav_exception ;

  // register csr_mie
  assign csr_mie$D_IN =
	     MUX_csr_mie$write_1__SEL_1 ?
	       MUX_csr_mie$write_1__VAL_1 :
	       MUX_csr_mie$write_1__VAL_2 ;
  assign csr_mie$EN =
	     EN_csr_write && csr_write_csr_addr == 12'h304 ||
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr[13:12] == 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h304 ||
	      mav_csrrxx_instr[13:12] != 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h304 &&
	      mav_csrrxx_instr[19:15] != 5'd0) ;

  // register csr_minstret
  always@(MUX_csr_minstret$write_1__SEL_1 or
	  MUX_csr_minstret$write_1__VAL_1 or
	  MUX_csr_minstret$write_1__SEL_2 or
	  MUX_csr_minstret$write_1__VAL_2 or EN_ma_incr_instret or x__h6448)
  begin
    case (1'b1) // synopsys parallel_case
      MUX_csr_minstret$write_1__SEL_1:
	  csr_minstret$D_IN = MUX_csr_minstret$write_1__VAL_1;
      MUX_csr_minstret$write_1__SEL_2:
	  csr_minstret$D_IN = MUX_csr_minstret$write_1__VAL_2;
      EN_ma_incr_instret: csr_minstret$D_IN = x__h6448;
      default: csr_minstret$D_IN =
		   64'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
    endcase
  end
  assign csr_minstret$EN =
	     EN_csr_write &&
	     (csr_write_csr_addr == 12'hB02 ||
	      csr_write_csr_addr == 12'hB82) ||
	     EN_mav_csrrxx && _dfoo1 ||
	     EN_ma_incr_instret ;

  // register csr_mip_mtip
  assign csr_mip_mtip$D_IN = set_MIP_MTIP_v ;
  assign csr_mip_mtip$EN = 1'd1 ;

  // register csr_mscratch
  assign csr_mscratch$D_IN =
	     MUX_csr_mscratch$write_1__SEL_1 ?
	       csr_write_csr_val :
	       MUX_csr_dcsr$write_1__VAL_3 ;
  assign csr_mscratch$EN =
	     EN_csr_write && csr_write_csr_addr == 12'h340 ||
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr[13:12] == 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h340 ||
	      mav_csrrxx_instr[13:12] != 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h340 &&
	      mav_csrrxx_instr[19:15] != 5'd0) ;

  // register csr_mstatus
  always@(MUX_csr_mstatus$write_1__SEL_1 or
	  MUX_csr_mstatus$write_1__VAL_1 or
	  EN_mav_xRET or
	  _theResult____h7037 or
	  EN_mav_exception or
	  _theResult____h6613 or
	  MUX_csr_mstatus$write_1__SEL_4 or MUX_csr_mstatus$write_1__VAL_4)
  case (1'b1)
    MUX_csr_mstatus$write_1__SEL_1:
	csr_mstatus$D_IN = MUX_csr_mstatus$write_1__VAL_1;
    EN_mav_xRET: csr_mstatus$D_IN = _theResult____h7037;
    EN_mav_exception: csr_mstatus$D_IN = _theResult____h6613;
    MUX_csr_mstatus$write_1__SEL_4:
	csr_mstatus$D_IN = MUX_csr_mstatus$write_1__VAL_4;
    default: csr_mstatus$D_IN =
		 32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
  endcase
  assign csr_mstatus$EN =
	     EN_csr_write && csr_write_csr_addr == 12'h300 ||
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr[13:12] == 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h300 ||
	      mav_csrrxx_instr[13:12] != 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h300 &&
	      mav_csrrxx_instr[19:15] != 5'd0) ||
	     EN_mav_exception ||
	     EN_mav_xRET ;

  // register csr_mtval
  always@(MUX_csr_mtval$write_1__SEL_1 or
	  csr_write_csr_val or
	  EN_mav_exception or
	  mav_exception_tval or
	  MUX_csr_mtval$write_1__SEL_3 or MUX_csr_dcsr$write_1__VAL_3)
  case (1'b1)
    MUX_csr_mtval$write_1__SEL_1: csr_mtval$D_IN = csr_write_csr_val;
    EN_mav_exception: csr_mtval$D_IN = mav_exception_tval;
    MUX_csr_mtval$write_1__SEL_3:
	csr_mtval$D_IN = MUX_csr_dcsr$write_1__VAL_3;
    default: csr_mtval$D_IN =
		 32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
  endcase
  assign csr_mtval$EN =
	     EN_csr_write && csr_write_csr_addr == 12'h343 ||
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr[13:12] == 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h343 ||
	      mav_csrrxx_instr[13:12] != 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h343 &&
	      mav_csrrxx_instr[19:15] != 5'd0) ||
	     EN_mav_exception ;

  // register csr_mtvec
  assign csr_mtvec$D_IN =
	     MUX_csr_mtvec$write_1__SEL_1 ?
	       MUX_csr_mtvec$write_1__VAL_1 :
	       MUX_csr_mtvec$write_1__VAL_2 ;
  assign csr_mtvec$EN =
	     EN_csr_write && csr_write_csr_addr == 12'h305 ||
	     EN_mav_csrrxx &&
	     (mav_csrrxx_instr[13:12] == 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h305 ||
	      mav_csrrxx_instr[13:12] != 2'b01 &&
	      mav_csrrxx_instr[31:20] == 12'h305 &&
	      mav_csrrxx_instr[19:15] != 5'd0) ;

  // register rg_flog
  assign rg_flog$D_IN = init_initial_params[207:176] ;
  assign rg_flog$EN = EN_init ;

  // remaining internal signals
  assign IF_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1_T_ETC___d266 =
	     (mav_csrrxx_instr[13:12] == 2'b01) ?
	       ((mav_csrrxx_instr[31:20] == 12'hB02) ? x__h3578 : x__h3658) :
	       ((mav_csrrxx_instr[31:20] == 12'hB02) ? x__h6014 : x__h6094) ;
  assign IF_mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_ETC___d104 =
	     y__h1700 | _theResult____h1312 ;
  assign IF_mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_ETC___d106 =
	     y__h1700 & y__h5215 ;
  assign NOT_mav_csrrxx_instr_BITS_11_TO_7_80_EQ_0_81_7_ETC___d317 =
	     mav_csrrxx_instr[11:7] != 5'd0 &&
	     mav_csrrxx_instr[31:20] != 12'h301 &&
	     mav_csrrxx_instr[31:20] != 12'hF11 &&
	     mav_csrrxx_instr[31:20] != 12'hF12 &&
	     mav_csrrxx_instr[31:20] != 12'hF13 &&
	     mav_csrrxx_instr[31:20] != 12'hF14 &&
	     mav_csrrxx_instr[31:20] != 12'h300 &&
	     mav_csrrxx_instr[31:20] != 12'h310 &&
	     mav_csrrxx_instr[31:20] != 12'h304 &&
	     mav_csrrxx_instr[31:20] != 12'h344 &&
	     mav_csrrxx_instr[31:20] != 12'h305 &&
	     mav_csrrxx_instr[31:20] != 12'h340 &&
	     mav_csrrxx_instr[31:20] != 12'h341 &&
	     mav_csrrxx_instr[31:20] != 12'h342 &&
	     mav_csrrxx_instr[31:20] != 12'h343 &&
	     mav_csrrxx_instr[31:20] != 12'hC00 &&
	     mav_csrrxx_instr[31:20] != 12'hC80 &&
	     mav_csrrxx_instr[31:20] != 12'hB00 &&
	     mav_csrrxx_instr[31:20] != 12'hB80 &&
	     mav_csrrxx_instr[31:20] != 12'hC01 &&
	     mav_csrrxx_instr[31:20] != 12'hC81 &&
	     mav_csrrxx_instr[31:20] != 12'hB02 &&
	     mav_csrrxx_instr[31:20] != 12'hB82 &&
	     mav_csrrxx_instr[31:20] != 12'hC02 &&
	     mav_csrrxx_instr[31:20] != 12'hC82 &&
	     mav_csrrxx_instr[31:20] != 12'h7B0 &&
	     mav_csrrxx_instr[31:20] != 12'h7B1 &&
	     rg_flog != 32'd0 ;
  assign NOT_mav_csrrxx_instr_BITS_11_TO_7_80_EQ_0_81_7_ETC___d335 =
	     mav_csrrxx_instr[11:7] != 5'd0 &&
	     (mav_csrrxx_instr[31:20] == 12'h301 ||
	      mav_csrrxx_instr[31:20] == 12'hF11 ||
	      mav_csrrxx_instr[31:20] == 12'hF12 ||
	      mav_csrrxx_instr[31:20] == 12'hF13 ||
	      mav_csrrxx_instr[31:20] == 12'hF14 ||
	      mav_csrrxx_instr[31:20] == 12'h300 ||
	      mav_csrrxx_instr[31:20] == 12'h310 ||
	      mav_csrrxx_instr[31:20] == 12'h304 ||
	      mav_csrrxx_instr[31:20] == 12'h344 ||
	      mav_csrrxx_instr[31:20] == 12'h305 ||
	      mav_csrrxx_instr[31:20] == 12'h340 ||
	      mav_csrrxx_instr[31:20] == 12'h341 ||
	      mav_csrrxx_instr[31:20] == 12'h342 ||
	      mav_csrrxx_instr[31:20] == 12'h343 ||
	      mav_csrrxx_instr[31:20] == 12'hC00 ||
	      mav_csrrxx_instr[31:20] == 12'hC80 ||
	      mav_csrrxx_instr[31:20] == 12'hB00 ||
	      mav_csrrxx_instr[31:20] == 12'hB80 ||
	      mav_csrrxx_instr[31:20] == 12'hC01 ||
	      mav_csrrxx_instr[31:20] == 12'hC81 ||
	      mav_csrrxx_instr[31:20] == 12'hB02 ||
	      mav_csrrxx_instr[31:20] == 12'hB82 ||
	      mav_csrrxx_instr[31:20] == 12'hC02 ||
	      mav_csrrxx_instr[31:20] == 12'hC82 ||
	      mav_csrrxx_instr[31:20] == 12'h7B0 ||
	      mav_csrrxx_instr[31:20] == 12'h7B1) &&
	     rg_flog != 32'd0 ;
  assign NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d227 =
	     mav_csrrxx_instr[13:12] != 2'b01 &&
	     mav_csrrxx_instr[19:15] != 5'd0 &&
	     (mav_csrrxx_instr[31:20] == 12'hB00 ||
	      mav_csrrxx_instr[31:20] == 12'hB80) ;
  assign NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d258 =
	     mav_csrrxx_instr[13:12] != 2'b01 &&
	     mav_csrrxx_instr[19:15] != 5'd0 &&
	     (mav_csrrxx_instr[31:20] == 12'hB02 ||
	      mav_csrrxx_instr[31:20] == 12'hB82) ;
  assign NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d347 =
	     mav_csrrxx_instr[13:12] != 2'b01 &&
	     mav_csrrxx_instr[31:20] != 12'h301 &&
	     mav_csrrxx_instr[31:20] != 12'hF11 &&
	     mav_csrrxx_instr[31:20] != 12'hF12 &&
	     mav_csrrxx_instr[31:20] != 12'hF13 &&
	     mav_csrrxx_instr[31:20] != 12'hF14 &&
	     mav_csrrxx_instr[31:20] != 12'h300 &&
	     mav_csrrxx_instr[31:20] != 12'h310 &&
	     mav_csrrxx_instr[31:20] != 12'h304 &&
	     mav_csrrxx_instr[31:20] != 12'h344 &&
	     mav_csrrxx_instr[31:20] != 12'h305 &&
	     mav_csrrxx_instr[31:20] != 12'h340 &&
	     mav_csrrxx_instr[31:20] != 12'h341 &&
	     mav_csrrxx_instr[31:20] != 12'h342 &&
	     mav_csrrxx_instr[31:20] != 12'h343 &&
	     mav_csrrxx_instr[31:20] != 12'hC00 &&
	     mav_csrrxx_instr[31:20] != 12'hC80 &&
	     mav_csrrxx_instr[31:20] != 12'hB00 &&
	     mav_csrrxx_instr[31:20] != 12'hB80 &&
	     mav_csrrxx_instr[31:20] != 12'hC01 &&
	     mav_csrrxx_instr[31:20] != 12'hC81 &&
	     mav_csrrxx_instr[31:20] != 12'hB02 &&
	     mav_csrrxx_instr[31:20] != 12'hB82 &&
	     mav_csrrxx_instr[31:20] != 12'hC02 &&
	     mav_csrrxx_instr[31:20] != 12'hC82 &&
	     mav_csrrxx_instr[31:20] != 12'h7B0 &&
	     mav_csrrxx_instr[31:20] != 12'h7B1 &&
	     rg_flog != 32'd0 ;
  assign NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d348 =
	     mav_csrrxx_instr[13:12] != 2'b01 &&
	     (mav_csrrxx_instr[31:20] == 12'h301 ||
	      mav_csrrxx_instr[31:20] == 12'hF11 ||
	      mav_csrrxx_instr[31:20] == 12'hF12 ||
	      mav_csrrxx_instr[31:20] == 12'hF13 ||
	      mav_csrrxx_instr[31:20] == 12'hF14 ||
	      mav_csrrxx_instr[31:20] == 12'h300 ||
	      mav_csrrxx_instr[31:20] == 12'h310 ||
	      mav_csrrxx_instr[31:20] == 12'h304 ||
	      mav_csrrxx_instr[31:20] == 12'h344 ||
	      mav_csrrxx_instr[31:20] == 12'h305 ||
	      mav_csrrxx_instr[31:20] == 12'h340 ||
	      mav_csrrxx_instr[31:20] == 12'h341 ||
	      mav_csrrxx_instr[31:20] == 12'h342 ||
	      mav_csrrxx_instr[31:20] == 12'h343 ||
	      mav_csrrxx_instr[31:20] == 12'hC00 ||
	      mav_csrrxx_instr[31:20] == 12'hC80 ||
	      mav_csrrxx_instr[31:20] == 12'hB00 ||
	      mav_csrrxx_instr[31:20] == 12'hB80 ||
	      mav_csrrxx_instr[31:20] == 12'hC01 ||
	      mav_csrrxx_instr[31:20] == 12'hC81 ||
	      mav_csrrxx_instr[31:20] == 12'hB02 ||
	      mav_csrrxx_instr[31:20] == 12'hB82 ||
	      mav_csrrxx_instr[31:20] == 12'hC02 ||
	      mav_csrrxx_instr[31:20] == 12'hC82 ||
	      mav_csrrxx_instr[31:20] == 12'h7B0 ||
	      mav_csrrxx_instr[31:20] == 12'h7B1) &&
	     rg_flog != 32'd0 ;
  assign _0_CONCAT_IF_mav_csrrxx_instr_BITS_13_TO_12_0_E_ETC___d130 =
	     { 18'd0,
	       (mav_csrrxx_instr[13:12] == 2'b01) ?
		 _theResult____h1312[13] :
		 v_new__h4901[13],
	       1'd0,
	       (mav_csrrxx_instr[13:12] == 2'b01) ?
		 _theResult____h1312[11] :
		 v_new__h4901[11],
	       1'd0,
	       (mav_csrrxx_instr[13:12] == 2'b01) ?
		 _theResult____h1312[9] :
		 v_new__h4901[9],
	       1'd0 } ;
  assign _0_CONCAT_IF_mav_csrrxx_instr_BITS_13_TO_12_0_E_ETC___d134 =
	     { _0_CONCAT_IF_mav_csrrxx_instr_BITS_13_TO_12_0_E_ETC___d130,
	       (mav_csrrxx_instr[13:12] == 2'b01) ?
		 _theResult____h1312[7] :
		 v_new__h4901[7],
	       1'd0 } ;
  assign _0_CONCAT_IF_mav_csrrxx_instr_BITS_13_TO_12_0_E_ETC___d138 =
	     { _0_CONCAT_IF_mav_csrrxx_instr_BITS_13_TO_12_0_E_ETC___d134,
	       (mav_csrrxx_instr[13:12] == 2'b01) ?
		 _theResult____h1312[5] :
		 v_new__h4901[5],
	       1'd0 } ;
  assign _0_CONCAT_IF_mav_csrrxx_instr_BITS_13_TO_12_0_E_ETC___d142 =
	     { _0_CONCAT_IF_mav_csrrxx_instr_BITS_13_TO_12_0_E_ETC___d138,
	       (mav_csrrxx_instr[13:12] == 2'b01) ?
		 _theResult____h1312[3] :
		 v_new__h4901[3],
	       1'd0 } ;
  assign _dfoo1 =
	     mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1_AND__ETC___d255 ||
	     NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d258 ||
	     ((mav_csrrxx_instr[13:12] == 2'b01) ?
		mav_csrrxx_instr[31:20] != 12'hB02 &&
		mav_csrrxx_instr[31:20] != 12'hB82 :
		mav_csrrxx_instr[19:15] == 5'd0 ||
		mav_csrrxx_instr[31:20] != 12'hB02 &&
		mav_csrrxx_instr[31:20] != 12'hB82) ;
  assign _theResult____h1312 =
	     mav_csrrxx_instr[14] ?
	       { 27'd0, mav_csrrxx_instr[19:15] } :
	       mav_csrrxx_rs1_val ;
  assign _theResult____h6613 =
	     { csr_mstatus[31:8],
	       csr_mstatus[3],
	       csr_mstatus[6:4],
	       1'd0,
	       csr_mstatus[2:0] } ;
  assign _theResult____h7037 =
	     csr_mstatus[7] ? new_mstatus___1__h7088 : new_mstatus__h7036 ;
  assign base__h6614 = { csr_mtvec[31:2], 2'd0 } ;
  assign mav_csrrxx_instr_BITS_11_TO_7_80_EQ_0_81_OR_ma_ETC___d338 =
	     (mav_csrrxx_instr[11:7] == 5'd0 ||
	      mav_csrrxx_instr[31:20] == 12'h301 ||
	      mav_csrrxx_instr[31:20] == 12'hF11 ||
	      mav_csrrxx_instr[31:20] == 12'hF12 ||
	      mav_csrrxx_instr[31:20] == 12'hF13 ||
	      mav_csrrxx_instr[31:20] == 12'hF14 ||
	      mav_csrrxx_instr[31:20] == 12'h300 ||
	      mav_csrrxx_instr[31:20] == 12'h310 ||
	      mav_csrrxx_instr[31:20] == 12'h304 ||
	      mav_csrrxx_instr[31:20] == 12'h344 ||
	      mav_csrrxx_instr[31:20] == 12'h305 ||
	      mav_csrrxx_instr[31:20] == 12'h340 ||
	      mav_csrrxx_instr[31:20] == 12'h341 ||
	      mav_csrrxx_instr[31:20] == 12'h342 ||
	      mav_csrrxx_instr[31:20] == 12'h343 ||
	      mav_csrrxx_instr[31:20] == 12'hC00 ||
	      mav_csrrxx_instr[31:20] == 12'hC80 ||
	      mav_csrrxx_instr[31:20] == 12'hB00 ||
	      mav_csrrxx_instr[31:20] == 12'hB80 ||
	      mav_csrrxx_instr[31:20] == 12'hC01 ||
	      mav_csrrxx_instr[31:20] == 12'hC81 ||
	      mav_csrrxx_instr[31:20] == 12'hB02 ||
	      mav_csrrxx_instr[31:20] == 12'hB82 ||
	      mav_csrrxx_instr[31:20] == 12'hC02 ||
	      mav_csrrxx_instr[31:20] == 12'hC82 ||
	      mav_csrrxx_instr[31:20] == 12'h7B0 ||
	      mav_csrrxx_instr[31:20] == 12'h7B1) &&
	     rg_flog != 32'd0 ;
  assign mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1_AND__ETC___d224 =
	     mav_csrrxx_instr[13:12] == 2'b01 &&
	     (mav_csrrxx_instr[31:20] == 12'hB00 ||
	      mav_csrrxx_instr[31:20] == 12'hB80) ;
  assign mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1_AND__ETC___d255 =
	     mav_csrrxx_instr[13:12] == 2'b01 &&
	     (mav_csrrxx_instr[31:20] == 12'hB02 ||
	      mav_csrrxx_instr[31:20] == 12'hB82) ;
  assign mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_OR_ETC___d350 =
	     (mav_csrrxx_instr[31:20] == 12'h301 ||
	      mav_csrrxx_instr[31:20] == 12'hF11 ||
	      mav_csrrxx_instr[31:20] == 12'hF12 ||
	      mav_csrrxx_instr[31:20] == 12'hF13 ||
	      mav_csrrxx_instr[31:20] == 12'hF14 ||
	      mav_csrrxx_instr[31:20] == 12'h300 ||
	      mav_csrrxx_instr[31:20] == 12'h310 ||
	      mav_csrrxx_instr[31:20] == 12'h304 ||
	      mav_csrrxx_instr[31:20] == 12'h344 ||
	      mav_csrrxx_instr[31:20] == 12'h305 ||
	      mav_csrrxx_instr[31:20] == 12'h340 ||
	      mav_csrrxx_instr[31:20] == 12'h341 ||
	      mav_csrrxx_instr[31:20] == 12'h342 ||
	      mav_csrrxx_instr[31:20] == 12'h343 ||
	      mav_csrrxx_instr[31:20] == 12'hC00 ||
	      mav_csrrxx_instr[31:20] == 12'hC80 ||
	      mav_csrrxx_instr[31:20] == 12'hB00 ||
	      mav_csrrxx_instr[31:20] == 12'hB80 ||
	      mav_csrrxx_instr[31:20] == 12'hC01 ||
	      mav_csrrxx_instr[31:20] == 12'hC81 ||
	      mav_csrrxx_instr[31:20] == 12'hB02 ||
	      mav_csrrxx_instr[31:20] == 12'hB82 ||
	      mav_csrrxx_instr[31:20] == 12'hC02 ||
	      mav_csrrxx_instr[31:20] == 12'hC82 ||
	      mav_csrrxx_instr[31:20] == 12'h7B0 ||
	      mav_csrrxx_instr[31:20] == 12'h7B1) &&
	     mav_csrrxx_instr[19:15] != 5'd0 &&
	     rg_flog != 32'd0 ;
  assign mcause_msb__h6539 =
	     mav_exception_is_interrupt ? 32'h80000000 : 32'd0 ;
  assign mode__h3216 =
	     _theResult____h1312[1] ?
	       csr_mtvec[1:0] :
	       _theResult____h1312[1:0] ;
  assign mode__h5653 = v_new__h4901[1] ? csr_mtvec[1:0] : v_new__h4901[1:0] ;
  assign mode__h8226 =
	     csr_write_csr_val[1] ? csr_mtvec[1:0] : csr_write_csr_val[1:0] ;
  assign new_cause_prv__h9897 =
	     { 23'd0,
	       save_dpc_dcsr_cause_prv_cause,
	       4'h0,
	       save_dpc_dcsr_cause_prv_prv } ;
  assign new_mstatus___1__h7088 =
	     { csr_mstatus[31:8],
	       1'd1,
	       csr_mstatus[6:4],
	       1'd1,
	       csr_mstatus[2:0] } ;
  assign new_mstatus__h7036 =
	     { csr_mstatus[31:8],
	       1'd1,
	       csr_mstatus[6:4],
	       1'd0,
	       csr_mstatus[2:0] } ;
  assign v_new__h4901 =
	     (mav_csrrxx_instr[13:12] == 2'b10) ?
	       IF_mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_ETC___d104 :
	       IF_mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_ETC___d106 ;
  assign x1__h3421 =
	     { csr_mcycle$port0__write_1[63:32], _theResult____h1312 } ;
  assign x1__h3503 =
	     { _theResult____h1312, csr_mcycle$port0__write_1[31:0] } ;
  assign x1__h5857 = { csr_mcycle$port0__write_1[63:32], v_new__h4901 } ;
  assign x1__h5939 = { v_new__h4901, csr_mcycle$port0__write_1[31:0] } ;
  assign x1__h8429 = { csr_mcycle$port0__write_1[63:32], csr_write_csr_val } ;
  assign x1__h8510 = { csr_write_csr_val, csr_mcycle$port0__write_1[31:0] } ;
  assign x__h2177 = { csr_mip_mtip, 7'b0 } ;
  assign x__h3044 =
	     (_theResult____h1312[12:11] == 2'b11) ?
	       _theResult____h1312 :
	       y___1__h3086 ;
  assign x__h3194 = { _theResult____h1312[31:2], mode__h3216 } ;
  assign x__h3578 = { csr_minstret[63:32], _theResult____h1312 } ;
  assign x__h3658 = { _theResult____h1312, csr_minstret[31:0] } ;
  assign x__h5487 =
	     (v_new__h4901[12:11] == 2'b11) ? v_new__h4901 : y___1__h5529 ;
  assign x__h5631 = { v_new__h4901[31:2], mode__h5653 } ;
  assign x__h6014 = { csr_minstret[63:32], v_new__h4901 } ;
  assign x__h6094 = { v_new__h4901, csr_minstret[31:0] } ;
  assign x__h6448 = csr_minstret + 64'd1 ;
  assign x__h8584 = { csr_minstret[63:32], csr_write_csr_val } ;
  assign x__h8663 = { csr_write_csr_val, csr_minstret[31:0] } ;
  assign x__h9912 = { csr_dcsr[31:9], 3'd0, csr_dcsr[5:2], 2'd0 } ;
  assign y___1__h3086 =
	     { _theResult____h1312[31:13], 2'd3, _theResult____h1312[10:0] } ;
  assign y___1__h5529 = { v_new__h4901[31:13], 2'd3, v_new__h4901[10:0] } ;
  assign y___1__h8102 =
	     { csr_write_csr_val[31:13], 2'd3, csr_write_csr_val[10:0] } ;
  assign y__h1762 = { 24'd0, x__h2177 } ;
  assign y__h5215 = ~_theResult____h1312 ;
  always@(mav_csrrxx_instr or
	  csr_dpc or
	  csr_mstatus or
	  csr_mie or
	  csr_mtvec or
	  csr_mscratch or
	  csr_mepc or
	  csr_mcause or
	  csr_mtval or
	  y__h1762 or
	  csr_dcsr or csr_mcycle$port0__write_1 or csr_minstret or set_TIME_t)
  begin
    case (mav_csrrxx_instr[31:20])
      12'h300: y__h1700 = csr_mstatus;
      12'h301: y__h1700 = 32'd1073742080;
      12'h304: y__h1700 = csr_mie;
      12'h305: y__h1700 = csr_mtvec;
      12'h310, 12'hF11, 12'hF12, 12'hF13, 12'hF14: y__h1700 = 32'd0;
      12'h340: y__h1700 = csr_mscratch;
      12'h341: y__h1700 = csr_mepc;
      12'h342: y__h1700 = csr_mcause;
      12'h343: y__h1700 = csr_mtval;
      12'h344: y__h1700 = y__h1762;
      12'h7B0: y__h1700 = csr_dcsr;
      12'hB00, 12'hC00: y__h1700 = csr_mcycle$port0__write_1[31:0];
      12'hB02, 12'hC02: y__h1700 = csr_minstret[31:0];
      12'hB80, 12'hC80: y__h1700 = csr_mcycle$port0__write_1[63:32];
      12'hB82, 12'hC82: y__h1700 = csr_minstret[63:32];
      12'hC01: y__h1700 = set_TIME_t[31:0];
      12'hC81: y__h1700 = set_TIME_t[63:32];
      default: y__h1700 = csr_dpc;
    endcase
  end
  always@(csr_read_csr_addr or
	  csr_dpc or
	  csr_mstatus or
	  csr_mie or
	  csr_mtvec or
	  csr_mscratch or
	  csr_mepc or
	  csr_mcause or
	  csr_mtval or
	  y__h1762 or
	  csr_dcsr or csr_mcycle$port0__write_1 or csr_minstret or set_TIME_t)
  begin
    case (csr_read_csr_addr)
      12'h300: y__h9196 = csr_mstatus;
      12'h301: y__h9196 = 32'd1073742080;
      12'h304: y__h9196 = csr_mie;
      12'h305: y__h9196 = csr_mtvec;
      12'h310, 12'hF11, 12'hF12, 12'hF13, 12'hF14: y__h9196 = 32'd0;
      12'h340: y__h9196 = csr_mscratch;
      12'h341: y__h9196 = csr_mepc;
      12'h342: y__h9196 = csr_mcause;
      12'h343: y__h9196 = csr_mtval;
      12'h344: y__h9196 = y__h1762;
      12'h7B0: y__h9196 = csr_dcsr;
      12'hB00, 12'hC00: y__h9196 = csr_mcycle$port0__write_1[31:0];
      12'hB02, 12'hC02: y__h9196 = csr_minstret[31:0];
      12'hB80, 12'hC80: y__h9196 = csr_mcycle$port0__write_1[63:32];
      12'hB82, 12'hC82: y__h9196 = csr_minstret[63:32];
      12'hC01: y__h9196 = set_TIME_t[31:0];
      12'hC81: y__h9196 = set_TIME_t[63:32];
      default: y__h9196 = csr_dpc;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        crg_csr_TIME <= `BSV_ASSIGNMENT_DELAY 64'd0;
	csr_dcsr <= `BSV_ASSIGNMENT_DELAY 32'd0;
	csr_mcause <= `BSV_ASSIGNMENT_DELAY 32'd0;
	csr_mcycle <= `BSV_ASSIGNMENT_DELAY 64'd0;
	csr_mepc <= `BSV_ASSIGNMENT_DELAY 32'd0;
	csr_mie <= `BSV_ASSIGNMENT_DELAY 32'd0;
	csr_minstret <= `BSV_ASSIGNMENT_DELAY 64'd0;
	csr_mip_mtip <= `BSV_ASSIGNMENT_DELAY 1'd0;
	csr_mscratch <= `BSV_ASSIGNMENT_DELAY 32'd0;
	csr_mstatus <= `BSV_ASSIGNMENT_DELAY 32'd0;
	csr_mtval <= `BSV_ASSIGNMENT_DELAY 32'd0;
	csr_mtvec <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rg_flog <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (crg_csr_TIME$EN)
	  crg_csr_TIME <= `BSV_ASSIGNMENT_DELAY crg_csr_TIME$D_IN;
	if (csr_dcsr$EN) csr_dcsr <= `BSV_ASSIGNMENT_DELAY csr_dcsr$D_IN;
	if (csr_mcause$EN)
	  csr_mcause <= `BSV_ASSIGNMENT_DELAY csr_mcause$D_IN;
	if (csr_mcycle$EN)
	  csr_mcycle <= `BSV_ASSIGNMENT_DELAY csr_mcycle$D_IN;
	if (csr_mepc$EN) csr_mepc <= `BSV_ASSIGNMENT_DELAY csr_mepc$D_IN;
	if (csr_mie$EN) csr_mie <= `BSV_ASSIGNMENT_DELAY csr_mie$D_IN;
	if (csr_minstret$EN)
	  csr_minstret <= `BSV_ASSIGNMENT_DELAY csr_minstret$D_IN;
	if (csr_mip_mtip$EN)
	  csr_mip_mtip <= `BSV_ASSIGNMENT_DELAY csr_mip_mtip$D_IN;
	if (csr_mscratch$EN)
	  csr_mscratch <= `BSV_ASSIGNMENT_DELAY csr_mscratch$D_IN;
	if (csr_mstatus$EN)
	  csr_mstatus <= `BSV_ASSIGNMENT_DELAY csr_mstatus$D_IN;
	if (csr_mtval$EN) csr_mtval <= `BSV_ASSIGNMENT_DELAY csr_mtval$D_IN;
	if (csr_mtvec$EN) csr_mtvec <= `BSV_ASSIGNMENT_DELAY csr_mtvec$D_IN;
	if (rg_flog$EN) rg_flog <= `BSV_ASSIGNMENT_DELAY rg_flog$D_IN;
      end
    if (csr_dpc$EN) csr_dpc <= `BSV_ASSIGNMENT_DELAY csr_dpc$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    crg_csr_TIME = 64'hAAAAAAAAAAAAAAAA;
    csr_dcsr = 32'hAAAAAAAA;
    csr_dpc = 32'hAAAAAAAA;
    csr_mcause = 32'hAAAAAAAA;
    csr_mcycle = 64'hAAAAAAAAAAAAAAAA;
    csr_mepc = 32'hAAAAAAAA;
    csr_mie = 32'hAAAAAAAA;
    csr_minstret = 64'hAAAAAAAAAAAAAAAA;
    csr_mip_mtip = 1'h0;
    csr_mscratch = 32'hAAAAAAAA;
    csr_mstatus = 32'hAAAAAAAA;
    csr_mtval = 32'hAAAAAAAA;
    csr_mtvec = 32'hAAAAAAAA;
    rg_flog = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_csr_read && rg_flog != 32'd0)
	begin
	  v__h8964 = $stime;
	  #0;
	end
    x__h8997 = v__h8964 + 32'd5;
    v__h8956 = x__h8997 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_csr_read && rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h8956);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_csr_read && rg_flog != 32'd0)
	$fwrite(rg_flog, "CSRs: Reading csr_addr %03h", csr_read_csr_addr);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_csr_read && rg_flog != 32'd0) $fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_csr_read && csr_read_csr_addr != 12'h301 &&
	  csr_read_csr_addr != 12'hF11 &&
	  csr_read_csr_addr != 12'hF12 &&
	  csr_read_csr_addr != 12'hF13 &&
	  csr_read_csr_addr != 12'hF14 &&
	  csr_read_csr_addr != 12'h300 &&
	  csr_read_csr_addr != 12'h310 &&
	  csr_read_csr_addr != 12'h304 &&
	  csr_read_csr_addr != 12'h344 &&
	  csr_read_csr_addr != 12'h305 &&
	  csr_read_csr_addr != 12'h340 &&
	  csr_read_csr_addr != 12'h341 &&
	  csr_read_csr_addr != 12'h342 &&
	  csr_read_csr_addr != 12'h343 &&
	  csr_read_csr_addr != 12'hC00 &&
	  csr_read_csr_addr != 12'hC80 &&
	  csr_read_csr_addr != 12'hB00 &&
	  csr_read_csr_addr != 12'hB80 &&
	  csr_read_csr_addr != 12'hC01 &&
	  csr_read_csr_addr != 12'hC81 &&
	  csr_read_csr_addr != 12'hB02 &&
	  csr_read_csr_addr != 12'hB82 &&
	  csr_read_csr_addr != 12'hC02 &&
	  csr_read_csr_addr != 12'hC82 &&
	  csr_read_csr_addr != 12'h7B0 &&
	  csr_read_csr_addr != 12'h7B1 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "    => exception");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_csr_read && csr_read_csr_addr != 12'h301 &&
	  csr_read_csr_addr != 12'hF11 &&
	  csr_read_csr_addr != 12'hF12 &&
	  csr_read_csr_addr != 12'hF13 &&
	  csr_read_csr_addr != 12'hF14 &&
	  csr_read_csr_addr != 12'h300 &&
	  csr_read_csr_addr != 12'h310 &&
	  csr_read_csr_addr != 12'h304 &&
	  csr_read_csr_addr != 12'h344 &&
	  csr_read_csr_addr != 12'h305 &&
	  csr_read_csr_addr != 12'h340 &&
	  csr_read_csr_addr != 12'h341 &&
	  csr_read_csr_addr != 12'h342 &&
	  csr_read_csr_addr != 12'h343 &&
	  csr_read_csr_addr != 12'hC00 &&
	  csr_read_csr_addr != 12'hC80 &&
	  csr_read_csr_addr != 12'hB00 &&
	  csr_read_csr_addr != 12'hB80 &&
	  csr_read_csr_addr != 12'hC01 &&
	  csr_read_csr_addr != 12'hC81 &&
	  csr_read_csr_addr != 12'hB02 &&
	  csr_read_csr_addr != 12'hB82 &&
	  csr_read_csr_addr != 12'hC02 &&
	  csr_read_csr_addr != 12'hC82 &&
	  csr_read_csr_addr != 12'h7B0 &&
	  csr_read_csr_addr != 12'h7B1 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_csr_read &&
	  (csr_read_csr_addr == 12'h301 || csr_read_csr_addr == 12'hF11 ||
	   csr_read_csr_addr == 12'hF12 ||
	   csr_read_csr_addr == 12'hF13 ||
	   csr_read_csr_addr == 12'hF14 ||
	   csr_read_csr_addr == 12'h300 ||
	   csr_read_csr_addr == 12'h310 ||
	   csr_read_csr_addr == 12'h304 ||
	   csr_read_csr_addr == 12'h344 ||
	   csr_read_csr_addr == 12'h305 ||
	   csr_read_csr_addr == 12'h340 ||
	   csr_read_csr_addr == 12'h341 ||
	   csr_read_csr_addr == 12'h342 ||
	   csr_read_csr_addr == 12'h343 ||
	   csr_read_csr_addr == 12'hC00 ||
	   csr_read_csr_addr == 12'hC80 ||
	   csr_read_csr_addr == 12'hB00 ||
	   csr_read_csr_addr == 12'hB80 ||
	   csr_read_csr_addr == 12'hC01 ||
	   csr_read_csr_addr == 12'hC81 ||
	   csr_read_csr_addr == 12'hB02 ||
	   csr_read_csr_addr == 12'hB82 ||
	   csr_read_csr_addr == 12'hC02 ||
	   csr_read_csr_addr == 12'hC82 ||
	   csr_read_csr_addr == 12'h7B0 ||
	   csr_read_csr_addr == 12'h7B1) &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "    => rd_val:%08h", y__h9196);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_csr_read &&
	  (csr_read_csr_addr == 12'h301 || csr_read_csr_addr == 12'hF11 ||
	   csr_read_csr_addr == 12'hF12 ||
	   csr_read_csr_addr == 12'hF13 ||
	   csr_read_csr_addr == 12'hF14 ||
	   csr_read_csr_addr == 12'h300 ||
	   csr_read_csr_addr == 12'h310 ||
	   csr_read_csr_addr == 12'h304 ||
	   csr_read_csr_addr == 12'h344 ||
	   csr_read_csr_addr == 12'h305 ||
	   csr_read_csr_addr == 12'h340 ||
	   csr_read_csr_addr == 12'h341 ||
	   csr_read_csr_addr == 12'h342 ||
	   csr_read_csr_addr == 12'h343 ||
	   csr_read_csr_addr == 12'hC00 ||
	   csr_read_csr_addr == 12'hC80 ||
	   csr_read_csr_addr == 12'hB00 ||
	   csr_read_csr_addr == 12'hB80 ||
	   csr_read_csr_addr == 12'hC01 ||
	   csr_read_csr_addr == 12'hC81 ||
	   csr_read_csr_addr == 12'hB02 ||
	   csr_read_csr_addr == 12'hB82 ||
	   csr_read_csr_addr == 12'hC02 ||
	   csr_read_csr_addr == 12'hC82 ||
	   csr_read_csr_addr == 12'h7B0 ||
	   csr_read_csr_addr == 12'h7B1) &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && rg_flog != 32'd0)
	begin
	  v__h1078 = $stime;
	  #0;
	end
    x__h1111 = v__h1078 + 32'd5;
    v__h1070 = x__h1111 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h1070);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && rg_flog != 32'd0)
	$fwrite(rg_flog,
		"CSRs: csrrxx instr %08h rs1_val %08h",
		mav_csrrxx_instr,
		mav_csrrxx_rs1_val);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && rg_flog != 32'd0) $fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] == 2'b01 &&
	  mav_csrrxx_instr[11:7] != 5'd0 &&
	  rg_flog != 32'd0)
	begin
	  v__h1449 = $stime;
	  #0;
	end
    x__h1482 = v__h1449 + 32'd5;
    v__h1441 = x__h1482 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] == 2'b01 &&
	  mav_csrrxx_instr[11:7] != 5'd0 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h1441);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] == 2'b01 &&
	  mav_csrrxx_instr[11:7] != 5'd0 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog,
		"CSRs: Reading csr_addr %03h",
		mav_csrrxx_instr[31:20]);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] == 2'b01 &&
	  mav_csrrxx_instr[11:7] != 5'd0 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] == 2'b01 &&
	  NOT_mav_csrrxx_instr_BITS_11_TO_7_80_EQ_0_81_7_ETC___d317)
	$fwrite(rg_flog, "    => exception");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] == 2'b01 &&
	  NOT_mav_csrrxx_instr_BITS_11_TO_7_80_EQ_0_81_7_ETC___d317)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] == 2'b01 &&
	  NOT_mav_csrrxx_instr_BITS_11_TO_7_80_EQ_0_81_7_ETC___d335)
	$fwrite(rg_flog, "    => rd_val:%08h", y__h1700);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] == 2'b01 &&
	  NOT_mav_csrrxx_instr_BITS_11_TO_7_80_EQ_0_81_7_ETC___d335)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] == 2'b01 &&
	  mav_csrrxx_instr_BITS_11_TO_7_80_EQ_0_81_OR_ma_ETC___d338)
	begin
	  v__h2501 = $stime;
	  #0;
	end
    x__h2534 = v__h2501 + 32'd5;
    v__h2493 = x__h2534 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] == 2'b01 &&
	  mav_csrrxx_instr_BITS_11_TO_7_80_EQ_0_81_OR_ma_ETC___d338)
	$fwrite(rg_flog, "%0d: ", v__h2493);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] == 2'b01 &&
	  mav_csrrxx_instr_BITS_11_TO_7_80_EQ_0_81_OR_ma_ETC___d338)
	$fwrite(rg_flog,
		"CSRs: Writing csr_addr %03h <= %08h",
		mav_csrrxx_instr[31:20],
		_theResult____h1312);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] == 2'b01 &&
	  mav_csrrxx_instr_BITS_11_TO_7_80_EQ_0_81_OR_ma_ETC___d338)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] != 2'b01 &&
	  rg_flog != 32'd0)
	begin
	  v__h3990 = $stime;
	  #0;
	end
    x__h4023 = v__h3990 + 32'd5;
    v__h3982 = x__h4023 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] != 2'b01 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h3982);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] != 2'b01 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog,
		"CSRs: Reading csr_addr %03h",
		mav_csrrxx_instr[31:20]);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] != 2'b01 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx &&
	  NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d347)
	$fwrite(rg_flog, "    => exception");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx &&
	  NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d347)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx &&
	  NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d348)
	$fwrite(rg_flog, "    => rd_val:%08h", y__h1700);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx &&
	  NOT_mav_csrrxx_instr_BITS_13_TO_12_0_EQ_0b1_1__ETC___d348)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] != 2'b01 &&
	  mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_OR_ETC___d350)
	begin
	  v__h4956 = $stime;
	  #0;
	end
    x__h4989 = v__h4956 + 32'd5;
    v__h4948 = x__h4989 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] != 2'b01 &&
	  mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_OR_ETC___d350)
	$fwrite(rg_flog, "%0d: ", v__h4948);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] != 2'b01 &&
	  mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_OR_ETC___d350)
	$fwrite(rg_flog,
		"CSRs: Writing csr_addr %03h <= %08h",
		mav_csrrxx_instr[31:20],
		v_new__h4901);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_csrrxx && mav_csrrxx_instr[13:12] != 2'b01 &&
	  mav_csrrxx_instr_BITS_31_TO_20_2_EQ_0x301_2_OR_ETC___d350)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_exception && rg_flog != 32'd0)
	begin
	  v__h6752 = $stime;
	  #0;
	end
    x__h6785 = v__h6752 + 32'd5;
    v__h6744 = x__h6785 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_exception && rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h6744);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_exception && rg_flog != 32'd0)
	$fwrite(rg_flog,
		"CSRs: fav_exception mstatus %08h => %08h",
		csr_mstatus,
		_theResult____h6613);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_exception && rg_flog != 32'd0) $fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_xRET && rg_flog != 32'd0)
	begin
	  v__h7161 = $stime;
	  #0;
	end
    x__h7194 = v__h7161 + 32'd5;
    v__h7153 = x__h7194 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_xRET && rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h7153);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_xRET && rg_flog != 32'd0)
	$fwrite(rg_flog,
		"CSRs: fav_xRET mstatus %08h => %08h",
		csr_mstatus,
		_theResult____h7037);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_xRET && rg_flog != 32'd0) $fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_csr_write && rg_flog != 32'd0)
	begin
	  v__h7566 = $stime;
	  #0;
	end
    x__h7599 = v__h7566 + 32'd5;
    v__h7558 = x__h7599 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_csr_write && rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h7558);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_csr_write && rg_flog != 32'd0)
	$fwrite(rg_flog,
		"CSRs: Writing csr_addr %03h <= %08h",
		csr_write_csr_addr,
		csr_write_csr_val);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_csr_write && rg_flog != 32'd0) $fwrite(rg_flog, "\n");
  end
  // synopsys translate_on
endmodule  // mkCSRs

