//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:42 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_init                       O     1 const
// RDY_fi_Fetch_to_Decode_enq     O     1 reg
// fi_Fetch_to_Decode_notFull     O     1 reg
// RDY_fi_Fetch_to_Decode_notFull  O     1 const
// RDY_fi_IMem_to_Decode_enq      O     1
// fi_IMem_to_Decode_notFull      O     1
// RDY_fi_IMem_to_Decode_notFull  O     1 const
// fo_Decode_to_RR_first          O   271
// RDY_fo_Decode_to_RR_first      O     1
// RDY_fo_Decode_to_RR_deq        O     1
// fo_Decode_to_RR_notEmpty       O     1
// RDY_fo_Decode_to_RR_notEmpty   O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// init_initial_params            I   208 reg
// fi_Fetch_to_Decode_enq_x       I   131 reg
// fi_IMem_to_Decode_enq_x        I   265
// EN_init                        I     1
// EN_fi_Fetch_to_Decode_enq      I     1
// EN_fi_IMem_to_Decode_enq       I     1
// EN_fo_Decode_to_RR_deq         I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkDecode(CLK,
		RST_N,

		init_initial_params,
		EN_init,
		RDY_init,

		fi_Fetch_to_Decode_enq_x,
		EN_fi_Fetch_to_Decode_enq,
		RDY_fi_Fetch_to_Decode_enq,

		fi_Fetch_to_Decode_notFull,
		RDY_fi_Fetch_to_Decode_notFull,

		fi_IMem_to_Decode_enq_x,
		EN_fi_IMem_to_Decode_enq,
		RDY_fi_IMem_to_Decode_enq,

		fi_IMem_to_Decode_notFull,
		RDY_fi_IMem_to_Decode_notFull,

		fo_Decode_to_RR_first,
		RDY_fo_Decode_to_RR_first,

		EN_fo_Decode_to_RR_deq,
		RDY_fo_Decode_to_RR_deq,

		fo_Decode_to_RR_notEmpty,
		RDY_fo_Decode_to_RR_notEmpty);
  input  CLK;
  input  RST_N;

  // action method init
  input  [207 : 0] init_initial_params;
  input  EN_init;
  output RDY_init;

  // action method fi_Fetch_to_Decode_enq
  input  [130 : 0] fi_Fetch_to_Decode_enq_x;
  input  EN_fi_Fetch_to_Decode_enq;
  output RDY_fi_Fetch_to_Decode_enq;

  // value method fi_Fetch_to_Decode_notFull
  output fi_Fetch_to_Decode_notFull;
  output RDY_fi_Fetch_to_Decode_notFull;

  // action method fi_IMem_to_Decode_enq
  input  [264 : 0] fi_IMem_to_Decode_enq_x;
  input  EN_fi_IMem_to_Decode_enq;
  output RDY_fi_IMem_to_Decode_enq;

  // value method fi_IMem_to_Decode_notFull
  output fi_IMem_to_Decode_notFull;
  output RDY_fi_IMem_to_Decode_notFull;

  // value method fo_Decode_to_RR_first
  output [270 : 0] fo_Decode_to_RR_first;
  output RDY_fo_Decode_to_RR_first;

  // action method fo_Decode_to_RR_deq
  input  EN_fo_Decode_to_RR_deq;
  output RDY_fo_Decode_to_RR_deq;

  // value method fo_Decode_to_RR_notEmpty
  output fo_Decode_to_RR_notEmpty;
  output RDY_fo_Decode_to_RR_notEmpty;

  // signals for module outputs
  wire [270 : 0] fo_Decode_to_RR_first;
  wire RDY_fi_Fetch_to_Decode_enq,
       RDY_fi_Fetch_to_Decode_notFull,
       RDY_fi_IMem_to_Decode_enq,
       RDY_fi_IMem_to_Decode_notFull,
       RDY_fo_Decode_to_RR_deq,
       RDY_fo_Decode_to_RR_first,
       RDY_fo_Decode_to_RR_notEmpty,
       RDY_init,
       fi_Fetch_to_Decode_notFull,
       fi_IMem_to_Decode_notFull,
       fo_Decode_to_RR_notEmpty;

  // inlined wires
  wire [271 : 0] f_Decode_to_RR_rv$port0__write_1,
		 f_Decode_to_RR_rv$port1__read,
		 f_Decode_to_RR_rv$port1__write_1,
		 f_Decode_to_RR_rv$port2__read;
  wire [265 : 0] f_IMem_to_Decode_rv$port0__write_1,
		 f_IMem_to_Decode_rv$port1__read,
		 f_IMem_to_Decode_rv$port1__write_1,
		 f_IMem_to_Decode_rv$port2__read;
  wire f_Decode_to_RR_rv$EN_port0__write;

  // register f_Decode_to_RR_rv
  reg [271 : 0] f_Decode_to_RR_rv;
  wire [271 : 0] f_Decode_to_RR_rv$D_IN;
  wire f_Decode_to_RR_rv$EN;

  // register f_IMem_to_Decode_rv
  reg [265 : 0] f_IMem_to_Decode_rv;
  wire [265 : 0] f_IMem_to_Decode_rv$D_IN;
  wire f_IMem_to_Decode_rv$EN;

  // register rg_flog
  reg [31 : 0] rg_flog;
  wire [31 : 0] rg_flog$D_IN;
  wire rg_flog$EN;

  // ports of submodule f_Fetch_to_Decode
  wire [130 : 0] f_Fetch_to_Decode$D_IN, f_Fetch_to_Decode$D_OUT;
  wire f_Fetch_to_Decode$CLR,
       f_Fetch_to_Decode$DEQ,
       f_Fetch_to_Decode$EMPTY_N,
       f_Fetch_to_Decode$ENQ,
       f_Fetch_to_Decode$FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_rl_Decode,
       CAN_FIRE_RL_rl_Decode_halting,
       CAN_FIRE_fi_Fetch_to_Decode_enq,
       CAN_FIRE_fi_IMem_to_Decode_enq,
       CAN_FIRE_fo_Decode_to_RR_deq,
       CAN_FIRE_init,
       WILL_FIRE_RL_rl_Decode,
       WILL_FIRE_RL_rl_Decode_halting,
       WILL_FIRE_fi_Fetch_to_Decode_enq,
       WILL_FIRE_fi_IMem_to_Decode_enq,
       WILL_FIRE_fo_Decode_to_RR_deq,
       WILL_FIRE_init;

  // inputs to muxes for submodule ports
  wire [271 : 0] MUX_f_Decode_to_RR_rv$port0__write_1__VAL_1,
		 MUX_f_Decode_to_RR_rv$port0__write_1__VAL_2;

  // declarations used by system tasks
  // synopsys translate_off
  reg [31 : 0] v__h968;
  reg [31 : 0] v__h1417;
  reg [31 : 0] v__h4246;
  reg [31 : 0] v__h4811;
  reg [31 : 0] v__h5150;
  reg [31 : 0] v__h5502;
  reg [31 : 0] x__h1001;
  reg [31 : 0] x__h1450;
  reg [31 : 0] x__h4279;
  reg [31 : 0] x__h4844;
  reg [31 : 0] x__h5183;
  reg [31 : 0] x__h5535;
  reg [31 : 0] v__h960;
  reg [31 : 0] v__h1409;
  reg [31 : 0] v__h4238;
  reg [31 : 0] v__h4803;
  reg [31 : 0] v__h5142;
  reg [31 : 0] v__h5494;
  // synopsys translate_on

  // remaining internal signals
  reg [31 : 0] CASE_f_IMem_to_Decode_rv_BITS_205_TO_199_0b101_ETC__q2,
	       x1_avValue_imm__h2782,
	       x1_avValue_tval__h2774;
  reg [3 : 0] x1_avValue_cause__h2773;
  reg [2 : 0] CASE_f_IMem_to_Decode_rv_BITS_205_TO_199_0b101_ETC__q3;
  reg IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d424;
  wire [102 : 0] IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d461;
  wire [31 : 0] IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d452,
		IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d453,
		IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d455,
		SEXT_f_IMem_to_Decode_rv_port0__read_BITS_230__ETC___d448,
		x1_avValue_fallthru_pc__h2775,
		x1_avValue_tval__h2724;
  wire [20 : 0] x__h3976;
  wire [12 : 0] x__h3889;
  wire [11 : 0] f_IMem_to_Decode_rv_BITS_230_TO_219__q1, x__h4087;
  wire [2 : 0] IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d360;
  wire IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d420,
       NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d202,
       NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d229,
       NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d258,
       NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d274,
       NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d278,
       NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d479,
       NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d516,
       NOT_f_IMem_to_Decode_rv_port0__read_BITS_264_T_ETC___d486,
       NOT_f_IMem_to_Decode_rv_port0__read_BITS_264_T_ETC___d524,
       NOT_f_IMem_to_Decode_rv_port0__read_BITS_264_T_ETC___d549,
       NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472,
       NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d508,
       NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d296,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d315,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d319,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d330,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d333,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d334,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d337,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d354,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d389,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d394,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d402,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d406,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d499,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d500,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d503,
       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d541,
       f_IMem_to_Decode_rv_port0__read_BITS_264_TO_26_ETC___d573;

  // action method init
  assign RDY_init = 1'd1 ;
  assign CAN_FIRE_init = 1'd1 ;
  assign WILL_FIRE_init = EN_init ;

  // action method fi_Fetch_to_Decode_enq
  assign RDY_fi_Fetch_to_Decode_enq = f_Fetch_to_Decode$FULL_N ;
  assign CAN_FIRE_fi_Fetch_to_Decode_enq = f_Fetch_to_Decode$FULL_N ;
  assign WILL_FIRE_fi_Fetch_to_Decode_enq = EN_fi_Fetch_to_Decode_enq ;

  // value method fi_Fetch_to_Decode_notFull
  assign fi_Fetch_to_Decode_notFull = f_Fetch_to_Decode$FULL_N ;
  assign RDY_fi_Fetch_to_Decode_notFull = 1'd1 ;

  // action method fi_IMem_to_Decode_enq
  assign RDY_fi_IMem_to_Decode_enq = !f_IMem_to_Decode_rv$port1__read[265] ;
  assign CAN_FIRE_fi_IMem_to_Decode_enq =
	     !f_IMem_to_Decode_rv$port1__read[265] ;
  assign WILL_FIRE_fi_IMem_to_Decode_enq = EN_fi_IMem_to_Decode_enq ;

  // value method fi_IMem_to_Decode_notFull
  assign fi_IMem_to_Decode_notFull = !f_IMem_to_Decode_rv$port1__read[265] ;
  assign RDY_fi_IMem_to_Decode_notFull = 1'd1 ;

  // value method fo_Decode_to_RR_first
  assign fo_Decode_to_RR_first = f_Decode_to_RR_rv$port1__read[270:0] ;
  assign RDY_fo_Decode_to_RR_first = f_Decode_to_RR_rv$port1__read[271] ;

  // action method fo_Decode_to_RR_deq
  assign RDY_fo_Decode_to_RR_deq = f_Decode_to_RR_rv$port1__read[271] ;
  assign CAN_FIRE_fo_Decode_to_RR_deq = f_Decode_to_RR_rv$port1__read[271] ;
  assign WILL_FIRE_fo_Decode_to_RR_deq = EN_fo_Decode_to_RR_deq ;

  // value method fo_Decode_to_RR_notEmpty
  assign fo_Decode_to_RR_notEmpty = f_Decode_to_RR_rv$port1__read[271] ;
  assign RDY_fo_Decode_to_RR_notEmpty = 1'd1 ;

  // submodule f_Fetch_to_Decode
  SizedFIFO #(.p1width(32'd131),
	      .p2depth(32'd4),
	      .p3cntr_width(32'd2),
	      .guarded(1'd1)) f_Fetch_to_Decode(.RST(RST_N),
						.CLK(CLK),
						.D_IN(f_Fetch_to_Decode$D_IN),
						.ENQ(f_Fetch_to_Decode$ENQ),
						.DEQ(f_Fetch_to_Decode$DEQ),
						.CLR(f_Fetch_to_Decode$CLR),
						.D_OUT(f_Fetch_to_Decode$D_OUT),
						.FULL_N(f_Fetch_to_Decode$FULL_N),
						.EMPTY_N(f_Fetch_to_Decode$EMPTY_N));

  // rule RL_rl_Decode
  assign CAN_FIRE_RL_rl_Decode =
	     f_IMem_to_Decode_rv[265] && f_Fetch_to_Decode$EMPTY_N &&
	     !f_Decode_to_RR_rv[271] &&
	     !f_Fetch_to_Decode$D_OUT[64] ;
  assign WILL_FIRE_RL_rl_Decode = CAN_FIRE_RL_rl_Decode ;

  // rule RL_rl_Decode_halting
  assign CAN_FIRE_RL_rl_Decode_halting =
	     f_Fetch_to_Decode$EMPTY_N && !f_Decode_to_RR_rv[271] &&
	     f_Fetch_to_Decode$D_OUT[64] ;
  assign WILL_FIRE_RL_rl_Decode_halting = CAN_FIRE_RL_rl_Decode_halting ;

  // inputs to muxes for submodule ports
  assign MUX_f_Decode_to_RR_rv$port0__write_1__VAL_1 =
	     { 1'd1,
	       f_Fetch_to_Decode$D_OUT[130:65],
	       1'd0,
	       f_IMem_to_Decode_rv[264:263] == 2'd1 ||
	       f_IMem_to_Decode_rv[264:263] == 2'd2 ||
	       f_IMem_to_Decode_rv[264:263] != 2'd3 &&
	       f_IMem_to_Decode_rv[205:199] != 7'b0110111 &&
	       f_IMem_to_Decode_rv[205:199] != 7'b0010111 &&
	       NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d278,
	       x1_avValue_cause__h2773,
	       x1_avValue_tval__h2774,
	       x1_avValue_fallthru_pc__h2775,
	       f_IMem_to_Decode_rv[230:199],
	       IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d461 } ;
  assign MUX_f_Decode_to_RR_rv$port0__write_1__VAL_2 =
	     { 65'h10000000000000000,
	       f_Fetch_to_Decode$D_OUT[66:65],
	       205'h1000000000000000000000000000000000000000000000000000 } ;

  // inlined wires
  assign f_IMem_to_Decode_rv$port0__write_1 =
	     { 1'd0,
	       265'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign f_IMem_to_Decode_rv$port1__read =
	     CAN_FIRE_RL_rl_Decode ?
	       f_IMem_to_Decode_rv$port0__write_1 :
	       f_IMem_to_Decode_rv ;
  assign f_IMem_to_Decode_rv$port1__write_1 =
	     { 1'd1, fi_IMem_to_Decode_enq_x } ;
  assign f_IMem_to_Decode_rv$port2__read =
	     EN_fi_IMem_to_Decode_enq ?
	       f_IMem_to_Decode_rv$port1__write_1 :
	       f_IMem_to_Decode_rv$port1__read ;
  assign f_Decode_to_RR_rv$EN_port0__write =
	     WILL_FIRE_RL_rl_Decode || WILL_FIRE_RL_rl_Decode_halting ;
  assign f_Decode_to_RR_rv$port0__write_1 =
	     WILL_FIRE_RL_rl_Decode ?
	       MUX_f_Decode_to_RR_rv$port0__write_1__VAL_1 :
	       MUX_f_Decode_to_RR_rv$port0__write_1__VAL_2 ;
  assign f_Decode_to_RR_rv$port1__read =
	     f_Decode_to_RR_rv$EN_port0__write ?
	       f_Decode_to_RR_rv$port0__write_1 :
	       f_Decode_to_RR_rv ;
  assign f_Decode_to_RR_rv$port1__write_1 =
	     { 1'd0,
	       271'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign f_Decode_to_RR_rv$port2__read =
	     EN_fo_Decode_to_RR_deq ?
	       f_Decode_to_RR_rv$port1__write_1 :
	       f_Decode_to_RR_rv$port1__read ;

  // register f_Decode_to_RR_rv
  assign f_Decode_to_RR_rv$D_IN = f_Decode_to_RR_rv$port2__read ;
  assign f_Decode_to_RR_rv$EN = 1'b1 ;

  // register f_IMem_to_Decode_rv
  assign f_IMem_to_Decode_rv$D_IN = f_IMem_to_Decode_rv$port2__read ;
  assign f_IMem_to_Decode_rv$EN = 1'b1 ;

  // register rg_flog
  assign rg_flog$D_IN = init_initial_params[207:176] ;
  assign rg_flog$EN = EN_init ;

  // submodule f_Fetch_to_Decode
  assign f_Fetch_to_Decode$D_IN = fi_Fetch_to_Decode_enq_x ;
  assign f_Fetch_to_Decode$ENQ = EN_fi_Fetch_to_Decode_enq ;
  assign f_Fetch_to_Decode$DEQ =
	     WILL_FIRE_RL_rl_Decode_halting || WILL_FIRE_RL_rl_Decode ;
  assign f_Fetch_to_Decode$CLR = 1'b0 ;

  // remaining internal signals
  assign IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d360 =
	     (f_IMem_to_Decode_rv[205:199] == 7'b0000011 &&
	      (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b010 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b100 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b101) ||
	      f_IMem_to_Decode_rv[205:199] == 7'b0100011 &&
	      (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b010)) ?
	       3'd3 :
	       ((f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d296 ||
		 f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d315) ?
		  3'd2 :
		  (f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d354 ?
		     3'd0 :
		     ((f_IMem_to_Decode_rv[205:199] == 7'b0001111 &&
		       (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
			f_IMem_to_Decode_rv[213:211] == 3'b001)) ?
			3'd5 :
			3'd6))) ;
  assign IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d420 =
	     (f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d296 ||
	      f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d315) ?
	       f_IMem_to_Decode_rv[210:206] != 5'd0 :
	       NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d258 &&
	       ((f_IMem_to_Decode_rv[205:199] == 7'b1110011 &&
		 f_IMem_to_Decode_rv[213:211] != 3'b0 &&
		 f_IMem_to_Decode_rv[213:211] != 3'b100) ?
		  f_IMem_to_Decode_rv[210:206] != 5'd0 :
		  f_IMem_to_Decode_rv[205:199] == 7'b0001011 &&
		  f_IMem_to_Decode_rv[213:211] == 3'b0 &&
		  (f_IMem_to_Decode_rv[230:224] == 7'b0000010 ||
		   f_IMem_to_Decode_rv[230:224] == 7'b0000100 ||
		   f_IMem_to_Decode_rv[230:224] == 7'b0000101) &&
		  f_IMem_to_Decode_rv[210:206] != 5'd0) ;
  assign IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d452 =
	     (f_IMem_to_Decode_rv[205:199] == 7'b0100011 &&
	      (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b010)) ?
	       { {20{x__h4087[11]}}, x__h4087 } :
	       (f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d296 ?
		  SEXT_f_IMem_to_Decode_rv_port0__read_BITS_230__ETC___d448 :
		  32'd0) ;
  assign IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d453 =
	     (f_IMem_to_Decode_rv[205:199] == 7'b1100111 &&
	      f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	      f_IMem_to_Decode_rv[205:199] == 7'b0000011 &&
	      (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b010 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b100 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b101)) ?
	       SEXT_f_IMem_to_Decode_rv_port0__read_BITS_230__ETC___d448 :
	       IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d452 ;
  assign IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d455 =
	     (f_IMem_to_Decode_rv[205:199] == 7'b1100011 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b010 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b011) ?
	       { {19{x__h3889[12]}}, x__h3889 } :
	       ((f_IMem_to_Decode_rv[205:199] == 7'b1101111) ?
		  { {11{x__h3976[20]}}, x__h3976 } :
		  IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d453) ;
  assign IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d461 =
	     { CASE_f_IMem_to_Decode_rv_BITS_205_TO_199_0b101_ETC__q3,
	       f_IMem_to_Decode_rv[264:263] != 2'd1 &&
	       f_IMem_to_Decode_rv[264:263] != 2'd2 &&
	       f_IMem_to_Decode_rv[264:263] != 2'd3 &&
	       f_IMem_to_Decode_rv[205:199] != 7'b0110111 &&
	       f_IMem_to_Decode_rv[205:199] != 7'b0010111 &&
	       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d394,
	       f_IMem_to_Decode_rv[264:263] != 2'd1 &&
	       f_IMem_to_Decode_rv[264:263] != 2'd2 &&
	       f_IMem_to_Decode_rv[264:263] != 2'd3 &&
	       f_IMem_to_Decode_rv[205:199] != 7'b0110111 &&
	       f_IMem_to_Decode_rv[205:199] != 7'b0010111 &&
	       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d406,
	       f_IMem_to_Decode_rv[264:263] != 2'd1 &&
	       f_IMem_to_Decode_rv[264:263] != 2'd2 &&
	       f_IMem_to_Decode_rv[264:263] != 2'd3 &&
	       IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d424,
	       f_IMem_to_Decode_rv[264:263] != 2'd1 &&
	       f_IMem_to_Decode_rv[264:263] != 2'd2 &&
	       f_IMem_to_Decode_rv[264:263] != 2'd3 &&
	       f_IMem_to_Decode_rv[205:199] == 7'b0100011 &&
	       (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
		f_IMem_to_Decode_rv[213:211] == 3'b001 ||
		f_IMem_to_Decode_rv[213:211] == 3'b010),
	       x1_avValue_imm__h2782,
	       f_Fetch_to_Decode$D_OUT[63:0] } ;
  assign NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d202 =
	     f_IMem_to_Decode_rv[205:199] != 7'b0010011 ||
	     ((f_IMem_to_Decode_rv[213:211] == 3'b001) ?
		f_IMem_to_Decode_rv[230:224] != 7'b0 :
		f_IMem_to_Decode_rv[213:211] == 3'b101 &&
		f_IMem_to_Decode_rv[230:224] != 7'b0100000 &&
		f_IMem_to_Decode_rv[230:224] != 7'b0) ;
  assign NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d229 =
	     f_IMem_to_Decode_rv[205:199] != 7'b0110011 ||
	     (f_IMem_to_Decode_rv[213:211] != 3'b0 ||
	      f_IMem_to_Decode_rv[230:224] != 7'b0) &&
	     (f_IMem_to_Decode_rv[213:211] != 3'b0 ||
	      f_IMem_to_Decode_rv[230:224] != 7'b0100000) &&
	     (f_IMem_to_Decode_rv[213:211] != 3'b001 ||
	      f_IMem_to_Decode_rv[230:224] != 7'b0) &&
	     (f_IMem_to_Decode_rv[213:211] != 3'b010 ||
	      f_IMem_to_Decode_rv[230:224] != 7'b0) &&
	     (f_IMem_to_Decode_rv[213:211] != 3'b011 ||
	      f_IMem_to_Decode_rv[230:224] != 7'b0) &&
	     (f_IMem_to_Decode_rv[213:211] != 3'b100 ||
	      f_IMem_to_Decode_rv[230:224] != 7'b0) &&
	     (f_IMem_to_Decode_rv[213:211] != 3'b101 ||
	      f_IMem_to_Decode_rv[230:224] != 7'b0) &&
	     (f_IMem_to_Decode_rv[213:211] != 3'b101 ||
	      f_IMem_to_Decode_rv[230:224] != 7'b0100000) &&
	     (f_IMem_to_Decode_rv[213:211] != 3'b110 ||
	      f_IMem_to_Decode_rv[230:224] != 7'b0) &&
	     (f_IMem_to_Decode_rv[213:211] != 3'b111 ||
	      f_IMem_to_Decode_rv[230:224] != 7'b0) ;
  assign NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d258 =
	     (f_IMem_to_Decode_rv[205:199] != 7'b1110011 ||
	      f_IMem_to_Decode_rv[230:219] != 12'b0 ||
	      f_IMem_to_Decode_rv[218:214] != 5'd0 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0 ||
	      f_IMem_to_Decode_rv[210:206] != 5'd0) &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b1110011 ||
	      f_IMem_to_Decode_rv[230:219] != 12'b000000000001 ||
	      f_IMem_to_Decode_rv[218:214] != 5'd0 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0 ||
	      f_IMem_to_Decode_rv[210:206] != 5'd0) &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b1110011 ||
	      f_IMem_to_Decode_rv[230:219] != 12'b001100000010 ||
	      f_IMem_to_Decode_rv[218:214] != 5'd0 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0 ||
	      f_IMem_to_Decode_rv[210:206] != 5'd0) ;
  assign NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d274 =
	     (f_IMem_to_Decode_rv[205:199] != 7'b0100011 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b001 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b010) &&
	     NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d202 &&
	     NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d229 &&
	     NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d258 &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b1110011 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b100) &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b0001111 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0) &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b0001111 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b001) &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b0001011 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0) ;
  assign NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d278 =
	     (f_IMem_to_Decode_rv[205:199] != 7'b1100011 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b010 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b011) &&
	     f_IMem_to_Decode_rv[205:199] != 7'b1101111 &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b1100111 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0) &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b0000011 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b001 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b010 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b100 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b101) &&
	     NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d274 ;
  assign NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d479 =
	     (f_IMem_to_Decode_rv[205:199] != 7'b0100011 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b001 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b010) &&
	     NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d202 &&
	     NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d229 &&
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d354 ;
  assign NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d516 =
	     (f_IMem_to_Decode_rv[205:199] != 7'b0000011 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b001 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b010 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b100 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b101) &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b0100011 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b001 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b010) &&
	     (f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d296 ||
	      f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d315) ;
  assign NOT_f_IMem_to_Decode_rv_port0__read_BITS_264_T_ETC___d486 =
	     f_IMem_to_Decode_rv[264:263] != 2'd1 &&
	     f_IMem_to_Decode_rv[264:263] != 2'd2 &&
	     (f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d296 ||
	      f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d315 ||
	      f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d330) &&
	     f_IMem_to_Decode_rv[264:263] != 2'd3 &&
	     f_IMem_to_Decode_rv[205:199] != 7'b0110111 &&
	     f_IMem_to_Decode_rv[205:199] != 7'b0010111 &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b1100011 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b010 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b011) &&
	     f_IMem_to_Decode_rv[205:199] != 7'b1101111 &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b1100111 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0) &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b0000011 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b001 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b010 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b100 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b101) &&
	     NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d479 ;
  assign NOT_f_IMem_to_Decode_rv_port0__read_BITS_264_T_ETC___d524 =
	     f_IMem_to_Decode_rv[264:263] != 2'd1 &&
	     f_IMem_to_Decode_rv[264:263] != 2'd2 &&
	     (f_IMem_to_Decode_rv[205:199] == 7'b0110111 ||
	      f_IMem_to_Decode_rv[205:199] == 7'b0010111 ||
	      f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d337) &&
	     (f_IMem_to_Decode_rv[205:199] == 7'b0110111 ||
	      f_IMem_to_Decode_rv[205:199] == 7'b0010111 ||
	      f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d503) &&
	     f_IMem_to_Decode_rv[264:263] != 2'd3 &&
	     (f_IMem_to_Decode_rv[205:199] == 7'b0110111 ||
	      f_IMem_to_Decode_rv[205:199] == 7'b0010111 ||
	      (f_IMem_to_Decode_rv[205:199] != 7'b1100011 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b010 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b011) &&
	      f_IMem_to_Decode_rv[205:199] != 7'b1101111 &&
	      (f_IMem_to_Decode_rv[205:199] != 7'b1100111 ||
	       f_IMem_to_Decode_rv[213:211] != 3'b0) &&
	      NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d516) ;
  assign NOT_f_IMem_to_Decode_rv_port0__read_BITS_264_T_ETC___d549 =
	     f_IMem_to_Decode_rv[264:263] != 2'd1 &&
	     f_IMem_to_Decode_rv[264:263] != 2'd2 &&
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d334 &&
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d500 &&
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d541 &&
	     f_IMem_to_Decode_rv[264:263] != 2'd3 &&
	     (f_IMem_to_Decode_rv[205:199] == 7'b0000011 &&
	      (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b010 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b100 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b101) ||
	      f_IMem_to_Decode_rv[205:199] == 7'b0100011 &&
	      (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b010)) ;
  assign NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472 =
	     rg_flog != 32'd0 && f_IMem_to_Decode_rv[264:263] != 2'd1 &&
	     f_IMem_to_Decode_rv[264:263] != 2'd2 &&
	     (f_IMem_to_Decode_rv[264:263] == 2'd3 ||
	      f_IMem_to_Decode_rv[205:199] == 7'b0110111 ||
	      f_IMem_to_Decode_rv[205:199] == 7'b0010111 ||
	      f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d337) ;
  assign NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d508 =
	     rg_flog != 32'd0 && f_IMem_to_Decode_rv[264:263] != 2'd1 &&
	     f_IMem_to_Decode_rv[264:263] != 2'd2 &&
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d337 &&
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d503 &&
	     f_IMem_to_Decode_rv[264:263] != 2'd3 &&
	     (f_IMem_to_Decode_rv[205:199] == 7'b1100011 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b010 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b011 ||
	      f_IMem_to_Decode_rv[205:199] == 7'b1101111 ||
	      f_IMem_to_Decode_rv[205:199] == 7'b1100111 &&
	      f_IMem_to_Decode_rv[213:211] == 3'b0) ;
  assign NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469 =
	     rg_flog != 32'd0 &&
	     (f_IMem_to_Decode_rv[264:263] == 2'd1 ||
	      f_IMem_to_Decode_rv[264:263] == 2'd2 ||
	      f_IMem_to_Decode_rv[264:263] != 2'd3 &&
	      f_IMem_to_Decode_rv[205:199] != 7'b0110111 &&
	      f_IMem_to_Decode_rv[205:199] != 7'b0010111 &&
	      NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d278) ;
  assign SEXT_f_IMem_to_Decode_rv_port0__read_BITS_230__ETC___d448 =
	     { {20{f_IMem_to_Decode_rv_BITS_230_TO_219__q1[11]}},
	       f_IMem_to_Decode_rv_BITS_230_TO_219__q1 } ;
  assign f_IMem_to_Decode_rv_BITS_230_TO_219__q1 =
	     f_IMem_to_Decode_rv[230:219] ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d296 =
	     f_IMem_to_Decode_rv[205:199] == 7'b0010011 &&
	     ((f_IMem_to_Decode_rv[213:211] == 3'b001) ?
		f_IMem_to_Decode_rv[230:224] == 7'b0 :
		f_IMem_to_Decode_rv[213:211] != 3'b101 ||
		f_IMem_to_Decode_rv[230:224] == 7'b0100000 ||
		f_IMem_to_Decode_rv[230:224] == 7'b0) ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d315 =
	     f_IMem_to_Decode_rv[205:199] == 7'b0110011 &&
	     (f_IMem_to_Decode_rv[213:211] == 3'b0 &&
	      (f_IMem_to_Decode_rv[230:224] == 7'b0 ||
	       f_IMem_to_Decode_rv[230:224] == 7'b0100000) ||
	      (f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b010 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b011 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b100 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b101) &&
	      f_IMem_to_Decode_rv[230:224] == 7'b0 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b101 &&
	      f_IMem_to_Decode_rv[230:224] == 7'b0100000 ||
	      (f_IMem_to_Decode_rv[213:211] == 3'b110 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b111) &&
	      f_IMem_to_Decode_rv[230:224] == 7'b0) ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d319 =
	     f_IMem_to_Decode_rv[205:199] == 7'b1110011 &&
	     (f_IMem_to_Decode_rv[230:219] == 12'b0 ||
	      f_IMem_to_Decode_rv[230:219] == 12'b000000000001 ||
	      f_IMem_to_Decode_rv[230:219] == 12'b001100000010) &&
	     f_IMem_to_Decode_rv[218:214] == 5'd0 ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d330 =
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d319 &&
	     f_IMem_to_Decode_rv[213:211] == 3'b0 &&
	     f_IMem_to_Decode_rv[210:206] == 5'd0 ||
	     f_IMem_to_Decode_rv[205:199] == 7'b1110011 &&
	     f_IMem_to_Decode_rv[213:211] != 3'b0 &&
	     f_IMem_to_Decode_rv[213:211] != 3'b100 ||
	     f_IMem_to_Decode_rv[205:199] == 7'b0001111 &&
	     f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	     f_IMem_to_Decode_rv[205:199] == 7'b0001111 &&
	     f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	     f_IMem_to_Decode_rv[205:199] == 7'b0001011 &&
	     f_IMem_to_Decode_rv[213:211] == 3'b0 ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d333 =
	     f_IMem_to_Decode_rv[205:199] == 7'b0100011 &&
	     (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b010) ||
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d296 ||
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d315 ||
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d330 ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d334 =
	     f_IMem_to_Decode_rv[205:199] == 7'b0000011 &&
	     (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b010 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b100 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b101) ||
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d333 ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d337 =
	     f_IMem_to_Decode_rv[205:199] == 7'b1100011 &&
	     f_IMem_to_Decode_rv[213:211] != 3'b010 &&
	     f_IMem_to_Decode_rv[213:211] != 3'b011 ||
	     f_IMem_to_Decode_rv[205:199] == 7'b1101111 ||
	     f_IMem_to_Decode_rv[205:199] == 7'b1100111 &&
	     f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d334 ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d354 =
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d319 &&
	     f_IMem_to_Decode_rv[213:211] == 3'b0 &&
	     f_IMem_to_Decode_rv[210:206] == 5'd0 ||
	     f_IMem_to_Decode_rv[205:199] == 7'b1110011 &&
	     f_IMem_to_Decode_rv[213:211] != 3'b0 &&
	     f_IMem_to_Decode_rv[213:211] != 3'b100 ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d389 =
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d296 ||
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d315 ||
	     NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d258 &&
	     ((f_IMem_to_Decode_rv[205:199] == 7'b1110011 &&
	       f_IMem_to_Decode_rv[213:211] != 3'b0 &&
	       f_IMem_to_Decode_rv[213:211] != 3'b100) ?
		!f_IMem_to_Decode_rv[213] :
		f_IMem_to_Decode_rv[205:199] == 7'b0001011 &&
		f_IMem_to_Decode_rv[213:211] == 3'b0 &&
		(f_IMem_to_Decode_rv[230:224] == 7'b0 ||
		 f_IMem_to_Decode_rv[230:224] == 7'b0000001 ||
		 f_IMem_to_Decode_rv[230:224] == 7'b0000100 ||
		 f_IMem_to_Decode_rv[230:224] == 7'b0000101)) ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d394 =
	     f_IMem_to_Decode_rv[205:199] == 7'b1100011 &&
	     f_IMem_to_Decode_rv[213:211] != 3'b010 &&
	     f_IMem_to_Decode_rv[213:211] != 3'b011 ||
	     f_IMem_to_Decode_rv[205:199] != 7'b1101111 &&
	     (f_IMem_to_Decode_rv[205:199] == 7'b1100111 &&
	      f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	      f_IMem_to_Decode_rv[205:199] == 7'b0000011 &&
	      (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b010 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b100 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b101) ||
	      f_IMem_to_Decode_rv[205:199] == 7'b0100011 &&
	      (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b010) ||
	      f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d389) ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d402 =
	     f_IMem_to_Decode_rv[205:199] == 7'b0100011 &&
	     (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b010) ||
	     NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d202 &&
	     (f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d315 ||
	      f_IMem_to_Decode_rv[205:199] == 7'b0001011 &&
	      f_IMem_to_Decode_rv[213:211] == 3'b0 &&
	      (f_IMem_to_Decode_rv[230:224] == 7'b0 ||
	       f_IMem_to_Decode_rv[230:224] == 7'b0000001)) ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d406 =
	     f_IMem_to_Decode_rv[205:199] == 7'b1100011 &&
	     f_IMem_to_Decode_rv[213:211] != 3'b010 &&
	     f_IMem_to_Decode_rv[213:211] != 3'b011 ||
	     f_IMem_to_Decode_rv[205:199] != 7'b1101111 &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b1100111 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0) &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b0000011 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b001 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b010 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b100 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b101) &&
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d402 ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d499 =
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d296 ||
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d315 ||
	     (f_IMem_to_Decode_rv[205:199] != 7'b1110011 ||
	      f_IMem_to_Decode_rv[230:219] != 12'b0 &&
	      f_IMem_to_Decode_rv[230:219] != 12'b000000000001 &&
	      f_IMem_to_Decode_rv[230:219] != 12'b001100000010 ||
	      f_IMem_to_Decode_rv[218:214] != 5'd0 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0 ||
	      f_IMem_to_Decode_rv[210:206] != 5'd0) &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b1110011 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b100) ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d500 =
	     f_IMem_to_Decode_rv[205:199] == 7'b0000011 &&
	     (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b010 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b100 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b101) ||
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d499 ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d503 =
	     f_IMem_to_Decode_rv[205:199] == 7'b1100011 &&
	     f_IMem_to_Decode_rv[213:211] != 3'b010 &&
	     f_IMem_to_Decode_rv[213:211] != 3'b011 ||
	     f_IMem_to_Decode_rv[205:199] == 7'b1101111 ||
	     f_IMem_to_Decode_rv[205:199] == 7'b1100111 &&
	     f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	     f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d500 ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d541 =
	     f_IMem_to_Decode_rv[205:199] == 7'b0000011 &&
	     (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b010 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b100 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b101) ||
	     f_IMem_to_Decode_rv[205:199] == 7'b0100011 &&
	     (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b001 ||
	      f_IMem_to_Decode_rv[213:211] == 3'b010) ||
	     NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d202 &&
	     (f_IMem_to_Decode_rv[205:199] != 7'b0110011 ||
	      (f_IMem_to_Decode_rv[213:211] != 3'b0 ||
	       f_IMem_to_Decode_rv[230:224] != 7'b0 &&
	       f_IMem_to_Decode_rv[230:224] != 7'b0100000) &&
	      (f_IMem_to_Decode_rv[213:211] != 3'b001 ||
	       f_IMem_to_Decode_rv[230:224] != 7'b0) &&
	      (f_IMem_to_Decode_rv[213:211] != 3'b010 ||
	       f_IMem_to_Decode_rv[230:224] != 7'b0) &&
	      (f_IMem_to_Decode_rv[213:211] != 3'b011 ||
	       f_IMem_to_Decode_rv[230:224] != 7'b0) &&
	      (f_IMem_to_Decode_rv[213:211] != 3'b100 ||
	       f_IMem_to_Decode_rv[230:224] != 7'b0) &&
	      (f_IMem_to_Decode_rv[213:211] != 3'b101 ||
	       f_IMem_to_Decode_rv[230:224] != 7'b0) &&
	      (f_IMem_to_Decode_rv[213:211] != 3'b101 ||
	       f_IMem_to_Decode_rv[230:224] != 7'b0100000) &&
	      (f_IMem_to_Decode_rv[213:211] != 3'b110 ||
	       f_IMem_to_Decode_rv[230:224] != 7'b0) &&
	      (f_IMem_to_Decode_rv[213:211] != 3'b111 ||
	       f_IMem_to_Decode_rv[230:224] != 7'b0)) ;
  assign f_IMem_to_Decode_rv_port0__read_BITS_264_TO_26_ETC___d573 =
	     (f_IMem_to_Decode_rv[264:263] == 2'd3 ||
	      f_IMem_to_Decode_rv[205:199] == 7'b0110111 ||
	      f_IMem_to_Decode_rv[205:199] == 7'b0010111 ||
	      f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d503) &&
	     (f_IMem_to_Decode_rv[264:263] == 2'd3 ||
	      (f_IMem_to_Decode_rv[205:199] != 7'b1100011 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b010 ||
	       f_IMem_to_Decode_rv[213:211] == 3'b011) &&
	      f_IMem_to_Decode_rv[205:199] != 7'b1101111 &&
	      (f_IMem_to_Decode_rv[205:199] != 7'b1100111 ||
	       f_IMem_to_Decode_rv[213:211] != 3'b0)) &&
	     (f_IMem_to_Decode_rv[264:263] == 2'd3 ||
	      f_IMem_to_Decode_rv[205:199] != 7'b0110111 &&
	      f_IMem_to_Decode_rv[205:199] != 7'b0010111 &&
	      (f_IMem_to_Decode_rv[205:199] == 7'b1100011 &&
	       f_IMem_to_Decode_rv[213:211] != 3'b010 &&
	       f_IMem_to_Decode_rv[213:211] != 3'b011 ||
	       f_IMem_to_Decode_rv[205:199] == 7'b1101111 ||
	       f_IMem_to_Decode_rv[205:199] == 7'b1100111 &&
	       f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	       f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d541)) &&
	     (f_IMem_to_Decode_rv[264:263] == 2'd3 ||
	      (f_IMem_to_Decode_rv[205:199] != 7'b0000011 ||
	       f_IMem_to_Decode_rv[213:211] != 3'b0 &&
	       f_IMem_to_Decode_rv[213:211] != 3'b001 &&
	       f_IMem_to_Decode_rv[213:211] != 3'b010 &&
	       f_IMem_to_Decode_rv[213:211] != 3'b100 &&
	       f_IMem_to_Decode_rv[213:211] != 3'b101) &&
	      (f_IMem_to_Decode_rv[205:199] != 7'b0100011 ||
	       f_IMem_to_Decode_rv[213:211] != 3'b0 &&
	       f_IMem_to_Decode_rv[213:211] != 3'b001 &&
	       f_IMem_to_Decode_rv[213:211] != 3'b010)) &&
	     (f_IMem_to_Decode_rv[264:263] == 2'd3 ||
	      f_IMem_to_Decode_rv[205:199] != 7'b0001111 ||
	      f_IMem_to_Decode_rv[213:211] != 3'b0 &&
	      f_IMem_to_Decode_rv[213:211] != 3'b001) ;
  assign x1_avValue_fallthru_pc__h2775 =
	     f_Fetch_to_Decode$D_OUT[130:99] + 32'd4 ;
  assign x1_avValue_tval__h2724 =
	     (f_IMem_to_Decode_rv[264:263] == 2'd3 ||
	      f_IMem_to_Decode_rv[205:199] == 7'b0110111 ||
	      f_IMem_to_Decode_rv[205:199] == 7'b0010111 ||
	      f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d337) ?
	       32'd0 :
	       f_IMem_to_Decode_rv[230:199] ;
  assign x__h3889 =
	     { f_IMem_to_Decode_rv[230],
	       f_IMem_to_Decode_rv[206],
	       f_IMem_to_Decode_rv[229:224],
	       f_IMem_to_Decode_rv[210:207],
	       1'b0 } ;
  assign x__h3976 =
	     { f_IMem_to_Decode_rv[230],
	       f_IMem_to_Decode_rv[218:211],
	       f_IMem_to_Decode_rv[219],
	       f_IMem_to_Decode_rv[229:220],
	       1'b0 } ;
  assign x__h4087 =
	     { f_IMem_to_Decode_rv[230:224], f_IMem_to_Decode_rv[210:206] } ;
  always@(f_IMem_to_Decode_rv)
  begin
    case (f_IMem_to_Decode_rv[264:263])
      2'd1: x1_avValue_cause__h2773 = 4'd0;
      2'd2: x1_avValue_cause__h2773 = 4'd1;
      default: x1_avValue_cause__h2773 = 4'd2;
    endcase
  end
  always@(f_IMem_to_Decode_rv or x1_avValue_tval__h2724)
  begin
    case (f_IMem_to_Decode_rv[264:263])
      2'd1, 2'd2: x1_avValue_tval__h2774 = f_IMem_to_Decode_rv[159:128];
      default: x1_avValue_tval__h2774 = x1_avValue_tval__h2724;
    endcase
  end
  always@(f_IMem_to_Decode_rv or
	  IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d420)
  begin
    case (f_IMem_to_Decode_rv[205:199])
      7'b0010111, 7'b0110111:
	  IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d424 =
	      f_IMem_to_Decode_rv[210:206] != 5'd0;
      default: IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d424 =
		   (f_IMem_to_Decode_rv[205:199] != 7'b1100011 ||
		    f_IMem_to_Decode_rv[213:211] == 3'b010 ||
		    f_IMem_to_Decode_rv[213:211] == 3'b011) &&
		   ((f_IMem_to_Decode_rv[205:199] == 7'b1101111 ||
		     f_IMem_to_Decode_rv[205:199] == 7'b1100111 &&
		     f_IMem_to_Decode_rv[213:211] == 3'b0 ||
		     f_IMem_to_Decode_rv[205:199] == 7'b0000011 &&
		     (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
		      f_IMem_to_Decode_rv[213:211] == 3'b001 ||
		      f_IMem_to_Decode_rv[213:211] == 3'b010 ||
		      f_IMem_to_Decode_rv[213:211] == 3'b100 ||
		      f_IMem_to_Decode_rv[213:211] == 3'b101)) ?
		      f_IMem_to_Decode_rv[210:206] != 5'd0 :
		      (f_IMem_to_Decode_rv[205:199] != 7'b0100011 ||
		       f_IMem_to_Decode_rv[213:211] != 3'b0 &&
		       f_IMem_to_Decode_rv[213:211] != 3'b001 &&
		       f_IMem_to_Decode_rv[213:211] != 3'b010) &&
		      IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d420);
    endcase
  end
  always@(f_IMem_to_Decode_rv or
	  IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d455)
  begin
    case (f_IMem_to_Decode_rv[205:199])
      7'b0010111, 7'b0110111:
	  CASE_f_IMem_to_Decode_rv_BITS_205_TO_199_0b101_ETC__q2 =
	      { f_IMem_to_Decode_rv[230:211], 12'h0 };
      default: CASE_f_IMem_to_Decode_rv_BITS_205_TO_199_0b101_ETC__q2 =
		   IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d455;
    endcase
  end
  always@(f_IMem_to_Decode_rv or
	  CASE_f_IMem_to_Decode_rv_BITS_205_TO_199_0b101_ETC__q2)
  begin
    case (f_IMem_to_Decode_rv[264:263])
      2'd0:
	  x1_avValue_imm__h2782 =
	      CASE_f_IMem_to_Decode_rv_BITS_205_TO_199_0b101_ETC__q2;
      2'd1, 2'd2, 2'd3: x1_avValue_imm__h2782 = 32'd0;
    endcase
  end
  always@(f_IMem_to_Decode_rv or
	  IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d360)
  begin
    case (f_IMem_to_Decode_rv[205:199])
      7'b0010111, 7'b0110111:
	  CASE_f_IMem_to_Decode_rv_BITS_205_TO_199_0b101_ETC__q3 = 3'd2;
      default: CASE_f_IMem_to_Decode_rv_BITS_205_TO_199_0b101_ETC__q3 =
		   (f_IMem_to_Decode_rv[205:199] == 7'b1100011 &&
		    f_IMem_to_Decode_rv[213:211] != 3'b010 &&
		    f_IMem_to_Decode_rv[213:211] != 3'b011 ||
		    f_IMem_to_Decode_rv[205:199] == 7'b1101111 ||
		    f_IMem_to_Decode_rv[205:199] == 7'b1100111 &&
		    f_IMem_to_Decode_rv[213:211] == 3'b0) ?
		     3'd1 :
		     IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d360;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        f_Decode_to_RR_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0,
	      271'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
	f_IMem_to_Decode_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0,
	      265'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
	rg_flog <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (f_Decode_to_RR_rv$EN)
	  f_Decode_to_RR_rv <= `BSV_ASSIGNMENT_DELAY f_Decode_to_RR_rv$D_IN;
	if (f_IMem_to_Decode_rv$EN)
	  f_IMem_to_Decode_rv <= `BSV_ASSIGNMENT_DELAY
	      f_IMem_to_Decode_rv$D_IN;
	if (rg_flog$EN) rg_flog <= `BSV_ASSIGNMENT_DELAY rg_flog$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    f_Decode_to_RR_rv =
	272'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    f_IMem_to_Decode_rv =
	266'h2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    rg_flog = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0)
	begin
	  v__h968 = $stime;
	  #0;
	end
    x__h1001 = v__h968 + 32'd5;
    v__h960 = x__h1001 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h960);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "fn_D: IMPOSSIBLE: IMem response is DEFERRED\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "    Mem_Rsp {");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "MEM_REQ_DEFERRED");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, " addr:%08h", f_IMem_to_Decode_rv[191:128]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, " rdata:%08h", f_IMem_to_Decode_rv[262:199]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog,
		" I_%0d pc:%08h instr:%08h ",
		f_IMem_to_Decode_rv[127:64],
		f_IMem_to_Decode_rv[63:32],
		f_IMem_to_Decode_rv[31:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b00110)
	$fwrite(rg_flog, "FETCH");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11110)
	$fwrite(rg_flog, "LOAD");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11111)
	$fwrite(rg_flog, "STORE");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11101)
	$fwrite(rg_flog, "FENCE");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11001)
	$fwrite(rg_flog, "FENCE.I");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b00010)
	$fwrite(rg_flog, "LR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b00011)
	$fwrite(rg_flog, "SC");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b00001)
	$fwrite(rg_flog, "AMOSWAP");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b0)
	$fwrite(rg_flog, "AMOADD");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b00100)
	$fwrite(rg_flog, "AMOXOR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b01100)
	$fwrite(rg_flog, "AMOAND");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b01000)
	$fwrite(rg_flog, "AMOOR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b10000)
	$fwrite(rg_flog, "AMOMIN");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b10100)
	$fwrite(rg_flog, "AMOMAX");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11000)
	$fwrite(rg_flog, "AMOMINU");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11100)
	$fwrite(rg_flog, "AMOMAXU");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b00110 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11110 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11111 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11101 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11001 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b00010 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b00011 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b00001 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b0 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b00100 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b01100 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b01000 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b10000 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b10100 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11000 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11100)
	$fwrite(rg_flog,
		"<unknown Mem_Req_Type %0h",
		f_IMem_to_Decode_rv[198:194]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, " ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[193:192] == 2'd0)
	$fwrite(rg_flog, "1B");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[193:192] == 2'd1)
	$fwrite(rg_flog, "2B");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[193:192] == 2'd2)
	$fwrite(rg_flog, "4B");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[193:192] != 2'd0 &&
	  f_IMem_to_Decode_rv[193:192] != 2'd1 &&
	  f_IMem_to_Decode_rv[193:192] != 2'd2)
	$fwrite(rg_flog, "8B");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "}");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3)
	begin
	  v__h1417 = $stime;
	  #0;
	end
    x__h1450 = v__h1417 + 32'd5;
    v__h1409 = x__h1450 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3)
	$write("%0d: ", v__h1409);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3)
	$write("fn_D: IMPOSSIBLE: IMem response is DEFERRED\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3)
	$write("    Mem_Rsp {");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3)
	$write("MEM_REQ_DEFERRED");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3)
	$write(" addr:%08h", f_IMem_to_Decode_rv[191:128]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3)
	$write(" rdata:%08h", f_IMem_to_Decode_rv[262:199]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3)
	$write(" I_%0d pc:%08h instr:%08h ",
	       f_IMem_to_Decode_rv[127:64],
	       f_IMem_to_Decode_rv[63:32],
	       f_IMem_to_Decode_rv[31:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b00110)
	$write("FETCH");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11110)
	$write("LOAD");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11111)
	$write("STORE");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11101)
	$write("FENCE");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11001)
	$write("FENCE.I");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b00010)
	$write("LR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b00011)
	$write("SC");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b00001)
	$write("AMOSWAP");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b0)
	$write("AMOADD");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b00100)
	$write("AMOXOR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b01100)
	$write("AMOAND");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b01000)
	$write("AMOOR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b10000)
	$write("AMOMIN");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b10100)
	$write("AMOMAX");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11000)
	$write("AMOMINU");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11100)
	$write("AMOMAXU");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b00110 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11110 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11111 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11101 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11001 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b00010 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b00011 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b00001 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b0 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b00100 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b01100 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b01000 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b10000 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b10100 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11000 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11100)
	$write("<unknown Mem_Req_Type %0h", f_IMem_to_Decode_rv[198:194]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3)
	$write(" ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[193:192] == 2'd0)
	$write("1B");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[193:192] == 2'd1)
	$write("2B");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[193:192] == 2'd2)
	$write("4B");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3 &&
	  f_IMem_to_Decode_rv[193:192] != 2'd0 &&
	  f_IMem_to_Decode_rv[193:192] != 2'd1 &&
	  f_IMem_to_Decode_rv[193:192] != 2'd2)
	$write("8B");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3)
	$write("}");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && f_IMem_to_Decode_rv[264:263] == 2'd3)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0)
	begin
	  v__h4246 = $stime;
	  #0;
	end
    x__h4279 = v__h4246 + 32'd5;
    v__h4238 = x__h4279 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h4238);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0)
	$fwrite(rg_flog, "CPU.Decode:\n    ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469)
	$fwrite(rg_flog,
		"    Decode_to_RR{",
		"I_%0d",
		f_Fetch_to_Decode$D_OUT[63:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472)
	$fwrite(rg_flog,
		"    Decode_to_RR{",
		"I_%0d",
		f_Fetch_to_Decode$D_OUT[63:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472)
	$fwrite(rg_flog, " pc:%08h", f_Fetch_to_Decode$D_OUT[130:99]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472)
	$fwrite(rg_flog, " instr:%08h", f_IMem_to_Decode_rv[230:199]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472)
	$fwrite(rg_flog,
		" pred:%08h epoch:%0d\n",
		f_Fetch_to_Decode$D_OUT[98:67],
		f_Fetch_to_Decode$D_OUT[66:65]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472)
	$fwrite(rg_flog, "            ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472)
	$fwrite(rg_flog, "fallthru:%08h ", x1_avValue_fallthru_pc__h2775);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  NOT_f_IMem_to_Decode_rv_port0__read_BITS_264_T_ETC___d486)
	$fwrite(rg_flog, "OPCLASS_SYSTEM");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d508)
	$fwrite(rg_flog, "OPCLASS_CONTROL");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  NOT_f_IMem_to_Decode_rv_port0__read_BITS_264_T_ETC___d524)
	$fwrite(rg_flog, "OPCLASS_INT");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  NOT_f_IMem_to_Decode_rv_port0__read_BITS_264_T_ETC___d549)
	$fwrite(rg_flog, "OPCLASS_MEM");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[264:263] != 2'd1 &&
	  f_IMem_to_Decode_rv[264:263] != 2'd2 &&
	  f_IMem_to_Decode_rv[264:263] != 2'd3 &&
	  f_IMem_to_Decode_rv[205:199] == 7'b0001111 &&
	  (f_IMem_to_Decode_rv[213:211] == 3'b0 ||
	   f_IMem_to_Decode_rv[213:211] == 3'b001))
	$fwrite(rg_flog, "OPCLASS_FENCE");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[264:263] != 2'd1 &&
	  f_IMem_to_Decode_rv[264:263] != 2'd2 &&
	  (f_IMem_to_Decode_rv[264:263] == 2'd3 ||
	   f_IMem_to_Decode_rv[205:199] == 7'b0110111 ||
	   f_IMem_to_Decode_rv[205:199] == 7'b0010111 ||
	   f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d337) &&
	  f_IMem_to_Decode_rv_port0__read_BITS_264_TO_26_ETC___d573)
	$fwrite(rg_flog, "OPCLASS_POSIT");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472)
	$fwrite(rg_flog,
		" has_{rs1,rs2,rd}:{%0d,%0d,%0d} writes_mem:%0d, imm:%0h",
		f_IMem_to_Decode_rv[264:263] != 2'd1 &&
		f_IMem_to_Decode_rv[264:263] != 2'd2 &&
		f_IMem_to_Decode_rv[264:263] != 2'd3 &&
		f_IMem_to_Decode_rv[205:199] != 7'b0110111 &&
		f_IMem_to_Decode_rv[205:199] != 7'b0010111 &&
		f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d394,
		f_IMem_to_Decode_rv[264:263] != 2'd1 &&
		f_IMem_to_Decode_rv[264:263] != 2'd2 &&
		f_IMem_to_Decode_rv[264:263] != 2'd3 &&
		f_IMem_to_Decode_rv[205:199] != 7'b0110111 &&
		f_IMem_to_Decode_rv[205:199] != 7'b0010111 &&
		f_IMem_to_Decode_rv_port0__read_BITS_205_TO_19_ETC___d406,
		f_IMem_to_Decode_rv[264:263] != 2'd1 &&
		f_IMem_to_Decode_rv[264:263] != 2'd2 &&
		f_IMem_to_Decode_rv[264:263] != 2'd3 &&
		IF_f_IMem_to_Decode_rv_port0__read_BITS_205_TO_ETC___d424,
		f_IMem_to_Decode_rv[264:263] != 2'd1 &&
		f_IMem_to_Decode_rv[264:263] != 2'd2 &&
		f_IMem_to_Decode_rv[264:263] != 2'd3 &&
		f_IMem_to_Decode_rv[205:199] == 7'b0100011 &&
		(f_IMem_to_Decode_rv[213:211] == 3'b0 ||
		 f_IMem_to_Decode_rv[213:211] == 3'b001 ||
		 f_IMem_to_Decode_rv[213:211] == 3'b010),
		x1_avValue_imm__h2782);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469)
	$fwrite(rg_flog, " pc:%08h", f_Fetch_to_Decode$D_OUT[130:99]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469)
	$fwrite(rg_flog, " instr:%08h", f_IMem_to_Decode_rv[230:199]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469)
	$fwrite(rg_flog,
		" pred:%08h epoch:%0d\n",
		f_Fetch_to_Decode$D_OUT[98:67],
		f_Fetch_to_Decode$D_OUT[66:65]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469)
	$fwrite(rg_flog, "            ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469)
	$fwrite(rg_flog, "fallthru:%08h ", x1_avValue_fallthru_pc__h2775);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[264:263] == 2'd1)
	$fwrite(rg_flog, "INSTR_ADDR_MISALIGNED");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[264:263] == 2'd2)
	$fwrite(rg_flog, "INSTR_ACCESS_FAULT");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[264:263] != 2'd3 &&
	  f_IMem_to_Decode_rv[205:199] != 7'b0110111 &&
	  f_IMem_to_Decode_rv[205:199] != 7'b0010111 &&
	  NOT_f_IMem_to_Decode_rv_port0__read_BITS_205_T_ETC___d278 &&
	  f_IMem_to_Decode_rv[264:263] != 2'd1 &&
	  f_IMem_to_Decode_rv[264:263] != 2'd2)
	$fwrite(rg_flog, "ILLEGAL_INSTR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_f_IMem_to_Decode_rv_ETC___d469)
	$fwrite(rg_flog, " tval:%0h", x1_avValue_tval__h2774);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode &&
	  NOT_rg_flog_6_EQ_0_7_8_AND_NOT_f_IMem_to_Decod_ETC___d472)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0)
	$fwrite(rg_flog, " halt_sentinel:%0d}", 1'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0)
	$fwrite(rg_flog, "\n    ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0)
	$fwrite(rg_flog, "    Mem_Rsp {");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[264:263] == 2'd0)
	$fwrite(rg_flog, "MEM_RSP_OK");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[264:263] == 2'd1)
	$fwrite(rg_flog, "MEM_RSP_MISALIGNED");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[264:263] == 2'd2)
	$fwrite(rg_flog, "MEM_RSP_ERR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[264:263] != 2'd0 &&
	  f_IMem_to_Decode_rv[264:263] != 2'd1 &&
	  f_IMem_to_Decode_rv[264:263] != 2'd2)
	$fwrite(rg_flog, "MEM_REQ_DEFERRED");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0)
	$fwrite(rg_flog, " addr:%08h", f_IMem_to_Decode_rv[191:128]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0)
	$fwrite(rg_flog, " rdata:%08h", f_IMem_to_Decode_rv[262:199]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0)
	$fwrite(rg_flog,
		" I_%0d pc:%08h instr:%08h ",
		f_IMem_to_Decode_rv[127:64],
		f_IMem_to_Decode_rv[63:32],
		f_IMem_to_Decode_rv[31:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b00110)
	$fwrite(rg_flog, "FETCH");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11110)
	$fwrite(rg_flog, "LOAD");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11111)
	$fwrite(rg_flog, "STORE");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11101)
	$fwrite(rg_flog, "FENCE");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11001)
	$fwrite(rg_flog, "FENCE.I");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b00010)
	$fwrite(rg_flog, "LR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b00011)
	$fwrite(rg_flog, "SC");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b00001)
	$fwrite(rg_flog, "AMOSWAP");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b0)
	$fwrite(rg_flog, "AMOADD");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b00100)
	$fwrite(rg_flog, "AMOXOR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b01100)
	$fwrite(rg_flog, "AMOAND");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b01000)
	$fwrite(rg_flog, "AMOOR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b10000)
	$fwrite(rg_flog, "AMOMIN");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b10100)
	$fwrite(rg_flog, "AMOMAX");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11000)
	$fwrite(rg_flog, "AMOMINU");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] == 5'b11100)
	$fwrite(rg_flog, "AMOMAXU");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b00110 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11110 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11111 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11101 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11001 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b00010 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b00011 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b00001 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b0 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b00100 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b01100 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b01000 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b10000 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b10100 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11000 &&
	  f_IMem_to_Decode_rv[198:194] != 5'b11100)
	$fwrite(rg_flog,
		"<unknown Mem_Req_Type %0h",
		f_IMem_to_Decode_rv[198:194]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0) $fwrite(rg_flog, " ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[193:192] == 2'd0)
	$fwrite(rg_flog, "1B");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[193:192] == 2'd1)
	$fwrite(rg_flog, "2B");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[193:192] == 2'd2)
	$fwrite(rg_flog, "4B");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0 &&
	  f_IMem_to_Decode_rv[193:192] != 2'd0 &&
	  f_IMem_to_Decode_rv[193:192] != 2'd1 &&
	  f_IMem_to_Decode_rv[193:192] != 2'd2)
	$fwrite(rg_flog, "8B");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0) $fwrite(rg_flog, "}");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0) $fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0)
	begin
	  v__h4811 = $stime;
	  #0;
	end
    x__h4844 = v__h4811 + 32'd5;
    v__h4803 = x__h4844 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0)
	$fwrite(rg_flog,
		"Trace %0d %0d %08h %08h %s",
		v__h4803,
		f_Fetch_to_Decode$D_OUT[63:0],
		f_Fetch_to_Decode$D_OUT[130:99],
		f_IMem_to_Decode_rv[230:199],
		"D");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0) $fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode && rg_flog != 32'd0) $fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	begin
	  v__h5150 = $stime;
	  #0;
	end
    x__h5183 = v__h5150 + 32'd5;
    v__h5142 = x__h5183 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h5142);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, "CPU.Decode:\n    ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, "    Decode_to_RR{", "I_%0d", 64'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, " pc:%08h", 32'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, " instr:%08h", 32'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog,
		" pred:%08h epoch:%0d\n",
		32'd0,
		f_Fetch_to_Decode$D_OUT[66:65]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, "            ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, "fallthru:%08h ", 32'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, "OPCLASS_SYSTEM");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog,
		" has_{rs1,rs2,rd}:{%0d,%0d,%0d} writes_mem:%0d, imm:%0h",
		1'd0,
		1'd0,
		1'd0,
		1'd0,
		32'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, " halt_sentinel:%0d}", 1'd1);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, "\n    ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, "    Mem_Rsp {", "MEM_RSP_OK");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, " addr:%08h", 64'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, " rdata:%08h", 64'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, " I_%0d pc:%08h instr:%08h ", 64'd0, 32'd0, 32'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, "AMOADD");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, " ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, "1B");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, "}");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	begin
	  v__h5502 = $stime;
	  #0;
	end
    x__h5535 = v__h5502 + 32'd5;
    v__h5494 = x__h5535 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog,
		"Trace %0d %0d %08h %08h %s",
		v__h5494,
		64'd0,
		32'd0,
		32'd0,
		"D");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Decode_halting && rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
  end
  // synopsys translate_on
endmodule  // mkDecode

