//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:52 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_request_put                O     1 reg
// response_get                   O    38 reg
// RDY_response_get               O     1 reg
// verbosity                      I     2
// CLK                            I     1 clock
// RST_N                          I     1 reset
// request_put                    I    32
// EN_request_put                 I     1
// EN_response_get                I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkExtracter(verbosity,
		   CLK,
		   RST_N,

		   request_put,
		   EN_request_put,
		   RDY_request_put,

		   EN_response_get,
		   response_get,
		   RDY_response_get);
  input  [1 : 0] verbosity;
  input  CLK;
  input  RST_N;

  // action method request_put
  input  [31 : 0] request_put;
  input  EN_request_put;
  output RDY_request_put;

  // actionvalue method response_get
  input  EN_response_get;
  output [37 : 0] response_get;
  output RDY_response_get;

  // signals for module outputs
  wire [37 : 0] response_get;
  wire RDY_request_put, RDY_response_get;

  // ports of submodule ff_extract_out
  wire [37 : 0] ff_extract_out$D_IN, ff_extract_out$D_OUT;
  wire ff_extract_out$CLR,
       ff_extract_out$DEQ,
       ff_extract_out$EMPTY_N,
       ff_extract_out$ENQ,
       ff_extract_out$FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_request_put,
       CAN_FIRE_response_get,
       WILL_FIRE_request_put,
       WILL_FIRE_response_get;

  // declarations used by system tasks
  // synopsys translate_off
  reg [31 : 0] v__h12093;
  reg [31 : 0] x__h12126;
  reg [31 : 0] v__h12085;
  // synopsys translate_on

  // remaining internal signals
  reg [26 : 0] x__h11756;
  wire [34 : 0] IF_request_put_BITS_30_TO_0_EQ_0_AND_NOT_reque_ETC___d372;
  wire [30 : 0] INV_new_inp41__q1,
		new_inp41_AND_INV_0x7FFFFFFE_SL_x1707_SRL_x1709__q2,
		new_inp__h141;
  wire [26 : 0] frac__h149;
  wire [7 : 0] SEXT_IF_IF_request_put_BIT_31_THEN_INV_request_ETC___d144,
	       SEXT_IF_new_inp41_BIT_30_THEN_b245_ELSE_b247__q4;
  wire [5 : 0] IF_new_inp41_BIT_30_THEN_b245_ELSE_b247__q3,
	       b__h1245,
	       b__h1247;
  wire [4 : 0] IF_IF_request_put_BIT_31_THEN_INV_request_put__ETC___d300,
	       x__h11707,
	       x__h11709,
	       x__h11744,
	       x__h1255,
	       x__h6309;
  wire [1 : 0] expo__h148;
  wire NOT_verbosity_ULE_1_74___d375;

  // action method request_put
  assign RDY_request_put = ff_extract_out$FULL_N ;
  assign CAN_FIRE_request_put = ff_extract_out$FULL_N ;
  assign WILL_FIRE_request_put = EN_request_put ;

  // actionvalue method response_get
  assign response_get = ff_extract_out$D_OUT ;
  assign RDY_response_get = ff_extract_out$EMPTY_N ;
  assign CAN_FIRE_response_get = ff_extract_out$EMPTY_N ;
  assign WILL_FIRE_response_get = EN_response_get ;

  // submodule ff_extract_out
  FIFO2 #(.width(32'd38), .guarded(1'd1)) ff_extract_out(.RST(RST_N),
							 .CLK(CLK),
							 .D_IN(ff_extract_out$D_IN),
							 .ENQ(ff_extract_out$ENQ),
							 .DEQ(ff_extract_out$DEQ),
							 .CLR(ff_extract_out$CLR),
							 .D_OUT(ff_extract_out$D_OUT),
							 .FULL_N(ff_extract_out$FULL_N),
							 .EMPTY_N(ff_extract_out$EMPTY_N));

  // submodule ff_extract_out
  assign ff_extract_out$D_IN =
	     { (request_put[30:0] == 31'd0 && !request_put[31]) ?
		 2'd2 :
		 ((request_put[30:0] == 31'd0 && request_put[31]) ?
		    2'd1 :
		    2'd0),
	       request_put[31],
	       IF_request_put_BITS_30_TO_0_EQ_0_AND_NOT_reque_ETC___d372 } ;
  assign ff_extract_out$ENQ = EN_request_put ;
  assign ff_extract_out$DEQ = EN_response_get ;
  assign ff_extract_out$CLR = 1'b0 ;

  // remaining internal signals
  assign IF_IF_request_put_BIT_31_THEN_INV_request_put__ETC___d300 =
	     new_inp__h141[30] ?
	       ((!INV_new_inp41__q1[30] && !INV_new_inp41__q1[29] &&
		 !INV_new_inp41__q1[28] &&
		 !INV_new_inp41__q1[27] &&
		 !INV_new_inp41__q1[26] &&
		 !INV_new_inp41__q1[25] &&
		 !INV_new_inp41__q1[24] &&
		 !INV_new_inp41__q1[23] &&
		 !INV_new_inp41__q1[22] &&
		 !INV_new_inp41__q1[21] &&
		 !INV_new_inp41__q1[20] &&
		 !INV_new_inp41__q1[19] &&
		 !INV_new_inp41__q1[18] &&
		 !INV_new_inp41__q1[17] &&
		 !INV_new_inp41__q1[16] &&
		 !INV_new_inp41__q1[15] &&
		 !INV_new_inp41__q1[14] &&
		 !INV_new_inp41__q1[13] &&
		 !INV_new_inp41__q1[12] &&
		 !INV_new_inp41__q1[11] &&
		 !INV_new_inp41__q1[10] &&
		 !INV_new_inp41__q1[9] &&
		 !INV_new_inp41__q1[8] &&
		 !INV_new_inp41__q1[7] &&
		 !INV_new_inp41__q1[6] &&
		 !INV_new_inp41__q1[5] &&
		 !INV_new_inp41__q1[4] &&
		 !INV_new_inp41__q1[3] &&
		 !INV_new_inp41__q1[2] &&
		 !INV_new_inp41__q1[1] &&
		 !INV_new_inp41__q1[0]) ?
		  5'd31 :
		  5'd30) -
	       x__h1255 :
	       ((!new_inp__h141[29] && !new_inp__h141[28] &&
		 !new_inp__h141[27] &&
		 !new_inp__h141[26] &&
		 !new_inp__h141[25] &&
		 !new_inp__h141[24] &&
		 !new_inp__h141[23] &&
		 !new_inp__h141[22] &&
		 !new_inp__h141[21] &&
		 !new_inp__h141[20] &&
		 !new_inp__h141[19] &&
		 !new_inp__h141[18] &&
		 !new_inp__h141[17] &&
		 !new_inp__h141[16] &&
		 !new_inp__h141[15] &&
		 !new_inp__h141[14] &&
		 !new_inp__h141[13] &&
		 !new_inp__h141[12] &&
		 !new_inp__h141[11] &&
		 !new_inp__h141[10] &&
		 !new_inp__h141[9] &&
		 !new_inp__h141[8] &&
		 !new_inp__h141[7] &&
		 !new_inp__h141[6] &&
		 !new_inp__h141[5] &&
		 !new_inp__h141[4] &&
		 !new_inp__h141[3] &&
		 !new_inp__h141[2] &&
		 !new_inp__h141[1] &&
		 !new_inp__h141[0]) ?
		  5'd31 :
		  5'd30) -
	       x__h6309 ;
  assign IF_new_inp41_BIT_30_THEN_b245_ELSE_b247__q3 =
	     new_inp__h141[30] ? b__h1245 : b__h1247 ;
  assign IF_request_put_BITS_30_TO_0_EQ_0_AND_NOT_reque_ETC___d372 =
	     (request_put[30:0] == 31'd0 && !request_put[31]) ?
	       35'd0 :
	       { SEXT_IF_IF_request_put_BIT_31_THEN_INV_request_ETC___d144 +
		 { 6'd0, expo__h148 },
		 frac__h149 } ;
  assign INV_new_inp41__q1 = ~new_inp__h141 ;
  assign NOT_verbosity_ULE_1_74___d375 = verbosity > 2'd1 ;
  assign SEXT_IF_IF_request_put_BIT_31_THEN_INV_request_ETC___d144 =
	     { SEXT_IF_new_inp41_BIT_30_THEN_b245_ELSE_b247__q4[5:0], 2'd0 } ;
  assign SEXT_IF_new_inp41_BIT_30_THEN_b245_ELSE_b247__q4 =
	     { {2{IF_new_inp41_BIT_30_THEN_b245_ELSE_b247__q3[5]}},
	       IF_new_inp41_BIT_30_THEN_b245_ELSE_b247__q3 } ;
  assign b__h1245 = { 1'd0, x__h1255 } - 6'd1 ;
  assign b__h1247 =
	     { 1'd1,
	       new_inp__h141[30] ?
		 5'd31 :
		 (new_inp__h141[29] ?
		    5'd30 :
		    (new_inp__h141[28] ?
		       5'd29 :
		       (new_inp__h141[27] ?
			  5'd28 :
			  (new_inp__h141[26] ?
			     5'd27 :
			     (new_inp__h141[25] ?
				5'd26 :
				(new_inp__h141[24] ?
				   5'd25 :
				   (new_inp__h141[23] ?
				      5'd24 :
				      (new_inp__h141[22] ?
					 5'd23 :
					 (new_inp__h141[21] ?
					    5'd22 :
					    (new_inp__h141[20] ?
					       5'd21 :
					       (new_inp__h141[19] ?
						  5'd20 :
						  (new_inp__h141[18] ?
						     5'd19 :
						     (new_inp__h141[17] ?
							5'd18 :
							(new_inp__h141[16] ?
							   5'd17 :
							   (new_inp__h141[15] ?
							      5'd16 :
							      (new_inp__h141[14] ?
								 5'd15 :
								 (new_inp__h141[13] ?
								    5'd14 :
								    (new_inp__h141[12] ?
								       5'd13 :
								       (new_inp__h141[11] ?
									  5'd12 :
									  (new_inp__h141[10] ?
									     5'd11 :
									     (new_inp__h141[9] ?
										5'd10 :
										(new_inp__h141[8] ?
										   5'd9 :
										   (new_inp__h141[7] ?
										      5'd8 :
										      (new_inp__h141[6] ?
											 5'd7 :
											 (new_inp__h141[5] ?
											    5'd6 :
											    (new_inp__h141[4] ?
											       5'd5 :
											       (new_inp__h141[3] ?
												  5'd4 :
												  (new_inp__h141[2] ?
												     5'd3 :
												     (new_inp__h141[1] ?
													5'd2 :
													(new_inp__h141[0] ?
													   5'd1 :
													   5'd0)))))))))))))))))))))))))))))) } +
	     6'd1 ;
  assign expo__h148 =
	     (IF_IF_request_put_BIT_31_THEN_INV_request_put__ETC___d300 <
	      5'd2) ?
	       new_inp__h141[1:0] << x__h11744 :
	       new_inp41_AND_INV_0x7FFFFFFE_SL_x1707_SRL_x1709__q2[1:0] ;
  assign frac__h149 = new_inp__h141[26:0] << x__h11756 ;
  assign new_inp41_AND_INV_0x7FFFFFFE_SL_x1707_SRL_x1709__q2 =
	     (new_inp__h141 & ~(31'h7FFFFFFE << x__h11707)) >> x__h11709 ;
  assign new_inp__h141 =
	     request_put[31] ?
	       ~request_put[30:0] + 31'd1 :
	       request_put[30:0] ;
  assign x__h11707 =
	     IF_IF_request_put_BIT_31_THEN_INV_request_put__ETC___d300 -
	     5'd1 ;
  assign x__h11709 =
	     IF_IF_request_put_BIT_31_THEN_INV_request_put__ETC___d300 -
	     5'd2 ;
  assign x__h11744 =
	     5'd2 -
	     IF_IF_request_put_BIT_31_THEN_INV_request_put__ETC___d300 ;
  assign x__h1255 =
	     INV_new_inp41__q1[30] ?
	       5'd0 :
	       (INV_new_inp41__q1[29] ?
		  5'd1 :
		  (INV_new_inp41__q1[28] ?
		     5'd2 :
		     (INV_new_inp41__q1[27] ?
			5'd3 :
			(INV_new_inp41__q1[26] ?
			   5'd4 :
			   (INV_new_inp41__q1[25] ?
			      5'd5 :
			      (INV_new_inp41__q1[24] ?
				 5'd6 :
				 (INV_new_inp41__q1[23] ?
				    5'd7 :
				    (INV_new_inp41__q1[22] ?
				       5'd8 :
				       (INV_new_inp41__q1[21] ?
					  5'd9 :
					  (INV_new_inp41__q1[20] ?
					     5'd10 :
					     (INV_new_inp41__q1[19] ?
						5'd11 :
						(INV_new_inp41__q1[18] ?
						   5'd12 :
						   (INV_new_inp41__q1[17] ?
						      5'd13 :
						      (INV_new_inp41__q1[16] ?
							 5'd14 :
							 (INV_new_inp41__q1[15] ?
							    5'd15 :
							    (INV_new_inp41__q1[14] ?
							       5'd16 :
							       (INV_new_inp41__q1[13] ?
								  5'd17 :
								  (INV_new_inp41__q1[12] ?
								     5'd18 :
								     (INV_new_inp41__q1[11] ?
									5'd19 :
									(INV_new_inp41__q1[10] ?
									   5'd20 :
									   (INV_new_inp41__q1[9] ?
									      5'd21 :
									      (INV_new_inp41__q1[8] ?
										 5'd22 :
										 (INV_new_inp41__q1[7] ?
										    5'd23 :
										    (INV_new_inp41__q1[6] ?
										       5'd24 :
										       (INV_new_inp41__q1[5] ?
											  5'd25 :
											  (INV_new_inp41__q1[4] ?
											     5'd26 :
											     (INV_new_inp41__q1[3] ?
												5'd27 :
												(INV_new_inp41__q1[2] ?
												   5'd28 :
												   (INV_new_inp41__q1[1] ?
												      5'd29 :
												      (INV_new_inp41__q1[0] ?
													 5'd30 :
													 5'd31)))))))))))))))))))))))))))))) ;
  assign x__h6309 =
	     new_inp__h141[30] ?
	       5'd0 :
	       (new_inp__h141[29] ?
		  5'd1 :
		  (new_inp__h141[28] ?
		     5'd2 :
		     (new_inp__h141[27] ?
			5'd3 :
			(new_inp__h141[26] ?
			   5'd4 :
			   (new_inp__h141[25] ?
			      5'd5 :
			      (new_inp__h141[24] ?
				 5'd6 :
				 (new_inp__h141[23] ?
				    5'd7 :
				    (new_inp__h141[22] ?
				       5'd8 :
				       (new_inp__h141[21] ?
					  5'd9 :
					  (new_inp__h141[20] ?
					     5'd10 :
					     (new_inp__h141[19] ?
						5'd11 :
						(new_inp__h141[18] ?
						   5'd12 :
						   (new_inp__h141[17] ?
						      5'd13 :
						      (new_inp__h141[16] ?
							 5'd14 :
							 (new_inp__h141[15] ?
							    5'd15 :
							    (new_inp__h141[14] ?
							       5'd16 :
							       (new_inp__h141[13] ?
								  5'd17 :
								  (new_inp__h141[12] ?
								     5'd18 :
								     (new_inp__h141[11] ?
									5'd19 :
									(new_inp__h141[10] ?
									   5'd20 :
									   (new_inp__h141[9] ?
									      5'd21 :
									      (new_inp__h141[8] ?
										 5'd22 :
										 (new_inp__h141[7] ?
										    5'd23 :
										    (new_inp__h141[6] ?
										       5'd24 :
										       (new_inp__h141[5] ?
											  5'd25 :
											  (new_inp__h141[4] ?
											     5'd26 :
											     (new_inp__h141[3] ?
												5'd27 :
												(new_inp__h141[2] ?
												   5'd28 :
												   (new_inp__h141[1] ?
												      5'd29 :
												      (new_inp__h141[0] ?
													 5'd30 :
													 5'd31)))))))))))))))))))))))))))))) ;
  always@(IF_IF_request_put_BIT_31_THEN_INV_request_put__ETC___d300)
  begin
    case (IF_IF_request_put_BIT_31_THEN_INV_request_put__ETC___d300)
      5'd3: x__h11756 = 27'd26;
      5'd4: x__h11756 = 27'd25;
      5'd5: x__h11756 = 27'd24;
      5'd6: x__h11756 = 27'd23;
      5'd7: x__h11756 = 27'd22;
      5'd8: x__h11756 = 27'd21;
      5'd9: x__h11756 = 27'd20;
      5'd10: x__h11756 = 27'd19;
      5'd11: x__h11756 = 27'd18;
      5'd12: x__h11756 = 27'd17;
      5'd13: x__h11756 = 27'd16;
      5'd14: x__h11756 = 27'd15;
      5'd15: x__h11756 = 27'd14;
      5'd16: x__h11756 = 27'd13;
      5'd17: x__h11756 = 27'd12;
      5'd18: x__h11756 = 27'd11;
      5'd19: x__h11756 = 27'd10;
      5'd20: x__h11756 = 27'd9;
      5'd21: x__h11756 = 27'd8;
      5'd22: x__h11756 = 27'd7;
      5'd23: x__h11756 = 27'd6;
      5'd24: x__h11756 = 27'd5;
      5'd25: x__h11756 = 27'd4;
      5'd26: x__h11756 = 27'd3;
      5'd27: x__h11756 = 27'd2;
      5'd28: x__h11756 = 27'd1;
      5'd29: x__h11756 = 27'd0;
      default: x__h11756 =
		   (IF_IF_request_put_BIT_31_THEN_INV_request_put__ETC___d300 <=
		    5'd2) ?
		     27'd27 :
		     27'd0;
    endcase
  end

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_74___d375)
	begin
	  v__h12093 = $stime;
	  #0;
	end
    x__h12126 = v__h12093 + 32'd5;
    v__h12085 = x__h12126 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_74___d375)
	$display("%0d: %m.request: 0x%08x", v__h12085, request_put);
  end
  // synopsys translate_on
endmodule  // mkExtracter

