//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:41 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_init                       O     1 const
// RDY_fi_RR_to_EX_Int_enq        O     1
// fi_RR_to_EX_Int_notFull        O     1
// RDY_fi_RR_to_EX_Int_notFull    O     1 const
// fo_EX_Int_to_Retire_first      O   197
// RDY_fo_EX_Int_to_Retire_first  O     1
// RDY_fo_EX_Int_to_Retire_deq    O     1
// fo_EX_Int_to_Retire_notEmpty   O     1
// RDY_fo_EX_Int_to_Retire_notEmpty  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// init_initial_params            I   208 reg
// fi_RR_to_EX_Int_enq_x          I   224
// EN_init                        I     1
// EN_fi_RR_to_EX_Int_enq         I     1
// EN_fo_EX_Int_to_Retire_deq     I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkEX_Int(CLK,
		RST_N,

		init_initial_params,
		EN_init,
		RDY_init,

		fi_RR_to_EX_Int_enq_x,
		EN_fi_RR_to_EX_Int_enq,
		RDY_fi_RR_to_EX_Int_enq,

		fi_RR_to_EX_Int_notFull,
		RDY_fi_RR_to_EX_Int_notFull,

		fo_EX_Int_to_Retire_first,
		RDY_fo_EX_Int_to_Retire_first,

		EN_fo_EX_Int_to_Retire_deq,
		RDY_fo_EX_Int_to_Retire_deq,

		fo_EX_Int_to_Retire_notEmpty,
		RDY_fo_EX_Int_to_Retire_notEmpty);
  input  CLK;
  input  RST_N;

  // action method init
  input  [207 : 0] init_initial_params;
  input  EN_init;
  output RDY_init;

  // action method fi_RR_to_EX_Int_enq
  input  [223 : 0] fi_RR_to_EX_Int_enq_x;
  input  EN_fi_RR_to_EX_Int_enq;
  output RDY_fi_RR_to_EX_Int_enq;

  // value method fi_RR_to_EX_Int_notFull
  output fi_RR_to_EX_Int_notFull;
  output RDY_fi_RR_to_EX_Int_notFull;

  // value method fo_EX_Int_to_Retire_first
  output [196 : 0] fo_EX_Int_to_Retire_first;
  output RDY_fo_EX_Int_to_Retire_first;

  // action method fo_EX_Int_to_Retire_deq
  input  EN_fo_EX_Int_to_Retire_deq;
  output RDY_fo_EX_Int_to_Retire_deq;

  // value method fo_EX_Int_to_Retire_notEmpty
  output fo_EX_Int_to_Retire_notEmpty;
  output RDY_fo_EX_Int_to_Retire_notEmpty;

  // signals for module outputs
  wire [196 : 0] fo_EX_Int_to_Retire_first;
  wire RDY_fi_RR_to_EX_Int_enq,
       RDY_fi_RR_to_EX_Int_notFull,
       RDY_fo_EX_Int_to_Retire_deq,
       RDY_fo_EX_Int_to_Retire_first,
       RDY_fo_EX_Int_to_Retire_notEmpty,
       RDY_init,
       fi_RR_to_EX_Int_notFull,
       fo_EX_Int_to_Retire_notEmpty;

  // inlined wires
  wire [224 : 0] f_RR_to_EX_Int_rv$port0__write_1,
		 f_RR_to_EX_Int_rv$port1__read,
		 f_RR_to_EX_Int_rv$port1__write_1,
		 f_RR_to_EX_Int_rv$port2__read;
  wire [197 : 0] f_EX_Int_to_Retire_rv$port0__write_1,
		 f_EX_Int_to_Retire_rv$port1__read,
		 f_EX_Int_to_Retire_rv$port1__write_1,
		 f_EX_Int_to_Retire_rv$port2__read;

  // register f_EX_Int_to_Retire_rv
  reg [197 : 0] f_EX_Int_to_Retire_rv;
  wire [197 : 0] f_EX_Int_to_Retire_rv$D_IN;
  wire f_EX_Int_to_Retire_rv$EN;

  // register f_RR_to_EX_Int_rv
  reg [224 : 0] f_RR_to_EX_Int_rv;
  wire [224 : 0] f_RR_to_EX_Int_rv$D_IN;
  wire f_RR_to_EX_Int_rv$EN;

  // register rg_flog
  reg [31 : 0] rg_flog;
  wire [31 : 0] rg_flog$D_IN;
  wire rg_flog$EN;

  // rule scheduling signals
  wire CAN_FIRE_RL_rl_EX_Int,
       CAN_FIRE_fi_RR_to_EX_Int_enq,
       CAN_FIRE_fo_EX_Int_to_Retire_deq,
       CAN_FIRE_init,
       WILL_FIRE_RL_rl_EX_Int,
       WILL_FIRE_fi_RR_to_EX_Int_enq,
       WILL_FIRE_fo_EX_Int_to_Retire_deq,
       WILL_FIRE_init;

  // declarations used by system tasks
  // synopsys translate_off
  reg [31 : 0] v__h1490;
  reg [31 : 0] v__h1757;
  reg [31 : 0] v__h2544;
  reg [31 : 0] v__h3087;
  reg [31 : 0] x__h1523;
  reg [31 : 0] x__h1790;
  reg [31 : 0] x__h2577;
  reg [31 : 0] x__h3120;
  reg [31 : 0] v__h1482;
  reg [31 : 0] v__h1749;
  reg [31 : 0] v__h2536;
  reg [31 : 0] v__h3079;
  // synopsys translate_on

  // remaining internal signals
  reg [31 : 0] x1_avValue_data__h2352,
	       y_avValue_snd__h1199,
	       y_avValue_snd__h1252;
  wire [31 : 0] f_RR_to_EX_Int_rv_BITS_191_TO_160__q1,
		v__h1119,
		x1_avValue_snd__h1202,
		x1_avValue_snd__h1255,
		y_OP_IMM___1__h1292,
		y_OP_IMM___1__h1297,
		y_OP_IMM___1__h1302,
		y_OP_IMM___1__h1307,
		y_OP_IMM___1__h1312,
		y_OP_IMM___1__h1317,
		y_OP_IMM___1__h1322,
		y_OP_IMM___1__h1327,
		y_OP___1__h1353,
		y_OP___1__h1358,
		y_OP___1__h1363,
		y_OP___1__h1368,
		y_OP___1__h1373,
		y_OP___1__h1378,
		y_OP___1__h1383,
		y_OP___1__h1388,
		y___1_data__h1094;
  wire IF_f_RR_to_EX_Int_rv_port0__read_BITS_198_TO_1_ETC___d58;

  // action method init
  assign RDY_init = 1'd1 ;
  assign CAN_FIRE_init = 1'd1 ;
  assign WILL_FIRE_init = EN_init ;

  // action method fi_RR_to_EX_Int_enq
  assign RDY_fi_RR_to_EX_Int_enq = !f_RR_to_EX_Int_rv$port1__read[224] ;
  assign CAN_FIRE_fi_RR_to_EX_Int_enq = !f_RR_to_EX_Int_rv$port1__read[224] ;
  assign WILL_FIRE_fi_RR_to_EX_Int_enq = EN_fi_RR_to_EX_Int_enq ;

  // value method fi_RR_to_EX_Int_notFull
  assign fi_RR_to_EX_Int_notFull = !f_RR_to_EX_Int_rv$port1__read[224] ;
  assign RDY_fi_RR_to_EX_Int_notFull = 1'd1 ;

  // value method fo_EX_Int_to_Retire_first
  assign fo_EX_Int_to_Retire_first =
	     f_EX_Int_to_Retire_rv$port1__read[196:0] ;
  assign RDY_fo_EX_Int_to_Retire_first =
	     f_EX_Int_to_Retire_rv$port1__read[197] ;

  // action method fo_EX_Int_to_Retire_deq
  assign RDY_fo_EX_Int_to_Retire_deq =
	     f_EX_Int_to_Retire_rv$port1__read[197] ;
  assign CAN_FIRE_fo_EX_Int_to_Retire_deq =
	     f_EX_Int_to_Retire_rv$port1__read[197] ;
  assign WILL_FIRE_fo_EX_Int_to_Retire_deq = EN_fo_EX_Int_to_Retire_deq ;

  // value method fo_EX_Int_to_Retire_notEmpty
  assign fo_EX_Int_to_Retire_notEmpty =
	     f_EX_Int_to_Retire_rv$port1__read[197] ;
  assign RDY_fo_EX_Int_to_Retire_notEmpty = 1'd1 ;

  // rule RL_rl_EX_Int
  assign CAN_FIRE_RL_rl_EX_Int =
	     f_RR_to_EX_Int_rv[224] && !f_EX_Int_to_Retire_rv[197] ;
  assign WILL_FIRE_RL_rl_EX_Int = CAN_FIRE_RL_rl_EX_Int ;

  // inlined wires
  assign f_RR_to_EX_Int_rv$port0__write_1 =
	     { 1'd0,
	       224'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign f_RR_to_EX_Int_rv$port1__read =
	     CAN_FIRE_RL_rl_EX_Int ?
	       f_RR_to_EX_Int_rv$port0__write_1 :
	       f_RR_to_EX_Int_rv ;
  assign f_RR_to_EX_Int_rv$port1__write_1 = { 1'd1, fi_RR_to_EX_Int_enq_x } ;
  assign f_RR_to_EX_Int_rv$port2__read =
	     EN_fi_RR_to_EX_Int_enq ?
	       f_RR_to_EX_Int_rv$port1__write_1 :
	       f_RR_to_EX_Int_rv$port1__read ;
  assign f_EX_Int_to_Retire_rv$port0__write_1 =
	     { 2'd2,
	       4'bxxxx /* unspecified value */ ,
	       32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ,
	       x1_avValue_data__h2352,
	       f_RR_to_EX_Int_rv[95:0],
	       f_RR_to_EX_Int_rv[223:192] } ;
  assign f_EX_Int_to_Retire_rv$port1__read =
	     CAN_FIRE_RL_rl_EX_Int ?
	       f_EX_Int_to_Retire_rv$port0__write_1 :
	       f_EX_Int_to_Retire_rv ;
  assign f_EX_Int_to_Retire_rv$port1__write_1 =
	     { 1'd0,
	       197'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign f_EX_Int_to_Retire_rv$port2__read =
	     EN_fo_EX_Int_to_Retire_deq ?
	       f_EX_Int_to_Retire_rv$port1__write_1 :
	       f_EX_Int_to_Retire_rv$port1__read ;

  // register f_EX_Int_to_Retire_rv
  assign f_EX_Int_to_Retire_rv$D_IN = f_EX_Int_to_Retire_rv$port2__read ;
  assign f_EX_Int_to_Retire_rv$EN = 1'b1 ;

  // register f_RR_to_EX_Int_rv
  assign f_RR_to_EX_Int_rv$D_IN = f_RR_to_EX_Int_rv$port2__read ;
  assign f_RR_to_EX_Int_rv$EN = 1'b1 ;

  // register rg_flog
  assign rg_flog$D_IN = init_initial_params[207:176] ;
  assign rg_flog$EN = EN_init ;

  // remaining internal signals
  assign IF_f_RR_to_EX_Int_rv_port0__read_BITS_198_TO_1_ETC___d58 =
	     (f_RR_to_EX_Int_rv[198:192] == 7'b0010011) ?
	       1'b0 :
	       f_RR_to_EX_Int_rv[198:192] != 7'b0110011 ;
  assign f_RR_to_EX_Int_rv_BITS_191_TO_160__q1 = f_RR_to_EX_Int_rv[191:160] ;
  assign v__h1119 = x1_avValue_snd__h1202 | x1_avValue_snd__h1255 ;
  assign x1_avValue_snd__h1202 =
	     (f_RR_to_EX_Int_rv[198:192] == 7'b0110011) ?
	       y_avValue_snd__h1199 :
	       32'd0 ;
  assign x1_avValue_snd__h1255 =
	     (f_RR_to_EX_Int_rv[198:192] == 7'b0010011) ?
	       y_avValue_snd__h1252 :
	       32'd0 ;
  assign y_OP_IMM___1__h1292 =
	     f_RR_to_EX_Int_rv[191:160] + f_RR_to_EX_Int_rv[127:96] ;
  assign y_OP_IMM___1__h1297 =
	     ((f_RR_to_EX_Int_rv[191:160] ^ 32'h80000000) <
	      (f_RR_to_EX_Int_rv[127:96] ^ 32'h80000000)) ?
	       32'd1 :
	       32'd0 ;
  assign y_OP_IMM___1__h1302 =
	     (f_RR_to_EX_Int_rv[191:160] < f_RR_to_EX_Int_rv[127:96]) ?
	       32'd1 :
	       32'd0 ;
  assign y_OP_IMM___1__h1307 =
	     f_RR_to_EX_Int_rv[191:160] ^ f_RR_to_EX_Int_rv[127:96] ;
  assign y_OP_IMM___1__h1312 =
	     f_RR_to_EX_Int_rv[191:160] | f_RR_to_EX_Int_rv[127:96] ;
  assign y_OP_IMM___1__h1317 =
	     f_RR_to_EX_Int_rv[191:160] & f_RR_to_EX_Int_rv[127:96] ;
  assign y_OP_IMM___1__h1322 =
	     f_RR_to_EX_Int_rv[191:160] << f_RR_to_EX_Int_rv[100:96] ;
  assign y_OP_IMM___1__h1327 =
	     f_RR_to_EX_Int_rv[222] ?
	       f_RR_to_EX_Int_rv[191:160] >> f_RR_to_EX_Int_rv[100:96] |
	       ~(32'hFFFFFFFF >> f_RR_to_EX_Int_rv[100:96]) &
	       {32{f_RR_to_EX_Int_rv_BITS_191_TO_160__q1[31]}} :
	       f_RR_to_EX_Int_rv[191:160] >> f_RR_to_EX_Int_rv[100:96] ;
  assign y_OP___1__h1353 =
	     f_RR_to_EX_Int_rv[222] ?
	       f_RR_to_EX_Int_rv[191:160] - f_RR_to_EX_Int_rv[159:128] :
	       f_RR_to_EX_Int_rv[191:160] + f_RR_to_EX_Int_rv[159:128] ;
  assign y_OP___1__h1358 =
	     f_RR_to_EX_Int_rv[191:160] << f_RR_to_EX_Int_rv[132:128] ;
  assign y_OP___1__h1363 =
	     ((f_RR_to_EX_Int_rv[191:160] ^ 32'h80000000) <
	      (f_RR_to_EX_Int_rv[159:128] ^ 32'h80000000)) ?
	       32'd1 :
	       32'd0 ;
  assign y_OP___1__h1368 =
	     (f_RR_to_EX_Int_rv[191:160] < f_RR_to_EX_Int_rv[159:128]) ?
	       32'd1 :
	       32'd0 ;
  assign y_OP___1__h1373 =
	     f_RR_to_EX_Int_rv[191:160] ^ f_RR_to_EX_Int_rv[159:128] ;
  assign y_OP___1__h1378 =
	     f_RR_to_EX_Int_rv[222] ?
	       f_RR_to_EX_Int_rv[191:160] >> f_RR_to_EX_Int_rv[132:128] |
	       ~(32'hFFFFFFFF >> f_RR_to_EX_Int_rv[132:128]) &
	       {32{f_RR_to_EX_Int_rv_BITS_191_TO_160__q1[31]}} :
	       f_RR_to_EX_Int_rv[191:160] >> f_RR_to_EX_Int_rv[132:128] ;
  assign y_OP___1__h1383 =
	     f_RR_to_EX_Int_rv[191:160] | f_RR_to_EX_Int_rv[159:128] ;
  assign y_OP___1__h1388 =
	     f_RR_to_EX_Int_rv[191:160] & f_RR_to_EX_Int_rv[159:128] ;
  assign y___1_data__h1094 =
	     f_RR_to_EX_Int_rv[31:0] + f_RR_to_EX_Int_rv[127:96] ;
  always@(f_RR_to_EX_Int_rv or
	  y_OP_IMM___1__h1292 or
	  y_OP_IMM___1__h1322 or
	  y_OP_IMM___1__h1297 or
	  y_OP_IMM___1__h1302 or
	  y_OP_IMM___1__h1307 or
	  y_OP_IMM___1__h1327 or y_OP_IMM___1__h1312 or y_OP_IMM___1__h1317)
  begin
    case (f_RR_to_EX_Int_rv[206:204])
      3'b0: y_avValue_snd__h1252 = y_OP_IMM___1__h1292;
      3'b001: y_avValue_snd__h1252 = y_OP_IMM___1__h1322;
      3'b010: y_avValue_snd__h1252 = y_OP_IMM___1__h1297;
      3'b011: y_avValue_snd__h1252 = y_OP_IMM___1__h1302;
      3'b100: y_avValue_snd__h1252 = y_OP_IMM___1__h1307;
      3'b101: y_avValue_snd__h1252 = y_OP_IMM___1__h1327;
      3'b110: y_avValue_snd__h1252 = y_OP_IMM___1__h1312;
      3'b111: y_avValue_snd__h1252 = y_OP_IMM___1__h1317;
    endcase
  end
  always@(f_RR_to_EX_Int_rv or
	  y_OP___1__h1353 or
	  y_OP___1__h1358 or
	  y_OP___1__h1363 or
	  y_OP___1__h1368 or
	  y_OP___1__h1373 or
	  y_OP___1__h1378 or y_OP___1__h1383 or y_OP___1__h1388)
  begin
    case (f_RR_to_EX_Int_rv[206:204])
      3'b0: y_avValue_snd__h1199 = y_OP___1__h1353;
      3'b001: y_avValue_snd__h1199 = y_OP___1__h1358;
      3'b010: y_avValue_snd__h1199 = y_OP___1__h1363;
      3'b011: y_avValue_snd__h1199 = y_OP___1__h1368;
      3'b100: y_avValue_snd__h1199 = y_OP___1__h1373;
      3'b101: y_avValue_snd__h1199 = y_OP___1__h1378;
      3'b110: y_avValue_snd__h1199 = y_OP___1__h1383;
      3'b111: y_avValue_snd__h1199 = y_OP___1__h1388;
    endcase
  end
  always@(f_RR_to_EX_Int_rv or v__h1119 or y___1_data__h1094)
  begin
    case (f_RR_to_EX_Int_rv[198:194])
      5'd5: x1_avValue_data__h2352 = y___1_data__h1094;
      5'd13: x1_avValue_data__h2352 = f_RR_to_EX_Int_rv[127:96];
      default: x1_avValue_data__h2352 = v__h1119;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        f_EX_Int_to_Retire_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0,
	      197'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
	f_RR_to_EX_Int_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0,
	      224'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
	rg_flog <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (f_EX_Int_to_Retire_rv$EN)
	  f_EX_Int_to_Retire_rv <= `BSV_ASSIGNMENT_DELAY
	      f_EX_Int_to_Retire_rv$D_IN;
	if (f_RR_to_EX_Int_rv$EN)
	  f_RR_to_EX_Int_rv <= `BSV_ASSIGNMENT_DELAY f_RR_to_EX_Int_rv$D_IN;
	if (rg_flog$EN) rg_flog <= `BSV_ASSIGNMENT_DELAY rg_flog$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    f_EX_Int_to_Retire_rv =
	198'h2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    f_RR_to_EX_Int_rv =
	225'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    rg_flog = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && f_RR_to_EX_Int_rv[198:194] == 5'd13 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog,
		"fn_EX_IALU: LUI x%0d <= %0h",
		f_RR_to_EX_Int_rv[203:199],
		f_RR_to_EX_Int_rv[127:96]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && f_RR_to_EX_Int_rv[198:194] == 5'd13 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && f_RR_to_EX_Int_rv[198:194] == 5'd5 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog,
		"fn_EX_IALU: AUIPC x%0d <= %0h",
		f_RR_to_EX_Int_rv[203:199],
		y___1_data__h1094);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && f_RR_to_EX_Int_rv[198:194] == 5'd5 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && f_RR_to_EX_Int_rv[198:194] != 5'd13 &&
	  f_RR_to_EX_Int_rv[198:194] != 5'd5 &&
	  IF_f_RR_to_EX_Int_rv_port0__read_BITS_198_TO_1_ETC___d58 &&
	  rg_flog != 32'd0)
	begin
	  v__h1490 = $stime;
	  #0;
	end
    x__h1523 = v__h1490 + 32'd5;
    v__h1482 = x__h1523 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && f_RR_to_EX_Int_rv[198:194] != 5'd13 &&
	  f_RR_to_EX_Int_rv[198:194] != 5'd5 &&
	  IF_f_RR_to_EX_Int_rv_port0__read_BITS_198_TO_1_ETC___d58 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h1482);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && f_RR_to_EX_Int_rv[198:194] != 5'd13 &&
	  f_RR_to_EX_Int_rv[198:194] != 5'd5 &&
	  IF_f_RR_to_EX_Int_rv_port0__read_BITS_198_TO_1_ETC___d58 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog,
		"ERROR: fn_IALU: UNIMPLEMENTED: instr:",
		f_RR_to_EX_Int_rv[223:192]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && f_RR_to_EX_Int_rv[198:194] != 5'd13 &&
	  f_RR_to_EX_Int_rv[198:194] != 5'd5 &&
	  IF_f_RR_to_EX_Int_rv_port0__read_BITS_198_TO_1_ETC___d58 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && f_RR_to_EX_Int_rv[198:194] != 5'd13 &&
	  f_RR_to_EX_Int_rv[198:194] != 5'd5 &&
	  IF_f_RR_to_EX_Int_rv_port0__read_BITS_198_TO_1_ETC___d58)
	begin
	  v__h1757 = $stime;
	  #0;
	end
    x__h1790 = v__h1757 + 32'd5;
    v__h1749 = x__h1790 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && f_RR_to_EX_Int_rv[198:194] != 5'd13 &&
	  f_RR_to_EX_Int_rv[198:194] != 5'd5 &&
	  IF_f_RR_to_EX_Int_rv_port0__read_BITS_198_TO_1_ETC___d58)
	$write("%0d: ", v__h1749);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && f_RR_to_EX_Int_rv[198:194] != 5'd13 &&
	  f_RR_to_EX_Int_rv[198:194] != 5'd5 &&
	  IF_f_RR_to_EX_Int_rv_port0__read_BITS_198_TO_1_ETC___d58)
	$write("ERROR: fn_IALU: UNIMPLEMENTED: instr:",
	       f_RR_to_EX_Int_rv[223:192]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && f_RR_to_EX_Int_rv[198:194] != 5'd13 &&
	  f_RR_to_EX_Int_rv[198:194] != 5'd5 &&
	  IF_f_RR_to_EX_Int_rv_port0__read_BITS_198_TO_1_ETC___d58)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && f_RR_to_EX_Int_rv[198:194] != 5'd13 &&
	  f_RR_to_EX_Int_rv[198:194] != 5'd5 &&
	  IF_f_RR_to_EX_Int_rv_port0__read_BITS_198_TO_1_ETC___d58)
	$finish(32'd1);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && f_RR_to_EX_Int_rv[198:194] != 5'd13 &&
	  f_RR_to_EX_Int_rv[198:194] != 5'd5 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog,
		"fn_EX_IALU: IALU x%0d <= %0h",
		f_RR_to_EX_Int_rv[203:199],
		v__h1119);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && f_RR_to_EX_Int_rv[198:194] != 5'd13 &&
	  f_RR_to_EX_Int_rv[198:194] != 5'd5 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	begin
	  v__h2544 = $stime;
	  #0;
	end
    x__h2577 = v__h2544 + 32'd5;
    v__h2536 = x__h2577 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h2536);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog, "CPU.EX_Int");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0) $fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog, "    ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog, "    RR_to_EX{", "I_%0d", f_RR_to_EX_Int_rv[95:32]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog, " pc:%08h", f_RR_to_EX_Int_rv[31:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog, " instr:%08h\n", f_RR_to_EX_Int_rv[223:192]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog, "             ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog, "rs1_val:%08h ", f_RR_to_EX_Int_rv[191:160]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog, " rs2_val:%08h ", f_RR_to_EX_Int_rv[159:128]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog, " imm:%08h ", f_RR_to_EX_Int_rv[127:96]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0) $fwrite(rg_flog, "}");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0) $fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog, "    ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog,
		"    EX_to_Retire{",
		"I_%0d",
		f_RR_to_EX_Int_rv[95:32]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog, " pc:%08h", f_RR_to_EX_Int_rv[31:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog, " instr:%08h\n", f_RR_to_EX_Int_rv[223:192]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog, "                 ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog, " data:%08h", x1_avValue_data__h2352);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0) $fwrite(rg_flog, "}");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0) $fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	begin
	  v__h3087 = $stime;
	  #0;
	end
    x__h3120 = v__h3087 + 32'd5;
    v__h3079 = x__h3120 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0)
	$fwrite(rg_flog,
		"Trace %0d %0d %08h %08h %s",
		v__h3079,
		f_RR_to_EX_Int_rv[95:32],
		f_RR_to_EX_Int_rv[31:0],
		f_RR_to_EX_Int_rv[223:192],
		"EX.I");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0) $fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Int && rg_flog != 32'd0) $fwrite(rg_flog, "\n");
  end
  // synopsys translate_on
endmodule  // mkEX_Int

