//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:40 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_init                       O     1 const
// RDY_fi_RR_to_EX_Control_enq    O     1
// fi_RR_to_EX_Control_notFull    O     1
// RDY_fi_RR_to_EX_Control_notFull  O     1 const
// fo_EX_Control_to_Retire_first  O   229
// RDY_fo_EX_Control_to_Retire_first  O     1
// RDY_fo_EX_Control_to_Retire_deq  O     1
// fo_EX_Control_to_Retire_notEmpty  O     1
// RDY_fo_EX_Control_to_Retire_notEmpty  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// init_initial_params            I   208 reg
// fi_RR_to_EX_Control_enq_x      I   256
// EN_init                        I     1
// EN_fi_RR_to_EX_Control_enq     I     1
// EN_fo_EX_Control_to_Retire_deq  I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkEX_Control(CLK,
		    RST_N,

		    init_initial_params,
		    EN_init,
		    RDY_init,

		    fi_RR_to_EX_Control_enq_x,
		    EN_fi_RR_to_EX_Control_enq,
		    RDY_fi_RR_to_EX_Control_enq,

		    fi_RR_to_EX_Control_notFull,
		    RDY_fi_RR_to_EX_Control_notFull,

		    fo_EX_Control_to_Retire_first,
		    RDY_fo_EX_Control_to_Retire_first,

		    EN_fo_EX_Control_to_Retire_deq,
		    RDY_fo_EX_Control_to_Retire_deq,

		    fo_EX_Control_to_Retire_notEmpty,
		    RDY_fo_EX_Control_to_Retire_notEmpty);
  input  CLK;
  input  RST_N;

  // action method init
  input  [207 : 0] init_initial_params;
  input  EN_init;
  output RDY_init;

  // action method fi_RR_to_EX_Control_enq
  input  [255 : 0] fi_RR_to_EX_Control_enq_x;
  input  EN_fi_RR_to_EX_Control_enq;
  output RDY_fi_RR_to_EX_Control_enq;

  // value method fi_RR_to_EX_Control_notFull
  output fi_RR_to_EX_Control_notFull;
  output RDY_fi_RR_to_EX_Control_notFull;

  // value method fo_EX_Control_to_Retire_first
  output [228 : 0] fo_EX_Control_to_Retire_first;
  output RDY_fo_EX_Control_to_Retire_first;

  // action method fo_EX_Control_to_Retire_deq
  input  EN_fo_EX_Control_to_Retire_deq;
  output RDY_fo_EX_Control_to_Retire_deq;

  // value method fo_EX_Control_to_Retire_notEmpty
  output fo_EX_Control_to_Retire_notEmpty;
  output RDY_fo_EX_Control_to_Retire_notEmpty;

  // signals for module outputs
  wire [228 : 0] fo_EX_Control_to_Retire_first;
  wire RDY_fi_RR_to_EX_Control_enq,
       RDY_fi_RR_to_EX_Control_notFull,
       RDY_fo_EX_Control_to_Retire_deq,
       RDY_fo_EX_Control_to_Retire_first,
       RDY_fo_EX_Control_to_Retire_notEmpty,
       RDY_init,
       fi_RR_to_EX_Control_notFull,
       fo_EX_Control_to_Retire_notEmpty;

  // inlined wires
  wire [256 : 0] f_RR_to_EX_Control_rv$port0__write_1,
		 f_RR_to_EX_Control_rv$port1__read,
		 f_RR_to_EX_Control_rv$port1__write_1,
		 f_RR_to_EX_Control_rv$port2__read;
  wire [229 : 0] f_EX_Control_to_Retire_rv$port0__write_1,
		 f_EX_Control_to_Retire_rv$port1__read,
		 f_EX_Control_to_Retire_rv$port1__write_1,
		 f_EX_Control_to_Retire_rv$port2__read;

  // register f_EX_Control_to_Retire_rv
  reg [229 : 0] f_EX_Control_to_Retire_rv;
  wire [229 : 0] f_EX_Control_to_Retire_rv$D_IN;
  wire f_EX_Control_to_Retire_rv$EN;

  // register f_RR_to_EX_Control_rv
  reg [256 : 0] f_RR_to_EX_Control_rv;
  wire [256 : 0] f_RR_to_EX_Control_rv$D_IN;
  wire f_RR_to_EX_Control_rv$EN;

  // register rg_flog
  reg [31 : 0] rg_flog;
  wire [31 : 0] rg_flog$D_IN;
  wire rg_flog$EN;

  // rule scheduling signals
  wire CAN_FIRE_RL_rl_EX_Control,
       CAN_FIRE_fi_RR_to_EX_Control_enq,
       CAN_FIRE_fo_EX_Control_to_Retire_deq,
       CAN_FIRE_init,
       WILL_FIRE_RL_rl_EX_Control,
       WILL_FIRE_fi_RR_to_EX_Control_enq,
       WILL_FIRE_fo_EX_Control_to_Retire_deq,
       WILL_FIRE_init;

  // declarations used by system tasks
  // synopsys translate_off
  reg [31 : 0] v__h996;
  reg [31 : 0] v__h1289;
  reg [31 : 0] v__h1923;
  reg [31 : 0] v__h2481;
  reg [31 : 0] x__h1029;
  reg [31 : 0] x__h1322;
  reg [31 : 0] x__h1956;
  reg [31 : 0] x__h2514;
  reg [31 : 0] v__h988;
  reg [31 : 0] v__h1281;
  reg [31 : 0] v__h1915;
  reg [31 : 0] v__h2473;
  // synopsys translate_on

  // remaining internal signals
  reg [31 : 0] next_pc__h1462;
  reg CASE_f_RR_to_EX_Control_rv_BITS_166_TO_162_24__ETC__q1,
      IF_f_RR_to_EX_Control_rv_port0__read_BITS_166__ETC___d60,
      IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d50,
      IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d79;
  wire [31 : 0] f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d56,
		target_pc__h707,
		y_avValue_snd__h1437,
		y_avValue_snd__h1449;
  wire NOT_rg_flog_7_EQ_0_8_9_AND_IF_f_RR_to_EX_Contr_ETC___d85,
       f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d36,
       f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d40,
       f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d44;

  // action method init
  assign RDY_init = 1'd1 ;
  assign CAN_FIRE_init = 1'd1 ;
  assign WILL_FIRE_init = EN_init ;

  // action method fi_RR_to_EX_Control_enq
  assign RDY_fi_RR_to_EX_Control_enq =
	     !f_RR_to_EX_Control_rv$port1__read[256] ;
  assign CAN_FIRE_fi_RR_to_EX_Control_enq =
	     !f_RR_to_EX_Control_rv$port1__read[256] ;
  assign WILL_FIRE_fi_RR_to_EX_Control_enq = EN_fi_RR_to_EX_Control_enq ;

  // value method fi_RR_to_EX_Control_notFull
  assign fi_RR_to_EX_Control_notFull =
	     !f_RR_to_EX_Control_rv$port1__read[256] ;
  assign RDY_fi_RR_to_EX_Control_notFull = 1'd1 ;

  // value method fo_EX_Control_to_Retire_first
  assign fo_EX_Control_to_Retire_first =
	     f_EX_Control_to_Retire_rv$port1__read[228:0] ;
  assign RDY_fo_EX_Control_to_Retire_first =
	     f_EX_Control_to_Retire_rv$port1__read[229] ;

  // action method fo_EX_Control_to_Retire_deq
  assign RDY_fo_EX_Control_to_Retire_deq =
	     f_EX_Control_to_Retire_rv$port1__read[229] ;
  assign CAN_FIRE_fo_EX_Control_to_Retire_deq =
	     f_EX_Control_to_Retire_rv$port1__read[229] ;
  assign WILL_FIRE_fo_EX_Control_to_Retire_deq =
	     EN_fo_EX_Control_to_Retire_deq ;

  // value method fo_EX_Control_to_Retire_notEmpty
  assign fo_EX_Control_to_Retire_notEmpty =
	     f_EX_Control_to_Retire_rv$port1__read[229] ;
  assign RDY_fo_EX_Control_to_Retire_notEmpty = 1'd1 ;

  // rule RL_rl_EX_Control
  assign CAN_FIRE_RL_rl_EX_Control =
	     f_RR_to_EX_Control_rv[256] && !f_EX_Control_to_Retire_rv[229] ;
  assign WILL_FIRE_RL_rl_EX_Control = CAN_FIRE_RL_rl_EX_Control ;

  // inlined wires
  assign f_RR_to_EX_Control_rv$port0__write_1 =
	     { 1'd0,
	       256'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign f_RR_to_EX_Control_rv$port1__read =
	     CAN_FIRE_RL_rl_EX_Control ?
	       f_RR_to_EX_Control_rv$port0__write_1 :
	       f_RR_to_EX_Control_rv ;
  assign f_RR_to_EX_Control_rv$port1__write_1 =
	     { 1'd1, fi_RR_to_EX_Control_enq_x } ;
  assign f_RR_to_EX_Control_rv$port2__read =
	     EN_fi_RR_to_EX_Control_enq ?
	       f_RR_to_EX_Control_rv$port1__write_1 :
	       f_RR_to_EX_Control_rv$port1__read ;
  assign f_EX_Control_to_Retire_rv$port0__write_1 =
	     { 1'd1,
	       IF_f_RR_to_EX_Control_rv_port0__read_BITS_166__ETC___d60,
	       4'd0,
	       next_pc__h1462,
	       next_pc__h1462,
	       f_RR_to_EX_Control_rv[223:192],
	       f_RR_to_EX_Control_rv[63:0],
	       f_RR_to_EX_Control_rv[255:224],
	       f_RR_to_EX_Control_rv[191:160] } ;
  assign f_EX_Control_to_Retire_rv$port1__read =
	     CAN_FIRE_RL_rl_EX_Control ?
	       f_EX_Control_to_Retire_rv$port0__write_1 :
	       f_EX_Control_to_Retire_rv ;
  assign f_EX_Control_to_Retire_rv$port1__write_1 =
	     { 1'd0,
	       229'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign f_EX_Control_to_Retire_rv$port2__read =
	     EN_fo_EX_Control_to_Retire_deq ?
	       f_EX_Control_to_Retire_rv$port1__write_1 :
	       f_EX_Control_to_Retire_rv$port1__read ;

  // register f_EX_Control_to_Retire_rv
  assign f_EX_Control_to_Retire_rv$D_IN =
	     f_EX_Control_to_Retire_rv$port2__read ;
  assign f_EX_Control_to_Retire_rv$EN = 1'b1 ;

  // register f_RR_to_EX_Control_rv
  assign f_RR_to_EX_Control_rv$D_IN = f_RR_to_EX_Control_rv$port2__read ;
  assign f_RR_to_EX_Control_rv$EN = 1'b1 ;

  // register rg_flog
  assign rg_flog$D_IN = init_initial_params[207:176] ;
  assign rg_flog$EN = EN_init ;

  // remaining internal signals
  assign NOT_rg_flog_7_EQ_0_8_9_AND_IF_f_RR_to_EX_Contr_ETC___d85 =
	     rg_flog != 32'd0 &&
	     CASE_f_RR_to_EX_Control_rv_BITS_166_TO_162_24__ETC__q1 ;
  assign f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d36 =
	     f_RR_to_EX_Control_rv[159:128] == f_RR_to_EX_Control_rv[127:96] ;
  assign f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d40 =
	     (f_RR_to_EX_Control_rv[159:128] ^ 32'h80000000) <
	     (f_RR_to_EX_Control_rv[127:96] ^ 32'h80000000) ;
  assign f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d44 =
	     f_RR_to_EX_Control_rv[159:128] < f_RR_to_EX_Control_rv[127:96] ;
  assign f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d56 =
	     f_RR_to_EX_Control_rv[159:128] + f_RR_to_EX_Control_rv[95:64] ;
  assign target_pc__h707 =
	     f_RR_to_EX_Control_rv[255:224] + f_RR_to_EX_Control_rv[95:64] ;
  assign y_avValue_snd__h1437 =
	     { f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d56[31:1],
	       1'd0 } ;
  assign y_avValue_snd__h1449 =
	     IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d50 ?
	       target_pc__h707 :
	       f_RR_to_EX_Control_rv[223:192] ;
  always@(f_RR_to_EX_Control_rv or
	  f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d44 or
	  f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d36 or
	  f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d40)
  begin
    case (f_RR_to_EX_Control_rv[174:172])
      3'b0:
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d50 =
	      f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d36;
      3'b001:
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d50 =
	      !f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d36;
      3'b100:
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d50 =
	      f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d40;
      3'b101:
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d50 =
	      !f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d40;
      3'b110:
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d50 =
	      f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d44;
      default: IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d50 =
		   !f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d44;
    endcase
  end
  always@(f_RR_to_EX_Control_rv or
	  y_avValue_snd__h1437 or y_avValue_snd__h1449 or target_pc__h707)
  begin
    case (f_RR_to_EX_Control_rv[166:162])
      5'd24: next_pc__h1462 = y_avValue_snd__h1449;
      5'd27: next_pc__h1462 = target_pc__h707;
      default: next_pc__h1462 = y_avValue_snd__h1437;
    endcase
  end
  always@(f_RR_to_EX_Control_rv or
	  f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d44 or
	  f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d36 or
	  f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d40)
  begin
    case (f_RR_to_EX_Control_rv[174:172])
      3'b0:
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d79 =
	      !f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d36;
      3'b001:
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d79 =
	      f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d36;
      3'b100:
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d79 =
	      !f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d40;
      3'b101:
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d79 =
	      f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d40;
      3'b110:
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d79 =
	      !f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d44;
      default: IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d79 =
		   f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d44;
    endcase
  end
  always@(f_RR_to_EX_Control_rv or
	  f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d56 or
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d50 or
	  target_pc__h707)
  begin
    case (f_RR_to_EX_Control_rv[166:162])
      5'd24:
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_166__ETC___d60 =
	      IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d50 &&
	      target_pc__h707[1:0] != 2'd0;
      5'd27:
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_166__ETC___d60 =
	      target_pc__h707[1:0] != 2'd0;
      default: IF_f_RR_to_EX_Control_rv_port0__read_BITS_166__ETC___d60 =
		   f_RR_to_EX_Control_rv[166:162] == 5'd25 &&
		   f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d56[1];
    endcase
  end
  always@(f_RR_to_EX_Control_rv or
	  f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d56 or
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d79 or
	  target_pc__h707)
  begin
    case (f_RR_to_EX_Control_rv[166:162])
      5'd24:
	  CASE_f_RR_to_EX_Control_rv_BITS_166_TO_162_24__ETC__q1 =
	      IF_f_RR_to_EX_Control_rv_port0__read_BITS_174__ETC___d79 ||
	      target_pc__h707[1:0] == 2'd0;
      5'd27:
	  CASE_f_RR_to_EX_Control_rv_BITS_166_TO_162_24__ETC__q1 =
	      target_pc__h707[1:0] == 2'd0;
      default: CASE_f_RR_to_EX_Control_rv_BITS_166_TO_162_24__ETC__q1 =
		   f_RR_to_EX_Control_rv[166:162] != 5'd25 ||
		   !f_RR_to_EX_Control_rv_port0__read_BITS_159_TO__ETC___d56[1];
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        f_EX_Control_to_Retire_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0,
	      229'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
	f_RR_to_EX_Control_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0,
	      256'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
	rg_flog <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (f_EX_Control_to_Retire_rv$EN)
	  f_EX_Control_to_Retire_rv <= `BSV_ASSIGNMENT_DELAY
	      f_EX_Control_to_Retire_rv$D_IN;
	if (f_RR_to_EX_Control_rv$EN)
	  f_RR_to_EX_Control_rv <= `BSV_ASSIGNMENT_DELAY
	      f_RR_to_EX_Control_rv$D_IN;
	if (rg_flog$EN) rg_flog <= `BSV_ASSIGNMENT_DELAY rg_flog$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    f_EX_Control_to_Retire_rv =
	230'h2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    f_RR_to_EX_Control_rv =
	257'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    rg_flog = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	begin
	  v__h996 = $stime;
	  #0;
	end
    x__h1029 = v__h996 + 32'd5;
    v__h988 = x__h1029 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h988);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "IMPOSSIBLE: fn_EX_Control");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "RR_to_EX_Control { ", "pc: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "'h%h", f_RR_to_EX_Control_rv[255:224]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, ", ", "fallthru_pc: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "'h%h", f_RR_to_EX_Control_rv[223:192]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, ", ", "instr: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "'h%h", f_RR_to_EX_Control_rv[191:160]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, ", ", "rs1_val: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "'h%h", f_RR_to_EX_Control_rv[159:128]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, ", ", "rs2_val: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "'h%h", f_RR_to_EX_Control_rv[127:96]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, ", ", "imm: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "'h%h", f_RR_to_EX_Control_rv[95:64]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, ", ", "xtra: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "RR_to_EX_Control_Xtra { ", "inum: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "'h%h", f_RR_to_EX_Control_rv[63:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25 &&
	  rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	begin
	  v__h1289 = $stime;
	  #0;
	end
    x__h1322 = v__h1289 + 32'd5;
    v__h1281 = x__h1322 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write("%0d: ", v__h1281);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write("IMPOSSIBLE: fn_EX_Control");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write("RR_to_EX_Control { ", "pc: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write("'h%h", f_RR_to_EX_Control_rv[255:224]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write(", ", "fallthru_pc: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write("'h%h", f_RR_to_EX_Control_rv[223:192]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write(", ", "instr: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write("'h%h", f_RR_to_EX_Control_rv[191:160]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write(", ", "rs1_val: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write("'h%h", f_RR_to_EX_Control_rv[159:128]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write(", ", "rs2_val: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write("'h%h", f_RR_to_EX_Control_rv[127:96]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write(", ", "imm: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write("'h%h", f_RR_to_EX_Control_rv[95:64]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write(", ", "xtra: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write("RR_to_EX_Control_Xtra { ", "inum: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write("'h%h", f_RR_to_EX_Control_rv[63:0], " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write(" }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd24 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd27 &&
	  f_RR_to_EX_Control_rv[166:162] != 5'd25)
	$finish(32'd1);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	begin
	  v__h1923 = $stime;
	  #0;
	end
    x__h1956 = v__h1923 + 32'd5;
    v__h1915 = x__h1956 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h1915);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, "CPU.EX_Control");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, "    ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog,
		"    RR_to_EX_Control{",
		"I_%0d",
		f_RR_to_EX_Control_rv[63:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, " pc:%08h", f_RR_to_EX_Control_rv[255:224]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, " instr:%08h", f_RR_to_EX_Control_rv[191:160]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, " fallthru:%08h\n", f_RR_to_EX_Control_rv[223:192]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, "                  ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, "rs1_val:%08h ", f_RR_to_EX_Control_rv[159:128]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, " rs2_val:%08h ", f_RR_to_EX_Control_rv[127:96]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, " imm:%08h ", f_RR_to_EX_Control_rv[95:64]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, "}");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, "    ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0 &&
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_166__ETC___d60)
	$fwrite(rg_flog,
		"    EX_Control_to_Retire{",
		"I_%0d",
		f_RR_to_EX_Control_rv[63:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  NOT_rg_flog_7_EQ_0_8_9_AND_IF_f_RR_to_EX_Contr_ETC___d85)
	$fwrite(rg_flog,
		"    EX_Control_to_Retire{",
		"I_%0d",
		f_RR_to_EX_Control_rv[63:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0 &&
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_166__ETC___d60)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  NOT_rg_flog_7_EQ_0_8_9_AND_IF_f_RR_to_EX_Contr_ETC___d85)
	$fwrite(rg_flog, " pc:%08h", f_RR_to_EX_Control_rv[255:224]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0 &&
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_166__ETC___d60)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  NOT_rg_flog_7_EQ_0_8_9_AND_IF_f_RR_to_EX_Contr_ETC___d85)
	$fwrite(rg_flog, " instr:%08h\n", f_RR_to_EX_Control_rv[191:160]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0 &&
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_166__ETC___d60)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  NOT_rg_flog_7_EQ_0_8_9_AND_IF_f_RR_to_EX_Contr_ETC___d85)
	$fwrite(rg_flog, "                      ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0 &&
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_166__ETC___d60)
	$fwrite(rg_flog, " pc:%08h", f_RR_to_EX_Control_rv[255:224]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  NOT_rg_flog_7_EQ_0_8_9_AND_IF_f_RR_to_EX_Contr_ETC___d85)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0 &&
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_166__ETC___d60)
	$fwrite(rg_flog, " instr:%08h\n", f_RR_to_EX_Control_rv[191:160]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  NOT_rg_flog_7_EQ_0_8_9_AND_IF_f_RR_to_EX_Contr_ETC___d85)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0 &&
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_166__ETC___d60)
	$fwrite(rg_flog, "                      ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  NOT_rg_flog_7_EQ_0_8_9_AND_IF_f_RR_to_EX_Contr_ETC___d85)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0 &&
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_166__ETC___d60)
	$fwrite(rg_flog, " ", "INSTR_ADDR_MISALIGNED");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  NOT_rg_flog_7_EQ_0_8_9_AND_IF_f_RR_to_EX_Contr_ETC___d85)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0 &&
	  IF_f_RR_to_EX_Control_rv_port0__read_BITS_166__ETC___d60)
	$fwrite(rg_flog, " tval:%0h", next_pc__h1462);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control &&
	  NOT_rg_flog_7_EQ_0_8_9_AND_IF_f_RR_to_EX_Contr_ETC___d85)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, " next_pc:%08h ", next_pc__h1462);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, " data:%08h", f_RR_to_EX_Control_rv[223:192]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, "}");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	begin
	  v__h2481 = $stime;
	  #0;
	end
    x__h2514 = v__h2481 + 32'd5;
    v__h2473 = x__h2514 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog,
		"Trace %0d %0d %08h %08h %s",
		v__h2473,
		f_RR_to_EX_Control_rv[63:0],
		f_RR_to_EX_Control_rv[255:224],
		f_RR_to_EX_Control_rv[191:160],
		"EX.C");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Control && rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
  end
  // synopsys translate_on
endmodule  // mkEX_Control

