//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:58 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_init                       O     1 const
// RDY_fi_RR_to_EX_Posit_enq      O     1
// fi_RR_to_EX_Posit_notFull      O     1
// RDY_fi_RR_to_EX_Posit_notFull  O     1 const
// fo_EX_Posit_to_Retire_first    O   197
// RDY_fo_EX_Posit_to_Retire_first  O     1
// RDY_fo_EX_Posit_to_Retire_deq  O     1
// fo_EX_Posit_to_Retire_notEmpty  O     1
// RDY_fo_EX_Posit_to_Retire_notEmpty  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// init_initial_params            I   208 reg
// fi_RR_to_EX_Posit_enq_x        I   224
// EN_init                        I     1
// EN_fi_RR_to_EX_Posit_enq       I     1
// EN_fo_EX_Posit_to_Retire_deq   I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkEX_Posit(CLK,
		  RST_N,

		  init_initial_params,
		  EN_init,
		  RDY_init,

		  fi_RR_to_EX_Posit_enq_x,
		  EN_fi_RR_to_EX_Posit_enq,
		  RDY_fi_RR_to_EX_Posit_enq,

		  fi_RR_to_EX_Posit_notFull,
		  RDY_fi_RR_to_EX_Posit_notFull,

		  fo_EX_Posit_to_Retire_first,
		  RDY_fo_EX_Posit_to_Retire_first,

		  EN_fo_EX_Posit_to_Retire_deq,
		  RDY_fo_EX_Posit_to_Retire_deq,

		  fo_EX_Posit_to_Retire_notEmpty,
		  RDY_fo_EX_Posit_to_Retire_notEmpty);
  input  CLK;
  input  RST_N;

  // action method init
  input  [207 : 0] init_initial_params;
  input  EN_init;
  output RDY_init;

  // action method fi_RR_to_EX_Posit_enq
  input  [223 : 0] fi_RR_to_EX_Posit_enq_x;
  input  EN_fi_RR_to_EX_Posit_enq;
  output RDY_fi_RR_to_EX_Posit_enq;

  // value method fi_RR_to_EX_Posit_notFull
  output fi_RR_to_EX_Posit_notFull;
  output RDY_fi_RR_to_EX_Posit_notFull;

  // value method fo_EX_Posit_to_Retire_first
  output [196 : 0] fo_EX_Posit_to_Retire_first;
  output RDY_fo_EX_Posit_to_Retire_first;

  // action method fo_EX_Posit_to_Retire_deq
  input  EN_fo_EX_Posit_to_Retire_deq;
  output RDY_fo_EX_Posit_to_Retire_deq;

  // value method fo_EX_Posit_to_Retire_notEmpty
  output fo_EX_Posit_to_Retire_notEmpty;
  output RDY_fo_EX_Posit_to_Retire_notEmpty;

  // signals for module outputs
  wire [196 : 0] fo_EX_Posit_to_Retire_first;
  wire RDY_fi_RR_to_EX_Posit_enq,
       RDY_fi_RR_to_EX_Posit_notFull,
       RDY_fo_EX_Posit_to_Retire_deq,
       RDY_fo_EX_Posit_to_Retire_first,
       RDY_fo_EX_Posit_to_Retire_notEmpty,
       RDY_init,
       fi_RR_to_EX_Posit_notFull,
       fo_EX_Posit_to_Retire_notEmpty;

  // inlined wires
  wire [224 : 0] f_RR_to_EX_Posit_rv$port0__write_1,
		 f_RR_to_EX_Posit_rv$port1__read,
		 f_RR_to_EX_Posit_rv$port1__write_1,
		 f_RR_to_EX_Posit_rv$port2__read;
  wire [197 : 0] f_EX_Posit_to_Retire_rv$port0__write_1,
		 f_EX_Posit_to_Retire_rv$port1__read,
		 f_EX_Posit_to_Retire_rv$port1__write_1,
		 f_EX_Posit_to_Retire_rv$port2__read;
  wire f_EX_Posit_to_Retire_rv$EN_port0__write,
       f_RR_to_EX_Posit_rv$EN_port0__write;

  // register f_EX_Posit_to_Retire_rv
  reg [197 : 0] f_EX_Posit_to_Retire_rv;
  wire [197 : 0] f_EX_Posit_to_Retire_rv$D_IN;
  wire f_EX_Posit_to_Retire_rv$EN;

  // register f_RR_to_EX_Posit_rv
  reg [224 : 0] f_RR_to_EX_Posit_rv;
  wire [224 : 0] f_RR_to_EX_Posit_rv$D_IN;
  wire f_RR_to_EX_Posit_rv$EN;

  // register rg_flog
  reg [31 : 0] rg_flog;
  wire [31 : 0] rg_flog$D_IN;
  wire rg_flog$EN;

  // ports of submodule f_pending
  wire [223 : 0] f_pending$D_IN, f_pending$D_OUT;
  wire f_pending$CLR,
       f_pending$DEQ,
       f_pending$EMPTY_N,
       f_pending$ENQ,
       f_pending$FULL_N;

  // ports of submodule posit_core
  wire [137 : 0] posit_core$server_core_request_put;
  wire [70 : 0] posit_core$server_core_response_get;
  wire posit_core$EN_server_core_request_put,
       posit_core$EN_server_core_response_get,
       posit_core$RDY_server_core_request_put,
       posit_core$RDY_server_core_response_get;

  // rule scheduling signals
  wire CAN_FIRE_RL_rl_EX_Posit_collect,
       CAN_FIRE_RL_rl_EX_Posit_issue,
       CAN_FIRE_fi_RR_to_EX_Posit_enq,
       CAN_FIRE_fo_EX_Posit_to_Retire_deq,
       CAN_FIRE_init,
       WILL_FIRE_RL_rl_EX_Posit_collect,
       WILL_FIRE_RL_rl_EX_Posit_issue,
       WILL_FIRE_fi_RR_to_EX_Posit_enq,
       WILL_FIRE_fo_EX_Posit_to_Retire_deq,
       WILL_FIRE_init;

  // declarations used by system tasks
  // synopsys translate_off
  reg [31 : 0] v__h1258;
  reg [31 : 0] x__h1291;
  reg [31 : 0] v__h1250;
  // synopsys translate_on

  // remaining internal signals
  reg [31 : 0] y_avValue_snd__h2104;
  wire [31 : 0] x__h2244;
  wire NOT_f_EX_Posit_to_Retire_rv_port0__read__4_BIT_ETC___d87;

  // action method init
  assign RDY_init = 1'd1 ;
  assign CAN_FIRE_init = 1'd1 ;
  assign WILL_FIRE_init = EN_init ;

  // action method fi_RR_to_EX_Posit_enq
  assign RDY_fi_RR_to_EX_Posit_enq = !f_RR_to_EX_Posit_rv$port1__read[224] ;
  assign CAN_FIRE_fi_RR_to_EX_Posit_enq =
	     !f_RR_to_EX_Posit_rv$port1__read[224] ;
  assign WILL_FIRE_fi_RR_to_EX_Posit_enq = EN_fi_RR_to_EX_Posit_enq ;

  // value method fi_RR_to_EX_Posit_notFull
  assign fi_RR_to_EX_Posit_notFull = !f_RR_to_EX_Posit_rv$port1__read[224] ;
  assign RDY_fi_RR_to_EX_Posit_notFull = 1'd1 ;

  // value method fo_EX_Posit_to_Retire_first
  assign fo_EX_Posit_to_Retire_first =
	     f_EX_Posit_to_Retire_rv$port1__read[196:0] ;
  assign RDY_fo_EX_Posit_to_Retire_first =
	     f_EX_Posit_to_Retire_rv$port1__read[197] ;

  // action method fo_EX_Posit_to_Retire_deq
  assign RDY_fo_EX_Posit_to_Retire_deq =
	     f_EX_Posit_to_Retire_rv$port1__read[197] ;
  assign CAN_FIRE_fo_EX_Posit_to_Retire_deq =
	     f_EX_Posit_to_Retire_rv$port1__read[197] ;
  assign WILL_FIRE_fo_EX_Posit_to_Retire_deq = EN_fo_EX_Posit_to_Retire_deq ;

  // value method fo_EX_Posit_to_Retire_notEmpty
  assign fo_EX_Posit_to_Retire_notEmpty =
	     f_EX_Posit_to_Retire_rv$port1__read[197] ;
  assign RDY_fo_EX_Posit_to_Retire_notEmpty = 1'd1 ;

  // submodule f_pending
  SizedFIFO #(.p1width(32'd224),
	      .p2depth(32'd4),
	      .p3cntr_width(32'd2),
	      .guarded(1'd1)) f_pending(.RST(RST_N),
					.CLK(CLK),
					.D_IN(f_pending$D_IN),
					.ENQ(f_pending$ENQ),
					.DEQ(f_pending$DEQ),
					.CLR(f_pending$CLR),
					.D_OUT(f_pending$D_OUT),
					.FULL_N(f_pending$FULL_N),
					.EMPTY_N(f_pending$EMPTY_N));

  // submodule posit_core
  mkPositCore posit_core(.CLK(CLK),
			 .RST_N(RST_N),
			 .server_core_request_put(posit_core$server_core_request_put),
			 .EN_server_core_request_put(posit_core$EN_server_core_request_put),
			 .EN_server_core_response_get(posit_core$EN_server_core_response_get),
			 .RDY_server_core_request_put(posit_core$RDY_server_core_request_put),
			 .server_core_response_get(posit_core$server_core_response_get),
			 .RDY_server_core_response_get(posit_core$RDY_server_core_response_get));

  // rule RL_rl_EX_Posit_issue
  assign CAN_FIRE_RL_rl_EX_Posit_issue =
	     f_RR_to_EX_Posit_rv[224] &&
	     posit_core$RDY_server_core_request_put &&
	     f_pending$FULL_N ;
  assign WILL_FIRE_RL_rl_EX_Posit_issue = CAN_FIRE_RL_rl_EX_Posit_issue ;

  // rule RL_rl_EX_Posit_collect
  assign CAN_FIRE_RL_rl_EX_Posit_collect =
	     f_pending$EMPTY_N &&
	     NOT_f_EX_Posit_to_Retire_rv_port0__read__4_BIT_ETC___d87 ;
  assign WILL_FIRE_RL_rl_EX_Posit_collect = CAN_FIRE_RL_rl_EX_Posit_collect ;

  // inlined wires
  assign f_RR_to_EX_Posit_rv$EN_port0__write =
	     f_RR_to_EX_Posit_rv[224] &&
	     posit_core$RDY_server_core_request_put &&
	     f_pending$FULL_N ;
  assign f_RR_to_EX_Posit_rv$port0__write_1 =
	     { 1'd0,
	       224'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign f_RR_to_EX_Posit_rv$port1__read =
	     f_RR_to_EX_Posit_rv$EN_port0__write ?
	       f_RR_to_EX_Posit_rv$port0__write_1 :
	       f_RR_to_EX_Posit_rv ;
  assign f_RR_to_EX_Posit_rv$port1__write_1 =
	     { 1'd1, fi_RR_to_EX_Posit_enq_x } ;
  assign f_RR_to_EX_Posit_rv$port2__read =
	     EN_fi_RR_to_EX_Posit_enq ?
	       f_RR_to_EX_Posit_rv$port1__write_1 :
	       f_RR_to_EX_Posit_rv$port1__read ;
  assign f_EX_Posit_to_Retire_rv$EN_port0__write =
	     f_pending$EMPTY_N &&
	     NOT_f_EX_Posit_to_Retire_rv_port0__read__4_BIT_ETC___d87 ;
  assign f_EX_Posit_to_Retire_rv$port0__write_1 =
	     { 1'd1,
	       f_pending$D_OUT[198:192] == 7'b0001011 &&
	       f_pending$D_OUT[206:204] == 3'b0 &&
	       (f_pending$D_OUT[223:217] == 7'b0000010 ||
		f_pending$D_OUT[223:217] == 7'b0000100 ||
		f_pending$D_OUT[223:217] == 7'b0000101) &&
	       (posit_core$server_core_response_get[4] ||
		posit_core$server_core_response_get[3]),
	       4'd2,
	       f_pending$D_OUT[223:192],
	       x__h2244,
	       f_pending$D_OUT[95:0],
	       32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign f_EX_Posit_to_Retire_rv$port1__read =
	     f_EX_Posit_to_Retire_rv$EN_port0__write ?
	       f_EX_Posit_to_Retire_rv$port0__write_1 :
	       f_EX_Posit_to_Retire_rv ;
  assign f_EX_Posit_to_Retire_rv$port1__write_1 =
	     { 1'd0,
	       197'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign f_EX_Posit_to_Retire_rv$port2__read =
	     EN_fo_EX_Posit_to_Retire_deq ?
	       f_EX_Posit_to_Retire_rv$port1__write_1 :
	       f_EX_Posit_to_Retire_rv$port1__read ;

  // register f_EX_Posit_to_Retire_rv
  assign f_EX_Posit_to_Retire_rv$D_IN = f_EX_Posit_to_Retire_rv$port2__read ;
  assign f_EX_Posit_to_Retire_rv$EN = 1'b1 ;

  // register f_RR_to_EX_Posit_rv
  assign f_RR_to_EX_Posit_rv$D_IN = f_RR_to_EX_Posit_rv$port2__read ;
  assign f_RR_to_EX_Posit_rv$EN = 1'b1 ;

  // register rg_flog
  assign rg_flog$D_IN = init_initial_params[207:176] ;
  assign rg_flog$EN = EN_init ;

  // submodule f_pending
  assign f_pending$D_IN = f_RR_to_EX_Posit_rv[223:0] ;
  assign f_pending$ENQ = CAN_FIRE_RL_rl_EX_Posit_issue ;
  assign f_pending$DEQ = CAN_FIRE_RL_rl_EX_Posit_collect ;
  assign f_pending$CLR = 1'b0 ;

  // submodule posit_core
  assign posit_core$server_core_request_put =
	     { (f_RR_to_EX_Posit_rv[198:192] == 7'b0001011 &&
		f_RR_to_EX_Posit_rv[206:204] == 3'b0 &&
		f_RR_to_EX_Posit_rv[223:217] == 7'b0000100) ?
		 { 2'd1, f_RR_to_EX_Posit_rv[223:160] } :
		 { 2'd2,
		   32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ,
		   (f_RR_to_EX_Posit_rv[198:192] == 7'b0001011 &&
		    f_RR_to_EX_Posit_rv[206:204] == 3'b0 &&
		    f_RR_to_EX_Posit_rv[223:217] == 7'b0000011) ?
		     32'd0 :
		     f_RR_to_EX_Posit_rv[191:160] },
	       2'd2,
	       32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ,
	       (f_RR_to_EX_Posit_rv[198:192] == 7'b0001011 &&
		f_RR_to_EX_Posit_rv[206:204] == 3'b0 &&
		f_RR_to_EX_Posit_rv[223:217] == 7'b0000011) ?
		 32'd0 :
		 f_RR_to_EX_Posit_rv[159:128],
	       3'd0,
	       (f_RR_to_EX_Posit_rv[198:192] == 7'b0001011 &&
		f_RR_to_EX_Posit_rv[206:204] == 3'b0 &&
		f_RR_to_EX_Posit_rv[223:217] == 7'b0) ?
		 3'd0 :
		 ((f_RR_to_EX_Posit_rv[198:192] == 7'b0001011 &&
		   f_RR_to_EX_Posit_rv[206:204] == 3'b0 &&
		   f_RR_to_EX_Posit_rv[223:217] == 7'b0000001) ?
		    3'd1 :
		    ((f_RR_to_EX_Posit_rv[198:192] == 7'b0001011 &&
		      f_RR_to_EX_Posit_rv[206:204] == 3'b0 &&
		      f_RR_to_EX_Posit_rv[223:217] == 7'b0000010) ?
		       3'd4 :
		       ((f_RR_to_EX_Posit_rv[198:192] == 7'b0001011 &&
			 f_RR_to_EX_Posit_rv[206:204] == 3'b0 &&
			 f_RR_to_EX_Posit_rv[223:217] == 7'b0000011) ?
			  3'd5 :
			  ((f_RR_to_EX_Posit_rv[198:192] == 7'b0001011 &&
			    f_RR_to_EX_Posit_rv[206:204] == 3'b0 &&
			    f_RR_to_EX_Posit_rv[223:217] == 7'b0000100) ?
			     3'd2 :
			     ((f_RR_to_EX_Posit_rv[198:192] == 7'b0001011 &&
			       f_RR_to_EX_Posit_rv[206:204] == 3'b0 &&
			       f_RR_to_EX_Posit_rv[223:217] == 7'b0000101) ?
				3'd3 :
				3'd0))))) } ;
  assign posit_core$EN_server_core_request_put =
	     CAN_FIRE_RL_rl_EX_Posit_issue ;
  assign posit_core$EN_server_core_response_get =
	     WILL_FIRE_RL_rl_EX_Posit_collect &&
	     f_pending$D_OUT[198:192] == 7'b0001011 &&
	     f_pending$D_OUT[206:204] == 3'b0 &&
	     (f_pending$D_OUT[223:217] == 7'b0000010 ||
	      f_pending$D_OUT[223:217] == 7'b0000100 ||
	      f_pending$D_OUT[223:217] == 7'b0000101) ;

  // remaining internal signals
  assign NOT_f_EX_Posit_to_Retire_rv_port0__read__4_BIT_ETC___d87 =
	     !f_EX_Posit_to_Retire_rv[197] &&
	     (f_pending$D_OUT[198:192] != 7'b0001011 ||
	      f_pending$D_OUT[206:204] != 3'b0 ||
	      f_pending$D_OUT[223:217] != 7'b0000010 &&
	      f_pending$D_OUT[223:217] != 7'b0000100 &&
	      f_pending$D_OUT[223:217] != 7'b0000101 ||
	      posit_core$RDY_server_core_response_get) ;
  assign x__h2244 =
	     (f_pending$D_OUT[198:192] == 7'b0001011 &&
	      f_pending$D_OUT[206:204] == 3'b0 &&
	      (f_pending$D_OUT[223:217] == 7'b0000010 ||
	       f_pending$D_OUT[223:217] == 7'b0000100 ||
	       f_pending$D_OUT[223:217] == 7'b0000101)) ?
	       y_avValue_snd__h2104 :
	       32'd0 ;
  always@(posit_core$server_core_response_get)
  begin
    case (posit_core$server_core_response_get[70:69])
      2'd1, 2'd2:
	  y_avValue_snd__h2104 = posit_core$server_core_response_get[36:5];
      default: y_avValue_snd__h2104 = 32'd0;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        f_EX_Posit_to_Retire_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0,
	      197'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
	f_RR_to_EX_Posit_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0,
	      224'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
	rg_flog <= `BSV_ASSIGNMENT_DELAY 32'd0;
      end
    else
      begin
        if (f_EX_Posit_to_Retire_rv$EN)
	  f_EX_Posit_to_Retire_rv <= `BSV_ASSIGNMENT_DELAY
	      f_EX_Posit_to_Retire_rv$D_IN;
	if (f_RR_to_EX_Posit_rv$EN)
	  f_RR_to_EX_Posit_rv <= `BSV_ASSIGNMENT_DELAY
	      f_RR_to_EX_Posit_rv$D_IN;
	if (rg_flog$EN) rg_flog <= `BSV_ASSIGNMENT_DELAY rg_flog$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    f_EX_Posit_to_Retire_rv =
	198'h2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    f_RR_to_EX_Posit_rv =
	225'h0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    rg_flog = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Posit_issue &&
	  (f_RR_to_EX_Posit_rv[198:192] != 7'b0001011 ||
	   f_RR_to_EX_Posit_rv[206:204] != 3'b0 ||
	   f_RR_to_EX_Posit_rv[223:217] != 7'b0 &&
	   f_RR_to_EX_Posit_rv[223:217] != 7'b0000001 &&
	   f_RR_to_EX_Posit_rv[223:217] != 7'b0000010 &&
	   f_RR_to_EX_Posit_rv[223:217] != 7'b0000011 &&
	   f_RR_to_EX_Posit_rv[223:217] != 7'b0000100 &&
	   f_RR_to_EX_Posit_rv[223:217] != 7'b0000101))
	begin
	  v__h1258 = $stime;
	  #0;
	end
    x__h1291 = v__h1258 + 32'd5;
    v__h1250 = x__h1291 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_EX_Posit_issue &&
	  (f_RR_to_EX_Posit_rv[198:192] != 7'b0001011 ||
	   f_RR_to_EX_Posit_rv[206:204] != 3'b0 ||
	   f_RR_to_EX_Posit_rv[223:217] != 7'b0 &&
	   f_RR_to_EX_Posit_rv[223:217] != 7'b0000001 &&
	   f_RR_to_EX_Posit_rv[223:217] != 7'b0000010 &&
	   f_RR_to_EX_Posit_rv[223:217] != 7'b0000011 &&
	   f_RR_to_EX_Posit_rv[223:217] != 7'b0000100 &&
	   f_RR_to_EX_Posit_rv[223:217] != 7'b0000101))
	$display("%0d: S4_EX_Posit: ERROR: unknown posit instr %08h",
		 v__h1250,
		 f_RR_to_EX_Posit_rv[223:192]);
  end
  // synopsys translate_on
endmodule  // mkEX_Posit

