//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:39 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_init                       O     1 reg
// fo_Fetch_to_Decode_first       O   131
// RDY_fo_Fetch_to_Decode_first   O     1
// RDY_fo_Fetch_to_Decode_deq     O     1
// fo_Fetch_to_Decode_notEmpty    O     1
// RDY_fo_Fetch_to_Decode_notEmpty  O     1 const
// fo_Fetch_to_IMem_first         O   265
// RDY_fo_Fetch_to_IMem_first     O     1
// RDY_fo_Fetch_to_IMem_deq       O     1
// fo_Fetch_to_IMem_notEmpty      O     1
// RDY_fo_Fetch_to_IMem_notEmpty  O     1 const
// RDY_fi_Fetch_from_Retire_enq   O     1
// fi_Fetch_from_Retire_notFull   O     1
// RDY_fi_Fetch_from_Retire_notFull  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// init_initial_params            I   208
// fi_Fetch_from_Retire_enq_x     I   163
// EN_init                        I     1
// EN_fo_Fetch_to_Decode_deq      I     1
// EN_fo_Fetch_to_IMem_deq        I     1
// EN_fi_Fetch_from_Retire_enq    I     1
//
// Combinational paths from inputs to outputs:
//   EN_init -> fo_Fetch_to_Decode_first
//   EN_init -> RDY_fo_Fetch_to_Decode_first
//   EN_init -> RDY_fo_Fetch_to_Decode_deq
//   EN_init -> fo_Fetch_to_Decode_notEmpty
//   EN_init -> RDY_fi_Fetch_from_Retire_enq
//   EN_init -> fi_Fetch_from_Retire_notFull
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFetch(CLK,
	       RST_N,

	       init_initial_params,
	       EN_init,
	       RDY_init,

	       fo_Fetch_to_Decode_first,
	       RDY_fo_Fetch_to_Decode_first,

	       EN_fo_Fetch_to_Decode_deq,
	       RDY_fo_Fetch_to_Decode_deq,

	       fo_Fetch_to_Decode_notEmpty,
	       RDY_fo_Fetch_to_Decode_notEmpty,

	       fo_Fetch_to_IMem_first,
	       RDY_fo_Fetch_to_IMem_first,

	       EN_fo_Fetch_to_IMem_deq,
	       RDY_fo_Fetch_to_IMem_deq,

	       fo_Fetch_to_IMem_notEmpty,
	       RDY_fo_Fetch_to_IMem_notEmpty,

	       fi_Fetch_from_Retire_enq_x,
	       EN_fi_Fetch_from_Retire_enq,
	       RDY_fi_Fetch_from_Retire_enq,

	       fi_Fetch_from_Retire_notFull,
	       RDY_fi_Fetch_from_Retire_notFull);
  input  CLK;
  input  RST_N;

  // action method init
  input  [207 : 0] init_initial_params;
  input  EN_init;
  output RDY_init;

  // value method fo_Fetch_to_Decode_first
  output [130 : 0] fo_Fetch_to_Decode_first;
  output RDY_fo_Fetch_to_Decode_first;

  // action method fo_Fetch_to_Decode_deq
  input  EN_fo_Fetch_to_Decode_deq;
  output RDY_fo_Fetch_to_Decode_deq;

  // value method fo_Fetch_to_Decode_notEmpty
  output fo_Fetch_to_Decode_notEmpty;
  output RDY_fo_Fetch_to_Decode_notEmpty;

  // value method fo_Fetch_to_IMem_first
  output [264 : 0] fo_Fetch_to_IMem_first;
  output RDY_fo_Fetch_to_IMem_first;

  // action method fo_Fetch_to_IMem_deq
  input  EN_fo_Fetch_to_IMem_deq;
  output RDY_fo_Fetch_to_IMem_deq;

  // value method fo_Fetch_to_IMem_notEmpty
  output fo_Fetch_to_IMem_notEmpty;
  output RDY_fo_Fetch_to_IMem_notEmpty;

  // action method fi_Fetch_from_Retire_enq
  input  [162 : 0] fi_Fetch_from_Retire_enq_x;
  input  EN_fi_Fetch_from_Retire_enq;
  output RDY_fi_Fetch_from_Retire_enq;

  // value method fi_Fetch_from_Retire_notFull
  output fi_Fetch_from_Retire_notFull;
  output RDY_fi_Fetch_from_Retire_notFull;

  // signals for module outputs
  wire [264 : 0] fo_Fetch_to_IMem_first;
  wire [130 : 0] fo_Fetch_to_Decode_first;
  wire RDY_fi_Fetch_from_Retire_enq,
       RDY_fi_Fetch_from_Retire_notFull,
       RDY_fo_Fetch_to_Decode_deq,
       RDY_fo_Fetch_to_Decode_first,
       RDY_fo_Fetch_to_Decode_notEmpty,
       RDY_fo_Fetch_to_IMem_deq,
       RDY_fo_Fetch_to_IMem_first,
       RDY_fo_Fetch_to_IMem_notEmpty,
       RDY_init,
       fi_Fetch_from_Retire_notFull,
       fo_Fetch_to_Decode_notEmpty,
       fo_Fetch_to_IMem_notEmpty;

  // inlined wires
  wire [265 : 0] f_Fetch_to_IMem_rv$port0__write_1,
		 f_Fetch_to_IMem_rv$port1__read,
		 f_Fetch_to_IMem_rv$port1__write_1,
		 f_Fetch_to_IMem_rv$port2__read;
  wire [163 : 0] f_Fetch_from_Retire_rv$port0__write_1,
		 f_Fetch_from_Retire_rv$port1__read,
		 f_Fetch_from_Retire_rv$port1__write_1,
		 f_Fetch_from_Retire_rv$port2__read;
  wire [131 : 0] f_Fetch_to_Decode_rv$port0__write_1,
		 f_Fetch_to_Decode_rv$port1__read,
		 f_Fetch_to_Decode_rv$port1__write_1,
		 f_Fetch_to_Decode_rv$port2__read;
  wire f_Fetch_to_Decode_rv$EN_port0__write;

  // register f_Fetch_from_Retire_rv
  reg [163 : 0] f_Fetch_from_Retire_rv;
  wire [163 : 0] f_Fetch_from_Retire_rv$D_IN;
  wire f_Fetch_from_Retire_rv$EN;

  // register f_Fetch_to_Decode_rv
  reg [131 : 0] f_Fetch_to_Decode_rv;
  wire [131 : 0] f_Fetch_to_Decode_rv$D_IN;
  wire f_Fetch_to_Decode_rv$EN;

  // register f_Fetch_to_IMem_rv
  reg [265 : 0] f_Fetch_to_IMem_rv;
  wire [265 : 0] f_Fetch_to_IMem_rv$D_IN;
  wire f_Fetch_to_IMem_rv$EN;

  // register rg_arch_inum
  reg [63 : 0] rg_arch_inum;
  wire [63 : 0] rg_arch_inum$D_IN;
  wire rg_arch_inum$EN;

  // register rg_epoch
  reg [1 : 0] rg_epoch;
  wire [1 : 0] rg_epoch$D_IN;
  wire rg_epoch$EN;

  // register rg_flog
  reg [31 : 0] rg_flog;
  wire [31 : 0] rg_flog$D_IN;
  wire rg_flog$EN;

  // register rg_inum
  reg [63 : 0] rg_inum;
  wire [63 : 0] rg_inum$D_IN;
  wire rg_inum$EN;

  // register rg_oiaat
  reg rg_oiaat;
  wire rg_oiaat$D_IN, rg_oiaat$EN;

  // register rg_oiaat_fetch
  reg rg_oiaat_fetch;
  wire rg_oiaat_fetch$D_IN, rg_oiaat_fetch$EN;

  // register rg_pc
  reg [31 : 0] rg_pc;
  reg [31 : 0] rg_pc$D_IN;
  wire rg_pc$EN;

  // register rg_runstate
  reg rg_runstate;
  wire rg_runstate$D_IN, rg_runstate$EN;

  // rule scheduling signals
  wire CAN_FIRE_RL_rl_Fetch_from_Retire,
       CAN_FIRE_RL_rl_Fetch_req,
       CAN_FIRE_fi_Fetch_from_Retire_enq,
       CAN_FIRE_fo_Fetch_to_Decode_deq,
       CAN_FIRE_fo_Fetch_to_IMem_deq,
       CAN_FIRE_init,
       WILL_FIRE_RL_rl_Fetch_from_Retire,
       WILL_FIRE_RL_rl_Fetch_req,
       WILL_FIRE_fi_Fetch_from_Retire_enq,
       WILL_FIRE_fo_Fetch_to_Decode_deq,
       WILL_FIRE_fo_Fetch_to_IMem_deq,
       WILL_FIRE_init;

  // inputs to muxes for submodule ports
  wire [131 : 0] MUX_f_Fetch_to_Decode_rv$port0__write_1__VAL_1,
		 MUX_f_Fetch_to_Decode_rv$port0__write_1__VAL_2;
  wire [63 : 0] MUX_rg_arch_inum$write_1__VAL_1,
		MUX_rg_arch_inum$write_1__VAL_2;
  wire MUX_f_Fetch_to_Decode_rv$port0__write_1__SEL_1,
       MUX_rg_oiaat_fetch$write_1__SEL_1,
       MUX_rg_runstate$write_1__SEL_1;

  // declarations used by system tasks
  // synopsys translate_off
  reg [31 : 0] v__h1521;
  reg [31 : 0] v__h2066;
  reg [31 : 0] v__h2716;
  reg [31 : 0] v__h3122;
  reg [31 : 0] x__h1554;
  reg [31 : 0] x__h2099;
  reg [31 : 0] x__h2749;
  reg [31 : 0] x__h3155;
  reg [31 : 0] v__h1513;
  reg [31 : 0] v__h2058;
  reg [31 : 0] v__h2708;
  reg [31 : 0] v__h3114;
  // synopsys translate_on

  // remaining internal signals
  wire [63 : 0] arch_rollback__h2335,
		x1_avValue_mem_req_addr__h1211,
		x__h2380;
  wire [31 : 0] pred_pc__h979;

  // action method init
  assign RDY_init = rg_runstate ;
  assign CAN_FIRE_init = rg_runstate ;
  assign WILL_FIRE_init = EN_init ;

  // value method fo_Fetch_to_Decode_first
  assign fo_Fetch_to_Decode_first = f_Fetch_to_Decode_rv$port1__read[130:0] ;
  assign RDY_fo_Fetch_to_Decode_first =
	     f_Fetch_to_Decode_rv$port1__read[131] ;

  // action method fo_Fetch_to_Decode_deq
  assign RDY_fo_Fetch_to_Decode_deq = f_Fetch_to_Decode_rv$port1__read[131] ;
  assign CAN_FIRE_fo_Fetch_to_Decode_deq =
	     f_Fetch_to_Decode_rv$port1__read[131] ;
  assign WILL_FIRE_fo_Fetch_to_Decode_deq = EN_fo_Fetch_to_Decode_deq ;

  // value method fo_Fetch_to_Decode_notEmpty
  assign fo_Fetch_to_Decode_notEmpty = f_Fetch_to_Decode_rv$port1__read[131] ;
  assign RDY_fo_Fetch_to_Decode_notEmpty = 1'd1 ;

  // value method fo_Fetch_to_IMem_first
  assign fo_Fetch_to_IMem_first = f_Fetch_to_IMem_rv$port1__read[264:0] ;
  assign RDY_fo_Fetch_to_IMem_first = f_Fetch_to_IMem_rv$port1__read[265] ;

  // action method fo_Fetch_to_IMem_deq
  assign RDY_fo_Fetch_to_IMem_deq = f_Fetch_to_IMem_rv$port1__read[265] ;
  assign CAN_FIRE_fo_Fetch_to_IMem_deq = f_Fetch_to_IMem_rv$port1__read[265] ;
  assign WILL_FIRE_fo_Fetch_to_IMem_deq = EN_fo_Fetch_to_IMem_deq ;

  // value method fo_Fetch_to_IMem_notEmpty
  assign fo_Fetch_to_IMem_notEmpty = f_Fetch_to_IMem_rv$port1__read[265] ;
  assign RDY_fo_Fetch_to_IMem_notEmpty = 1'd1 ;

  // action method fi_Fetch_from_Retire_enq
  assign RDY_fi_Fetch_from_Retire_enq =
	     !f_Fetch_from_Retire_rv$port1__read[163] ;
  assign CAN_FIRE_fi_Fetch_from_Retire_enq =
	     !f_Fetch_from_Retire_rv$port1__read[163] ;
  assign WILL_FIRE_fi_Fetch_from_Retire_enq = EN_fi_Fetch_from_Retire_enq ;

  // value method fi_Fetch_from_Retire_notFull
  assign fi_Fetch_from_Retire_notFull =
	     !f_Fetch_from_Retire_rv$port1__read[163] ;
  assign RDY_fi_Fetch_from_Retire_notFull = 1'd1 ;

  // rule RL_rl_Fetch_req
  assign CAN_FIRE_RL_rl_Fetch_req =
	     !f_Fetch_to_Decode_rv[131] && !f_Fetch_to_IMem_rv[265] &&
	     !rg_runstate &&
	     !f_Fetch_from_Retire_rv[163] &&
	     rg_oiaat_fetch ;
  assign WILL_FIRE_RL_rl_Fetch_req = CAN_FIRE_RL_rl_Fetch_req ;

  // rule RL_rl_Fetch_from_Retire
  assign CAN_FIRE_RL_rl_Fetch_from_Retire =
	     f_Fetch_from_Retire_rv[163] &&
	     (!f_Fetch_from_Retire_rv[128] || !f_Fetch_to_Decode_rv[131]) &&
	     (!rg_oiaat || !rg_oiaat_fetch) ;
  assign WILL_FIRE_RL_rl_Fetch_from_Retire =
	     CAN_FIRE_RL_rl_Fetch_from_Retire && !EN_init ;

  // inputs to muxes for submodule ports
  assign MUX_f_Fetch_to_Decode_rv$port0__write_1__SEL_1 =
	     WILL_FIRE_RL_rl_Fetch_from_Retire &&
	     f_Fetch_from_Retire_rv[128] ;
  assign MUX_rg_oiaat_fetch$write_1__SEL_1 =
	     WILL_FIRE_RL_rl_Fetch_req && rg_oiaat ;
  assign MUX_rg_runstate$write_1__SEL_1 =
	     WILL_FIRE_RL_rl_Fetch_from_Retire &&
	     (f_Fetch_from_Retire_rv[128] || rg_runstate) ;
  assign MUX_f_Fetch_to_Decode_rv$port0__write_1__VAL_1 =
	     { 65'h10000000000000000, rg_epoch, 65'h10000000000000000 } ;
  assign MUX_f_Fetch_to_Decode_rv$port0__write_1__VAL_2 =
	     { 1'd1, rg_pc, pred_pc__h979, rg_epoch, 1'd0, rg_inum } ;
  assign MUX_rg_arch_inum$write_1__VAL_1 = rg_arch_inum + 64'd1 ;
  assign MUX_rg_arch_inum$write_1__VAL_2 =
	     rg_arch_inum - arch_rollback__h2335 ;

  // inlined wires
  assign f_Fetch_to_Decode_rv$EN_port0__write =
	     WILL_FIRE_RL_rl_Fetch_from_Retire &&
	     f_Fetch_from_Retire_rv[128] ||
	     WILL_FIRE_RL_rl_Fetch_req ;
  assign f_Fetch_to_Decode_rv$port0__write_1 =
	     MUX_f_Fetch_to_Decode_rv$port0__write_1__SEL_1 ?
	       MUX_f_Fetch_to_Decode_rv$port0__write_1__VAL_1 :
	       MUX_f_Fetch_to_Decode_rv$port0__write_1__VAL_2 ;
  assign f_Fetch_to_Decode_rv$port1__read =
	     f_Fetch_to_Decode_rv$EN_port0__write ?
	       f_Fetch_to_Decode_rv$port0__write_1 :
	       f_Fetch_to_Decode_rv ;
  assign f_Fetch_to_Decode_rv$port1__write_1 =
	     { 1'd0,
	       131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign f_Fetch_to_Decode_rv$port2__read =
	     EN_fo_Fetch_to_Decode_deq ?
	       f_Fetch_to_Decode_rv$port1__write_1 :
	       f_Fetch_to_Decode_rv$port1__read ;
  assign f_Fetch_to_IMem_rv$port0__write_1 =
	     { 8'd154,
	       x1_avValue_mem_req_addr__h1211,
	       rg_arch_inum,
	       rg_epoch,
	       rg_inum,
	       rg_pc,
	       32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign f_Fetch_to_IMem_rv$port1__read =
	     CAN_FIRE_RL_rl_Fetch_req ?
	       f_Fetch_to_IMem_rv$port0__write_1 :
	       f_Fetch_to_IMem_rv ;
  assign f_Fetch_to_IMem_rv$port1__write_1 =
	     { 1'd0,
	       265'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign f_Fetch_to_IMem_rv$port2__read =
	     EN_fo_Fetch_to_IMem_deq ?
	       f_Fetch_to_IMem_rv$port1__write_1 :
	       f_Fetch_to_IMem_rv$port1__read ;
  assign f_Fetch_from_Retire_rv$port0__write_1 =
	     { 1'd0,
	       163'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign f_Fetch_from_Retire_rv$port1__read =
	     WILL_FIRE_RL_rl_Fetch_from_Retire ?
	       f_Fetch_from_Retire_rv$port0__write_1 :
	       f_Fetch_from_Retire_rv ;
  assign f_Fetch_from_Retire_rv$port1__write_1 =
	     { 1'd1, fi_Fetch_from_Retire_enq_x } ;
  assign f_Fetch_from_Retire_rv$port2__read =
	     EN_fi_Fetch_from_Retire_enq ?
	       f_Fetch_from_Retire_rv$port1__write_1 :
	       f_Fetch_from_Retire_rv$port1__read ;

  // register f_Fetch_from_Retire_rv
  assign f_Fetch_from_Retire_rv$D_IN = f_Fetch_from_Retire_rv$port2__read ;
  assign f_Fetch_from_Retire_rv$EN = 1'b1 ;

  // register f_Fetch_to_Decode_rv
  assign f_Fetch_to_Decode_rv$D_IN = f_Fetch_to_Decode_rv$port2__read ;
  assign f_Fetch_to_Decode_rv$EN = 1'b1 ;

  // register f_Fetch_to_IMem_rv
  assign f_Fetch_to_IMem_rv$D_IN = f_Fetch_to_IMem_rv$port2__read ;
  assign f_Fetch_to_IMem_rv$EN = 1'b1 ;

  // register rg_arch_inum
  assign rg_arch_inum$D_IN =
	     WILL_FIRE_RL_rl_Fetch_req ?
	       MUX_rg_arch_inum$write_1__VAL_1 :
	       MUX_rg_arch_inum$write_1__VAL_2 ;
  assign rg_arch_inum$EN =
	     WILL_FIRE_RL_rl_Fetch_req || WILL_FIRE_RL_rl_Fetch_from_Retire ;

  // register rg_epoch
  assign rg_epoch$D_IN = f_Fetch_from_Retire_rv[130:129] ;
  assign rg_epoch$EN = WILL_FIRE_RL_rl_Fetch_from_Retire ;

  // register rg_flog
  assign rg_flog$D_IN = init_initial_params[207:176] ;
  assign rg_flog$EN = EN_init ;

  // register rg_inum
  assign rg_inum$D_IN = rg_inum + 64'd1 ;
  assign rg_inum$EN = CAN_FIRE_RL_rl_Fetch_req ;

  // register rg_oiaat
  assign rg_oiaat$D_IN = 1'b0 ;
  assign rg_oiaat$EN = 1'b0 ;

  // register rg_oiaat_fetch
  assign rg_oiaat_fetch$D_IN = !MUX_rg_oiaat_fetch$write_1__SEL_1 ;
  assign rg_oiaat_fetch$EN =
	     WILL_FIRE_RL_rl_Fetch_req && rg_oiaat ||
	     WILL_FIRE_RL_rl_Fetch_from_Retire ;

  // register rg_pc
  always@(WILL_FIRE_RL_rl_Fetch_req or
	  pred_pc__h979 or
	  WILL_FIRE_RL_rl_Fetch_from_Retire or
	  f_Fetch_from_Retire_rv or EN_init or init_initial_params)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_rl_Fetch_req: rg_pc$D_IN = pred_pc__h979;
      WILL_FIRE_RL_rl_Fetch_from_Retire:
	  rg_pc$D_IN = f_Fetch_from_Retire_rv[162:131];
      EN_init: rg_pc$D_IN = init_initial_params[175:144];
      default: rg_pc$D_IN =
		   32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
    endcase
  end
  assign rg_pc$EN =
	     WILL_FIRE_RL_rl_Fetch_req || WILL_FIRE_RL_rl_Fetch_from_Retire ||
	     EN_init ;

  // register rg_runstate
  assign rg_runstate$D_IN =
	     MUX_rg_runstate$write_1__SEL_1 && f_Fetch_from_Retire_rv[128] ;
  assign rg_runstate$EN =
	     WILL_FIRE_RL_rl_Fetch_from_Retire &&
	     (f_Fetch_from_Retire_rv[128] || rg_runstate) ||
	     EN_init ;

  // remaining internal signals
  assign arch_rollback__h2335 = x__h2380 - 64'd1 ;
  assign pred_pc__h979 = rg_pc + 32'd4 ;
  assign x1_avValue_mem_req_addr__h1211 = { 32'd0, rg_pc } ;
  assign x__h2380 = rg_inum - f_Fetch_from_Retire_rv[127:64] ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        f_Fetch_from_Retire_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0,
	      163'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
	f_Fetch_to_Decode_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0,
	      131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
	f_Fetch_to_IMem_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0,
	      265'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
	rg_arch_inum <= `BSV_ASSIGNMENT_DELAY 64'd0;
	rg_epoch <= `BSV_ASSIGNMENT_DELAY 2'd0;
	rg_flog <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rg_inum <= `BSV_ASSIGNMENT_DELAY 64'd0;
	rg_oiaat <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rg_oiaat_fetch <= `BSV_ASSIGNMENT_DELAY 1'd1;
	rg_pc <= `BSV_ASSIGNMENT_DELAY 32'd0;
	rg_runstate <= `BSV_ASSIGNMENT_DELAY 1'd1;
      end
    else
      begin
        if (f_Fetch_from_Retire_rv$EN)
	  f_Fetch_from_Retire_rv <= `BSV_ASSIGNMENT_DELAY
	      f_Fetch_from_Retire_rv$D_IN;
	if (f_Fetch_to_Decode_rv$EN)
	  f_Fetch_to_Decode_rv <= `BSV_ASSIGNMENT_DELAY
	      f_Fetch_to_Decode_rv$D_IN;
	if (f_Fetch_to_IMem_rv$EN)
	  f_Fetch_to_IMem_rv <= `BSV_ASSIGNMENT_DELAY f_Fetch_to_IMem_rv$D_IN;
	if (rg_arch_inum$EN)
	  rg_arch_inum <= `BSV_ASSIGNMENT_DELAY rg_arch_inum$D_IN;
	if (rg_epoch$EN) rg_epoch <= `BSV_ASSIGNMENT_DELAY rg_epoch$D_IN;
	if (rg_flog$EN) rg_flog <= `BSV_ASSIGNMENT_DELAY rg_flog$D_IN;
	if (rg_inum$EN) rg_inum <= `BSV_ASSIGNMENT_DELAY rg_inum$D_IN;
	if (rg_oiaat$EN) rg_oiaat <= `BSV_ASSIGNMENT_DELAY rg_oiaat$D_IN;
	if (rg_oiaat_fetch$EN)
	  rg_oiaat_fetch <= `BSV_ASSIGNMENT_DELAY rg_oiaat_fetch$D_IN;
	if (rg_pc$EN) rg_pc <= `BSV_ASSIGNMENT_DELAY rg_pc$D_IN;
	if (rg_runstate$EN)
	  rg_runstate <= `BSV_ASSIGNMENT_DELAY rg_runstate$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    f_Fetch_from_Retire_rv = 164'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    f_Fetch_to_Decode_rv = 132'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    f_Fetch_to_IMem_rv =
	266'h2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    rg_arch_inum = 64'hAAAAAAAAAAAAAAAA;
    rg_epoch = 2'h2;
    rg_flog = 32'hAAAAAAAA;
    rg_inum = 64'hAAAAAAAAAAAAAAAA;
    rg_oiaat = 1'h0;
    rg_oiaat_fetch = 1'h0;
    rg_pc = 32'hAAAAAAAA;
    rg_runstate = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	begin
	  v__h1521 = $stime;
	  #0;
	end
    x__h1554 = v__h1521 + 32'd5;
    v__h1513 = x__h1554 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h1513);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, "CPU.Fetch:");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, "    ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, "    Fetch_to_Decode{", "I_%0d", rg_inum);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, " pc:%08h", rg_pc);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, " pred:%08h epoch:%0d", pred_pc__h979, rg_epoch);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, " halt_sentinel:%0d}", 1'd0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, "    ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog,
		"    Mem_Req {I_%0d pc:%08h instr:%08h ",
		rg_inum,
		rg_pc,
		32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ,
		"FETCH");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, " ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, "4B");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, " addr:%08h", x1_avValue_mem_req_addr__h1211);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, " epoch:%0d}", rg_epoch);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	begin
	  v__h2066 = $stime;
	  #0;
	end
    x__h2099 = v__h2066 + 32'd5;
    v__h2058 = x__h2099 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog,
		"Trace %0d %0d %08h %08h %s",
		v__h2058,
		rg_inum,
		rg_pc,
		32'd0,
		"F");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0) $fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_req && rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_from_Retire && rg_flog != 32'd0)
	begin
	  v__h2716 = $stime;
	  #0;
	end
    x__h2749 = v__h2716 + 32'd5;
    v__h2708 = x__h2749 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_from_Retire && rg_flog != 32'd0)
	$fwrite(rg_flog, "%0d: ", v__h2708);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_from_Retire && rg_flog != 32'd0)
	$fwrite(rg_flog, "CPU.Redirect:");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_from_Retire && rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_from_Retire && rg_flog != 32'd0)
	$fwrite(rg_flog, "    ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_from_Retire && rg_flog != 32'd0)
	$fwrite(rg_flog,
		"    Fetch_from_Retire{",
		"I_%0d",
		f_Fetch_from_Retire_rv[127:64]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_from_Retire && rg_flog != 32'd0)
	$fwrite(rg_flog, " pc:%08h", f_Fetch_from_Retire_rv[63:32]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_from_Retire && rg_flog != 32'd0)
	$fwrite(rg_flog, " instr:%08h", f_Fetch_from_Retire_rv[31:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_from_Retire && rg_flog != 32'd0)
	$fwrite(rg_flog,
		" next_pc:%08h next_epoch %0d haltreq %0d",
		f_Fetch_from_Retire_rv[162:131],
		f_Fetch_from_Retire_rv[130:129],
		f_Fetch_from_Retire_rv[128]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_from_Retire && rg_flog != 32'd0)
	$fwrite(rg_flog, "}");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_from_Retire && rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_from_Retire && rg_flog != 32'd0)
	begin
	  v__h3122 = $stime;
	  #0;
	end
    x__h3155 = v__h3122 + 32'd5;
    v__h3114 = x__h3155 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_from_Retire && rg_flog != 32'd0)
	$fwrite(rg_flog,
		"Trace %0d %0d %08h %08h %s",
		v__h3114,
		f_Fetch_from_Retire_rv[127:64],
		f_Fetch_from_Retire_rv[63:32],
		f_Fetch_from_Retire_rv[31:0],
		"Redir");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_from_Retire && rg_flog != 32'd0)
	$fwrite(rg_flog, "");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_Fetch_from_Retire && rg_flog != 32'd0)
	$fwrite(rg_flog, "\n");
  end
  // synopsys translate_on
endmodule  // mkFetch

