//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:54 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_request_put                O     1 reg
// response_get                   O    41 reg
// RDY_response_get               O     1 reg
// verbosity                      I     2 unused
// CLK                            I     1 clock
// RST_N                          I     1 reset
// request_put                    I    32
// EN_request_put                 I     1
// EN_response_get                I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFtoP_PNE(verbosity,
		  CLK,
		  RST_N,

		  request_put,
		  EN_request_put,
		  RDY_request_put,

		  EN_response_get,
		  response_get,
		  RDY_response_get);
  input  [1 : 0] verbosity;
  input  CLK;
  input  RST_N;

  // action method request_put
  input  [31 : 0] request_put;
  input  EN_request_put;
  output RDY_request_put;

  // actionvalue method response_get
  input  EN_response_get;
  output [40 : 0] response_get;
  output RDY_response_get;

  // signals for module outputs
  wire [40 : 0] response_get;
  wire RDY_request_put, RDY_response_get;

  // ports of submodule ffO
  wire [40 : 0] ffO$D_IN, ffO$D_OUT;
  wire ffO$CLR, ffO$DEQ, ffO$EMPTY_N, ffO$ENQ, ffO$FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_request_put,
       CAN_FIRE_response_get,
       WILL_FIRE_request_put,
       WILL_FIRE_response_get;

  // remaining internal signals
  wire [28 : 0] IF_IF_0_CONCAT_request_put_BITS_30_TO_23_3_MIN_ETC___d50;
  wire [27 : 0] frac__h143, x__h614;
  wire [26 : 0] frac_extend__h616;
  wire [8 : 0] _0_CONCAT_request_put_BITS_30_TO_23_MINUS_127__q1;
  wire [7 : 0] IF_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS__ETC__q2,
	       IF_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS__ETC__q3,
	       _0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d20,
	       _0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d24,
	       x_scale__h164;
  wire [5 : 0] IF_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS__ETC___d29,
	       IF_IF_0_CONCAT_request_put_BITS_30_TO_23_3_MIN_ETC___d34,
	       x__h674;
  wire _0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d16,
       _0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d17;

  // action method request_put
  assign RDY_request_put = ffO$FULL_N ;
  assign CAN_FIRE_request_put = ffO$FULL_N ;
  assign WILL_FIRE_request_put = EN_request_put ;

  // actionvalue method response_get
  assign response_get = ffO$D_OUT ;
  assign RDY_response_get = ffO$EMPTY_N ;
  assign CAN_FIRE_response_get = ffO$EMPTY_N ;
  assign WILL_FIRE_response_get = EN_response_get ;

  // submodule ffO
  FIFO1 #(.width(32'd41), .guarded(1'd1)) ffO(.RST(RST_N),
					      .CLK(CLK),
					      .D_IN(ffO$D_IN),
					      .ENQ(ffO$ENQ),
					      .DEQ(ffO$DEQ),
					      .CLR(ffO$CLR),
					      .D_OUT(ffO$D_OUT),
					      .FULL_N(ffO$FULL_N),
					      .EMPTY_N(ffO$EMPTY_N));

  // submodule ffO
  assign ffO$D_IN =
	     { request_put[31],
	       (request_put[30:23] == 8'd255 && request_put[22:0] == 23'd0) ?
		 2'd1 :
		 ((request_put[30:23] == 8'd0 && request_put[22:0] == 23'd0) ?
		    2'd2 :
		    2'd0),
	       request_put[30:23] == 8'd255 && request_put[22:0] != 23'd0,
	       x_scale__h164,
	       IF_IF_0_CONCAT_request_put_BITS_30_TO_23_3_MIN_ETC___d50 } ;
  assign ffO$ENQ = EN_request_put ;
  assign ffO$DEQ = EN_response_get ;
  assign ffO$CLR = 1'b0 ;

  // remaining internal signals
  assign IF_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS__ETC___d29 =
	     _0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d16 ?
	       IF_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS__ETC__q2[5:0] :
	       (_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d17 ?
		  6'd0 :
		  IF_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS__ETC__q3[5:0]) ;
  assign IF_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS__ETC__q2 =
	     ((_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d20 ^
	       8'h80) <=
	      8'd97) ?
	       8'd225 :
	       _0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d20 ;
  assign IF_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS__ETC__q3 =
	     ((_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d24 ^
	       8'h80) <=
	      8'd159) ?
	       _0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d24 :
	       8'd31 ;
  assign IF_IF_0_CONCAT_request_put_BITS_30_TO_23_3_MIN_ETC___d34 =
	     IF_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS__ETC___d29[5] ?
	       -IF_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS__ETC___d29 :
	       IF_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS__ETC___d29 ;
  assign IF_IF_0_CONCAT_request_put_BITS_30_TO_23_3_MIN_ETC___d50 =
	     IF_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS__ETC___d29[5] ?
	       { x__h614[26:0],
		 frac__h143[x__h674[4:0]],
		 { 4'd0,
		   (frac__h143 &
		    ~(28'hFFFFFFE <<
		      IF_IF_0_CONCAT_request_put_BITS_30_TO_23_3_MIN_ETC___d34[4:0])) >>
		   0 } ==
		 32'd0 } :
	       { (IF_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS__ETC___d29 ==
		  6'd0) ?
		   frac_extend__h616 :
		   27'd134217727,
		 IF_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS__ETC___d29 !=
		 6'd0,
		 IF_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS__ETC___d29 ==
		 6'd0 } ;
  assign _0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d16 =
	     (_0_CONCAT_request_put_BITS_30_TO_23_MINUS_127__q1[7:0] ^
	      8'h80) <
	     8'd8 ;
  assign _0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d17 =
	     (_0_CONCAT_request_put_BITS_30_TO_23_MINUS_127__q1[7:0] ^
	      8'h80) <=
	     8'd248 ;
  assign _0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d20 =
	     _0_CONCAT_request_put_BITS_30_TO_23_MINUS_127__q1[7:0] - 8'd136 ;
  assign _0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d24 =
	     _0_CONCAT_request_put_BITS_30_TO_23_MINUS_127__q1[7:0] - 8'd120 ;
  assign _0_CONCAT_request_put_BITS_30_TO_23_MINUS_127__q1 =
	     { 1'd0, request_put[30:23] } - 9'd127 ;
  assign frac__h143 = { 1'd1, frac_extend__h616 } ;
  assign frac_extend__h616 = { request_put[22:0], 4'd0 } ;
  assign x__h614 = frac__h143 >> x__h674 ;
  assign x__h674 =
	     IF_IF_0_CONCAT_request_put_BITS_30_TO_23_3_MIN_ETC___d34 + 6'd1 ;
  assign x_scale__h164 =
	     _0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d16 ?
	       8'd136 :
	       (_0_CONCAT_request_put_BITS_30_TO_23_3_MINUS_127_ETC___d17 ?
		  _0_CONCAT_request_put_BITS_30_TO_23_MINUS_127__q1[7:0] :
		  8'd120) ;
endmodule  // mkFtoP_PNE

