//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:49 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_log_rd_write               O     1 const
// RDY_log_rs1_read               O     1 const
// RDY_log_rs2_read               O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 unused
// log_rd_write_inum              I    64 reg
// log_rd_write_rd                I     5
// log_rs1_read_inum              I    64 reg
// log_rs1_read_rs1               I     5
// log_rs1_read_val               I    32 reg
// log_rs2_read_inum              I    64 reg
// log_rs2_read_rs2               I     5
// log_rs2_read_val               I    32 reg
// EN_log_rd_write                I     1
// EN_log_rs1_read                I     1
// EN_log_rs2_read                I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkGPR_Logging_synth(CLK,
			   RST_N,

			   log_rd_write_inum,
			   log_rd_write_rd,
			   EN_log_rd_write,
			   RDY_log_rd_write,

			   log_rs1_read_inum,
			   log_rs1_read_rs1,
			   log_rs1_read_val,
			   EN_log_rs1_read,
			   RDY_log_rs1_read,

			   log_rs2_read_inum,
			   log_rs2_read_rs2,
			   log_rs2_read_val,
			   EN_log_rs2_read,
			   RDY_log_rs2_read);
  input  CLK;
  input  RST_N;

  // action method log_rd_write
  input  [63 : 0] log_rd_write_inum;
  input  [4 : 0] log_rd_write_rd;
  input  EN_log_rd_write;
  output RDY_log_rd_write;

  // action method log_rs1_read
  input  [63 : 0] log_rs1_read_inum;
  input  [4 : 0] log_rs1_read_rs1;
  input  [31 : 0] log_rs1_read_val;
  input  EN_log_rs1_read;
  output RDY_log_rs1_read;

  // action method log_rs2_read
  input  [63 : 0] log_rs2_read_inum;
  input  [4 : 0] log_rs2_read_rs2;
  input  [31 : 0] log_rs2_read_val;
  input  EN_log_rs2_read;
  output RDY_log_rs2_read;

  // signals for module outputs
  wire RDY_log_rd_write, RDY_log_rs1_read, RDY_log_rs2_read;

  // ports of submodule ifc_rf_inum_rd_rs1
  wire [63 : 0] ifc_rf_inum_rd_rs1$D_IN;
  wire [4 : 0] ifc_rf_inum_rd_rs1$ADDR_1,
	       ifc_rf_inum_rd_rs1$ADDR_2,
	       ifc_rf_inum_rd_rs1$ADDR_3,
	       ifc_rf_inum_rd_rs1$ADDR_4,
	       ifc_rf_inum_rd_rs1$ADDR_5,
	       ifc_rf_inum_rd_rs1$ADDR_IN;
  wire ifc_rf_inum_rd_rs1$WE;

  // ports of submodule ifc_rf_inum_rd_rs2
  wire [63 : 0] ifc_rf_inum_rd_rs2$D_IN;
  wire [4 : 0] ifc_rf_inum_rd_rs2$ADDR_1,
	       ifc_rf_inum_rd_rs2$ADDR_2,
	       ifc_rf_inum_rd_rs2$ADDR_3,
	       ifc_rf_inum_rd_rs2$ADDR_4,
	       ifc_rf_inum_rd_rs2$ADDR_5,
	       ifc_rf_inum_rd_rs2$ADDR_IN;
  wire ifc_rf_inum_rd_rs2$WE;

  // ports of submodule ifc_rf_inum_wr
  wire [63 : 0] ifc_rf_inum_wr$D_IN;
  wire [4 : 0] ifc_rf_inum_wr$ADDR_1,
	       ifc_rf_inum_wr$ADDR_2,
	       ifc_rf_inum_wr$ADDR_3,
	       ifc_rf_inum_wr$ADDR_4,
	       ifc_rf_inum_wr$ADDR_5,
	       ifc_rf_inum_wr$ADDR_IN;
  wire ifc_rf_inum_wr$WE;

  // ports of submodule ifc_rf_val_rd_rs1
  wire [31 : 0] ifc_rf_val_rd_rs1$D_IN;
  wire [4 : 0] ifc_rf_val_rd_rs1$ADDR_1,
	       ifc_rf_val_rd_rs1$ADDR_2,
	       ifc_rf_val_rd_rs1$ADDR_3,
	       ifc_rf_val_rd_rs1$ADDR_4,
	       ifc_rf_val_rd_rs1$ADDR_5,
	       ifc_rf_val_rd_rs1$ADDR_IN;
  wire ifc_rf_val_rd_rs1$WE;

  // ports of submodule ifc_rf_val_rd_rs2
  wire [31 : 0] ifc_rf_val_rd_rs2$D_IN;
  wire [4 : 0] ifc_rf_val_rd_rs2$ADDR_1,
	       ifc_rf_val_rd_rs2$ADDR_2,
	       ifc_rf_val_rd_rs2$ADDR_3,
	       ifc_rf_val_rd_rs2$ADDR_4,
	       ifc_rf_val_rd_rs2$ADDR_5,
	       ifc_rf_val_rd_rs2$ADDR_IN;
  wire ifc_rf_val_rd_rs2$WE;

  // rule scheduling signals
  wire CAN_FIRE_log_rd_write,
       CAN_FIRE_log_rs1_read,
       CAN_FIRE_log_rs2_read,
       WILL_FIRE_log_rd_write,
       WILL_FIRE_log_rs1_read,
       WILL_FIRE_log_rs2_read;

  // action method log_rd_write
  assign RDY_log_rd_write = 1'd1 ;
  assign CAN_FIRE_log_rd_write = 1'd1 ;
  assign WILL_FIRE_log_rd_write = EN_log_rd_write ;

  // action method log_rs1_read
  assign RDY_log_rs1_read = 1'd1 ;
  assign CAN_FIRE_log_rs1_read = 1'd1 ;
  assign WILL_FIRE_log_rs1_read = EN_log_rs1_read ;

  // action method log_rs2_read
  assign RDY_log_rs2_read = 1'd1 ;
  assign CAN_FIRE_log_rs2_read = 1'd1 ;
  assign WILL_FIRE_log_rs2_read = EN_log_rs2_read ;

  // submodule ifc_rf_inum_rd_rs1
  RegFile #(.addr_width(32'd5),
	    .data_width(32'd64),
	    .lo(5'h0),
	    .hi(5'd31)) ifc_rf_inum_rd_rs1(.CLK(CLK),
					   .ADDR_1(ifc_rf_inum_rd_rs1$ADDR_1),
					   .ADDR_2(ifc_rf_inum_rd_rs1$ADDR_2),
					   .ADDR_3(ifc_rf_inum_rd_rs1$ADDR_3),
					   .ADDR_4(ifc_rf_inum_rd_rs1$ADDR_4),
					   .ADDR_5(ifc_rf_inum_rd_rs1$ADDR_5),
					   .ADDR_IN(ifc_rf_inum_rd_rs1$ADDR_IN),
					   .D_IN(ifc_rf_inum_rd_rs1$D_IN),
					   .WE(ifc_rf_inum_rd_rs1$WE),
					   .D_OUT_1(),
					   .D_OUT_2(),
					   .D_OUT_3(),
					   .D_OUT_4(),
					   .D_OUT_5());

  // submodule ifc_rf_inum_rd_rs2
  RegFile #(.addr_width(32'd5),
	    .data_width(32'd64),
	    .lo(5'h0),
	    .hi(5'd31)) ifc_rf_inum_rd_rs2(.CLK(CLK),
					   .ADDR_1(ifc_rf_inum_rd_rs2$ADDR_1),
					   .ADDR_2(ifc_rf_inum_rd_rs2$ADDR_2),
					   .ADDR_3(ifc_rf_inum_rd_rs2$ADDR_3),
					   .ADDR_4(ifc_rf_inum_rd_rs2$ADDR_4),
					   .ADDR_5(ifc_rf_inum_rd_rs2$ADDR_5),
					   .ADDR_IN(ifc_rf_inum_rd_rs2$ADDR_IN),
					   .D_IN(ifc_rf_inum_rd_rs2$D_IN),
					   .WE(ifc_rf_inum_rd_rs2$WE),
					   .D_OUT_1(),
					   .D_OUT_2(),
					   .D_OUT_3(),
					   .D_OUT_4(),
					   .D_OUT_5());

  // submodule ifc_rf_inum_wr
  RegFile #(.addr_width(32'd5),
	    .data_width(32'd64),
	    .lo(5'h0),
	    .hi(5'd31)) ifc_rf_inum_wr(.CLK(CLK),
				       .ADDR_1(ifc_rf_inum_wr$ADDR_1),
				       .ADDR_2(ifc_rf_inum_wr$ADDR_2),
				       .ADDR_3(ifc_rf_inum_wr$ADDR_3),
				       .ADDR_4(ifc_rf_inum_wr$ADDR_4),
				       .ADDR_5(ifc_rf_inum_wr$ADDR_5),
				       .ADDR_IN(ifc_rf_inum_wr$ADDR_IN),
				       .D_IN(ifc_rf_inum_wr$D_IN),
				       .WE(ifc_rf_inum_wr$WE),
				       .D_OUT_1(),
				       .D_OUT_2(),
				       .D_OUT_3(),
				       .D_OUT_4(),
				       .D_OUT_5());

  // submodule ifc_rf_val_rd_rs1
  RegFile #(.addr_width(32'd5),
	    .data_width(32'd32),
	    .lo(5'h0),
	    .hi(5'd31)) ifc_rf_val_rd_rs1(.CLK(CLK),
					  .ADDR_1(ifc_rf_val_rd_rs1$ADDR_1),
					  .ADDR_2(ifc_rf_val_rd_rs1$ADDR_2),
					  .ADDR_3(ifc_rf_val_rd_rs1$ADDR_3),
					  .ADDR_4(ifc_rf_val_rd_rs1$ADDR_4),
					  .ADDR_5(ifc_rf_val_rd_rs1$ADDR_5),
					  .ADDR_IN(ifc_rf_val_rd_rs1$ADDR_IN),
					  .D_IN(ifc_rf_val_rd_rs1$D_IN),
					  .WE(ifc_rf_val_rd_rs1$WE),
					  .D_OUT_1(),
					  .D_OUT_2(),
					  .D_OUT_3(),
					  .D_OUT_4(),
					  .D_OUT_5());

  // submodule ifc_rf_val_rd_rs2
  RegFile #(.addr_width(32'd5),
	    .data_width(32'd32),
	    .lo(5'h0),
	    .hi(5'd31)) ifc_rf_val_rd_rs2(.CLK(CLK),
					  .ADDR_1(ifc_rf_val_rd_rs2$ADDR_1),
					  .ADDR_2(ifc_rf_val_rd_rs2$ADDR_2),
					  .ADDR_3(ifc_rf_val_rd_rs2$ADDR_3),
					  .ADDR_4(ifc_rf_val_rd_rs2$ADDR_4),
					  .ADDR_5(ifc_rf_val_rd_rs2$ADDR_5),
					  .ADDR_IN(ifc_rf_val_rd_rs2$ADDR_IN),
					  .D_IN(ifc_rf_val_rd_rs2$D_IN),
					  .WE(ifc_rf_val_rd_rs2$WE),
					  .D_OUT_1(),
					  .D_OUT_2(),
					  .D_OUT_3(),
					  .D_OUT_4(),
					  .D_OUT_5());

  // submodule ifc_rf_inum_rd_rs1
  assign ifc_rf_inum_rd_rs1$ADDR_1 = 5'h0 ;
  assign ifc_rf_inum_rd_rs1$ADDR_2 = 5'h0 ;
  assign ifc_rf_inum_rd_rs1$ADDR_3 = 5'h0 ;
  assign ifc_rf_inum_rd_rs1$ADDR_4 = 5'h0 ;
  assign ifc_rf_inum_rd_rs1$ADDR_5 = 5'h0 ;
  assign ifc_rf_inum_rd_rs1$ADDR_IN = log_rs1_read_rs1 ;
  assign ifc_rf_inum_rd_rs1$D_IN = log_rs1_read_inum ;
  assign ifc_rf_inum_rd_rs1$WE = EN_log_rs1_read ;

  // submodule ifc_rf_inum_rd_rs2
  assign ifc_rf_inum_rd_rs2$ADDR_1 = 5'h0 ;
  assign ifc_rf_inum_rd_rs2$ADDR_2 = 5'h0 ;
  assign ifc_rf_inum_rd_rs2$ADDR_3 = 5'h0 ;
  assign ifc_rf_inum_rd_rs2$ADDR_4 = 5'h0 ;
  assign ifc_rf_inum_rd_rs2$ADDR_5 = 5'h0 ;
  assign ifc_rf_inum_rd_rs2$ADDR_IN = log_rs2_read_rs2 ;
  assign ifc_rf_inum_rd_rs2$D_IN = log_rs2_read_inum ;
  assign ifc_rf_inum_rd_rs2$WE = EN_log_rs2_read ;

  // submodule ifc_rf_inum_wr
  assign ifc_rf_inum_wr$ADDR_1 = 5'h0 ;
  assign ifc_rf_inum_wr$ADDR_2 = 5'h0 ;
  assign ifc_rf_inum_wr$ADDR_3 = 5'h0 ;
  assign ifc_rf_inum_wr$ADDR_4 = 5'h0 ;
  assign ifc_rf_inum_wr$ADDR_5 = 5'h0 ;
  assign ifc_rf_inum_wr$ADDR_IN = log_rd_write_rd ;
  assign ifc_rf_inum_wr$D_IN = log_rd_write_inum ;
  assign ifc_rf_inum_wr$WE = EN_log_rd_write ;

  // submodule ifc_rf_val_rd_rs1
  assign ifc_rf_val_rd_rs1$ADDR_1 = 5'h0 ;
  assign ifc_rf_val_rd_rs1$ADDR_2 = 5'h0 ;
  assign ifc_rf_val_rd_rs1$ADDR_3 = 5'h0 ;
  assign ifc_rf_val_rd_rs1$ADDR_4 = 5'h0 ;
  assign ifc_rf_val_rd_rs1$ADDR_5 = 5'h0 ;
  assign ifc_rf_val_rd_rs1$ADDR_IN = log_rs1_read_rs1 ;
  assign ifc_rf_val_rd_rs1$D_IN = log_rs1_read_val ;
  assign ifc_rf_val_rd_rs1$WE = EN_log_rs1_read ;

  // submodule ifc_rf_val_rd_rs2
  assign ifc_rf_val_rd_rs2$ADDR_1 = 5'h0 ;
  assign ifc_rf_val_rd_rs2$ADDR_2 = 5'h0 ;
  assign ifc_rf_val_rd_rs2$ADDR_3 = 5'h0 ;
  assign ifc_rf_val_rd_rs2$ADDR_4 = 5'h0 ;
  assign ifc_rf_val_rd_rs2$ADDR_5 = 5'h0 ;
  assign ifc_rf_val_rd_rs2$ADDR_IN = log_rs2_read_rs2 ;
  assign ifc_rf_val_rd_rs2$D_IN = log_rs2_read_val ;
  assign ifc_rf_val_rd_rs2$WE = EN_log_rs2_read ;
endmodule  // mkGPR_Logging_synth

