//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:49 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// read_rs1                       O    32
// RDY_read_rs1                   O     1 reg
// read_rs2                       O    32
// RDY_read_rs2                   O     1 reg
// RDY_write_rd                   O     1 reg
// read_dm                        O    32
// RDY_read_dm                    O     1 reg
// RDY_write_dm                   O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// read_rs1_rs1                   I     5
// read_rs2_rs2                   I     5
// write_rd_rd                    I     5
// write_rd_rd_val                I    32
// read_dm_rs                     I     5
// write_dm_rd                    I     5
// write_dm_rd_val                I    32
// EN_write_rd                    I     1
// EN_write_dm                    I     1
//
// Combinational paths from inputs to outputs:
//   read_rs1_rs1 -> read_rs1
//   read_rs2_rs2 -> read_rs2
//   read_dm_rs -> read_dm
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkGPRs_synth(CLK,
		    RST_N,

		    read_rs1_rs1,
		    read_rs1,
		    RDY_read_rs1,

		    read_rs2_rs2,
		    read_rs2,
		    RDY_read_rs2,

		    write_rd_rd,
		    write_rd_rd_val,
		    EN_write_rd,
		    RDY_write_rd,

		    read_dm_rs,
		    read_dm,
		    RDY_read_dm,

		    write_dm_rd,
		    write_dm_rd_val,
		    EN_write_dm,
		    RDY_write_dm);
  input  CLK;
  input  RST_N;

  // value method read_rs1
  input  [4 : 0] read_rs1_rs1;
  output [31 : 0] read_rs1;
  output RDY_read_rs1;

  // value method read_rs2
  input  [4 : 0] read_rs2_rs2;
  output [31 : 0] read_rs2;
  output RDY_read_rs2;

  // action method write_rd
  input  [4 : 0] write_rd_rd;
  input  [31 : 0] write_rd_rd_val;
  input  EN_write_rd;
  output RDY_write_rd;

  // value method read_dm
  input  [4 : 0] read_dm_rs;
  output [31 : 0] read_dm;
  output RDY_read_dm;

  // action method write_dm
  input  [4 : 0] write_dm_rd;
  input  [31 : 0] write_dm_rd_val;
  input  EN_write_dm;
  output RDY_write_dm;

  // signals for module outputs
  wire [31 : 0] read_dm, read_rs1, read_rs2;
  wire RDY_read_dm, RDY_read_rs1, RDY_read_rs2, RDY_write_dm, RDY_write_rd;

  // register ifc_rg_init_index
  reg [5 : 0] ifc_rg_init_index;
  wire [5 : 0] ifc_rg_init_index$D_IN;
  wire ifc_rg_init_index$EN;

  // ports of submodule ifc_rf
  reg [31 : 0] ifc_rf$D_IN;
  reg [4 : 0] ifc_rf$ADDR_IN;
  wire [31 : 0] ifc_rf$D_OUT_1, ifc_rf$D_OUT_2, ifc_rf$D_OUT_3;
  wire [4 : 0] ifc_rf$ADDR_1,
	       ifc_rf$ADDR_2,
	       ifc_rf$ADDR_3,
	       ifc_rf$ADDR_4,
	       ifc_rf$ADDR_5;
  wire ifc_rf$WE;

  // rule scheduling signals
  wire CAN_FIRE_RL_ifc_rl_init,
       CAN_FIRE_write_dm,
       CAN_FIRE_write_rd,
       WILL_FIRE_RL_ifc_rl_init,
       WILL_FIRE_write_dm,
       WILL_FIRE_write_rd;

  // value method read_rs1
  assign read_rs1 = (read_rs1_rs1 == 5'd0) ? 32'd0 : ifc_rf$D_OUT_3 ;
  assign RDY_read_rs1 = ifc_rg_init_index[5] ;

  // value method read_rs2
  assign read_rs2 = (read_rs2_rs2 == 5'd0) ? 32'd0 : ifc_rf$D_OUT_2 ;
  assign RDY_read_rs2 = ifc_rg_init_index[5] ;

  // action method write_rd
  assign RDY_write_rd = ifc_rg_init_index[5] ;
  assign CAN_FIRE_write_rd = ifc_rg_init_index[5] ;
  assign WILL_FIRE_write_rd = EN_write_rd ;

  // value method read_dm
  assign read_dm = (read_dm_rs == 5'd0) ? 32'd0 : ifc_rf$D_OUT_1 ;
  assign RDY_read_dm = ifc_rg_init_index[5] ;

  // action method write_dm
  assign RDY_write_dm = ifc_rg_init_index[5] ;
  assign CAN_FIRE_write_dm = ifc_rg_init_index[5] ;
  assign WILL_FIRE_write_dm = EN_write_dm ;

  // submodule ifc_rf
  RegFile #(.addr_width(32'd5),
	    .data_width(32'd32),
	    .lo(5'h0),
	    .hi(5'd31)) ifc_rf(.CLK(CLK),
			       .ADDR_1(ifc_rf$ADDR_1),
			       .ADDR_2(ifc_rf$ADDR_2),
			       .ADDR_3(ifc_rf$ADDR_3),
			       .ADDR_4(ifc_rf$ADDR_4),
			       .ADDR_5(ifc_rf$ADDR_5),
			       .ADDR_IN(ifc_rf$ADDR_IN),
			       .D_IN(ifc_rf$D_IN),
			       .WE(ifc_rf$WE),
			       .D_OUT_1(ifc_rf$D_OUT_1),
			       .D_OUT_2(ifc_rf$D_OUT_2),
			       .D_OUT_3(ifc_rf$D_OUT_3),
			       .D_OUT_4(),
			       .D_OUT_5());

  // rule RL_ifc_rl_init
  assign CAN_FIRE_RL_ifc_rl_init = !ifc_rg_init_index[5] ;
  assign WILL_FIRE_RL_ifc_rl_init = CAN_FIRE_RL_ifc_rl_init ;

  // register ifc_rg_init_index
  assign ifc_rg_init_index$D_IN = ifc_rg_init_index + 6'd1 ;
  assign ifc_rg_init_index$EN = CAN_FIRE_RL_ifc_rl_init ;

  // submodule ifc_rf
  assign ifc_rf$ADDR_1 = read_dm_rs ;
  assign ifc_rf$ADDR_2 = read_rs2_rs2 ;
  assign ifc_rf$ADDR_3 = read_rs1_rs1 ;
  assign ifc_rf$ADDR_4 = 5'h0 ;
  assign ifc_rf$ADDR_5 = 5'h0 ;
  always@(EN_write_rd or
	  write_rd_rd or
	  EN_write_dm or
	  write_dm_rd or WILL_FIRE_RL_ifc_rl_init or ifc_rg_init_index)
  begin
    case (1'b1) // synopsys parallel_case
      EN_write_rd: ifc_rf$ADDR_IN = write_rd_rd;
      EN_write_dm: ifc_rf$ADDR_IN = write_dm_rd;
      WILL_FIRE_RL_ifc_rl_init: ifc_rf$ADDR_IN = ifc_rg_init_index[4:0];
      default: ifc_rf$ADDR_IN = 5'bxxxxx /* unspecified value */ ;
    endcase
  end
  always@(EN_write_rd or
	  write_rd_rd_val or
	  EN_write_dm or write_dm_rd_val or WILL_FIRE_RL_ifc_rl_init)
  begin
    case (1'b1) // synopsys parallel_case
      EN_write_rd: ifc_rf$D_IN = write_rd_rd_val;
      EN_write_dm: ifc_rf$D_IN = write_dm_rd_val;
      WILL_FIRE_RL_ifc_rl_init: ifc_rf$D_IN = 32'd0;
      default: ifc_rf$D_IN =
		   32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
    endcase
  end
  assign ifc_rf$WE = EN_write_rd || EN_write_dm || WILL_FIRE_RL_ifc_rl_init ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        ifc_rg_init_index <= `BSV_ASSIGNMENT_DELAY 6'd0;
      end
    else
      begin
        if (ifc_rg_init_index$EN)
	  ifc_rg_init_index <= `BSV_ASSIGNMENT_DELAY ifc_rg_init_index$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    ifc_rg_init_index = 6'h2A;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_ifc_rl_init && ifc_rg_init_index == 6'd31)
	$display("GPRs: initialized to 0");
  end
  // synopsys translate_on
endmodule  // mkGPRs_synth

