//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:54 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_request_put                O     1 reg
// response_get                   O   486 reg
// RDY_response_get               O     1 reg
// verbosity                      I     2
// CLK                            I     1 clock
// RST_N                          I     1 reset
// request_put                    I    76
// EN_request_put                 I     1
// EN_response_get                I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkMultiplier(verbosity,
		    CLK,
		    RST_N,

		    request_put,
		    EN_request_put,
		    RDY_request_put,

		    EN_response_get,
		    response_get,
		    RDY_response_get);
  input  [1 : 0] verbosity;
  input  CLK;
  input  RST_N;

  // action method request_put
  input  [75 : 0] request_put;
  input  EN_request_put;
  output RDY_request_put;

  // actionvalue method response_get
  input  EN_response_get;
  output [485 : 0] response_get;
  output RDY_response_get;

  // signals for module outputs
  wire [485 : 0] response_get;
  wire RDY_request_put, RDY_response_get;

  // ports of submodule ff_pipe_reg
  wire [68 : 0] ff_pipe_reg$D_IN, ff_pipe_reg$D_OUT;
  wire ff_pipe_reg$CLR,
       ff_pipe_reg$DEQ,
       ff_pipe_reg$EMPTY_N,
       ff_pipe_reg$ENQ,
       ff_pipe_reg$FULL_N;

  // ports of submodule ff_to_quire
  wire [485 : 0] ff_to_quire$D_IN, ff_to_quire$D_OUT;
  wire ff_to_quire$CLR,
       ff_to_quire$DEQ,
       ff_to_quire$EMPTY_N,
       ff_to_quire$ENQ,
       ff_to_quire$FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_stage_1,
       CAN_FIRE_request_put,
       CAN_FIRE_response_get,
       WILL_FIRE_RL_stage_1,
       WILL_FIRE_request_put,
       WILL_FIRE_response_get;

  // declarations used by system tasks
  // synopsys translate_off
  reg [31 : 0] v__h5266;
  reg [31 : 0] v__h500;
  reg [31 : 0] x__h533;
  reg [31 : 0] x__h5299;
  reg [31 : 0] v__h492;
  reg [31 : 0] v__h5258;
  // synopsys translate_on

  // remaining internal signals
  wire [511 : 0] SEXT_ff_pipe_reg_first_BIT_65_CONCAT_IF_ff_pip_ETC___d51;
  wire [480 : 0] s_if__h698;
  wire [479 : 0] q_if___1__h327,
		 q_if__h301,
		 q_if__h398,
		 qif__h247,
		 shftamt__h326,
		 shftamt__h397;
  wire [239 : 0] q_f__h299;
  wire [111 : 0] _0_CONCAT_IF_request_put_BITS_75_TO_74_6_EQ_2_2_ETC___d89;
  wire [27 : 0] f1__h4664, f2__h4665;
  wire [8 : 0] SEXT_request_put_BITS_72_TO_65_8_9_PLUS_SEXT_r_ETC___d82,
	       ff_pipe_reg_first_BITS_64_TO_56_PLUS_1___d7,
	       x__h412;
  wire [7 : 0] request_put_BITS_34_TO_27__q2, request_put_BITS_72_TO_65__q1;
  wire [1 : 0] IF_request_put_BITS_75_TO_74_6_EQ_2_2_THEN_0b1_ETC___d73;
  wire NOT_verbosity_ULE_1_2_3_AND_verbosity_EQ_3_7_A_ETC___d119,
       NOT_verbosity_ULE_1_2___d23,
       stage0_regf_sign__h4571,
       x__h4679,
       x__h4681;

  // action method request_put
  assign RDY_request_put = ff_pipe_reg$FULL_N ;
  assign CAN_FIRE_request_put = ff_pipe_reg$FULL_N ;
  assign WILL_FIRE_request_put = EN_request_put ;

  // actionvalue method response_get
  assign response_get = ff_to_quire$D_OUT ;
  assign RDY_response_get = ff_to_quire$EMPTY_N ;
  assign CAN_FIRE_response_get = ff_to_quire$EMPTY_N ;
  assign WILL_FIRE_response_get = EN_response_get ;

  // submodule ff_pipe_reg
  FIFO1 #(.width(32'd69), .guarded(1'd1)) ff_pipe_reg(.RST(RST_N),
						      .CLK(CLK),
						      .D_IN(ff_pipe_reg$D_IN),
						      .ENQ(ff_pipe_reg$ENQ),
						      .DEQ(ff_pipe_reg$DEQ),
						      .CLR(ff_pipe_reg$CLR),
						      .D_OUT(ff_pipe_reg$D_OUT),
						      .FULL_N(ff_pipe_reg$FULL_N),
						      .EMPTY_N(ff_pipe_reg$EMPTY_N));

  // submodule ff_to_quire
  FIFO1 #(.width(32'd486), .guarded(1'd1)) ff_to_quire(.RST(RST_N),
						       .CLK(CLK),
						       .D_IN(ff_to_quire$D_IN),
						       .ENQ(ff_to_quire$ENQ),
						       .DEQ(ff_to_quire$DEQ),
						       .CLR(ff_to_quire$CLR),
						       .D_OUT(ff_to_quire$D_OUT),
						       .FULL_N(ff_to_quire$FULL_N),
						       .EMPTY_N(ff_to_quire$EMPTY_N));

  // rule RL_stage_1
  assign CAN_FIRE_RL_stage_1 = ff_pipe_reg$EMPTY_N && ff_to_quire$FULL_N ;
  assign WILL_FIRE_RL_stage_1 = CAN_FIRE_RL_stage_1 ;

  // submodule ff_pipe_reg
  assign ff_pipe_reg$D_IN =
	     { request_put[75:74] == 2'd1 && request_put[37:36] == 2'd2 ||
	       request_put[37:36] == 2'd1 && request_put[75:74] == 2'd2,
	       (request_put[75:74] == 2'd2 || request_put[37:36] == 2'd2) ?
		 2'd2 :
		 ((request_put[75:74] == 2'd1 || request_put[37:36] == 2'd1) ?
		    2'd1 :
		    2'd0),
	       stage0_regf_sign__h4571,
	       SEXT_request_put_BITS_72_TO_65_8_9_PLUS_SEXT_r_ETC___d82,
	       _0_CONCAT_IF_request_put_BITS_75_TO_74_6_EQ_2_2_ETC___d89[55:0] } ;
  assign ff_pipe_reg$ENQ = EN_request_put ;
  assign ff_pipe_reg$DEQ = CAN_FIRE_RL_stage_1 ;
  assign ff_pipe_reg$CLR = 1'b0 ;

  // submodule ff_to_quire
  assign ff_to_quire$D_IN =
	     { ff_pipe_reg$D_OUT[65],
	       qif__h247,
	       ff_pipe_reg$D_OUT[68:66],
	       2'd1 } ;
  assign ff_to_quire$ENQ = CAN_FIRE_RL_stage_1 ;
  assign ff_to_quire$DEQ = EN_response_get ;
  assign ff_to_quire$CLR = 1'b0 ;

  // remaining internal signals
  assign IF_request_put_BITS_75_TO_74_6_EQ_2_2_THEN_0b1_ETC___d73 =
	     (request_put[75:74] == 2'd2) ?
	       2'b01 :
	       ((request_put[37:36] == 2'd2) ? request_put[37:36] : 2'b11) ;
  assign NOT_verbosity_ULE_1_2_3_AND_verbosity_EQ_3_7_A_ETC___d119 =
	     NOT_verbosity_ULE_1_2___d23 && verbosity == 2'd3 &&
	     (request_put[75:74] == 2'd2 || request_put[37:36] == 2'd2 ||
	      request_put[75:74] == 2'd1 ||
	      request_put[37:36] == 2'd1) &&
	     (request_put[75:74] == 2'd2 || request_put[37:36] == 2'd2 ||
	      request_put[75:74] != 2'd1 && request_put[37:36] != 2'd1) ;
  assign NOT_verbosity_ULE_1_2___d23 = verbosity > 2'd1 ;
  assign SEXT_ff_pipe_reg_first_BIT_65_CONCAT_IF_ff_pip_ETC___d51 =
	     { {31{s_if__h698[480]}}, s_if__h698 } ;
  assign SEXT_request_put_BITS_72_TO_65_8_9_PLUS_SEXT_r_ETC___d82 =
	     { request_put_BITS_72_TO_65__q1[7],
	       request_put_BITS_72_TO_65__q1 } +
	     { request_put_BITS_34_TO_27__q2[7],
	       request_put_BITS_34_TO_27__q2 } ;
  assign _0_CONCAT_IF_request_put_BITS_75_TO_74_6_EQ_2_2_ETC___d89 =
	     { 28'd0, f1__h4664 } * { 28'd0, f2__h4665 } ;
  assign f1__h4664 =
	     { IF_request_put_BITS_75_TO_74_6_EQ_2_2_THEN_0b1_ETC___d73[1],
	       request_put[64:38] } ;
  assign f2__h4665 =
	     { IF_request_put_BITS_75_TO_74_6_EQ_2_2_THEN_0b1_ETC___d73[0],
	       request_put[26:0] } ;
  assign ff_pipe_reg_first_BITS_64_TO_56_PLUS_1___d7 =
	     ff_pipe_reg$D_OUT[64:56] + 9'd1 ;
  assign q_f__h299 = { ff_pipe_reg$D_OUT[55:0], 184'd0 } ;
  assign q_if___1__h327 = q_if__h301 << shftamt__h326 ;
  assign q_if__h301 = { 239'd0, q_f__h299, 1'd0 } ;
  assign q_if__h398 = q_if__h301 >> shftamt__h397 ;
  assign qif__h247 =
	     ff_pipe_reg_first_BITS_64_TO_56_PLUS_1___d7[8] ?
	       q_if__h398 :
	       q_if___1__h327 ;
  assign request_put_BITS_34_TO_27__q2 = request_put[34:27] ;
  assign request_put_BITS_72_TO_65__q1 = request_put[72:65] ;
  assign s_if__h698 =
	     { ff_pipe_reg$D_OUT[65],
	       ff_pipe_reg$D_OUT[65] ? ~qif__h247 + 480'd1 : qif__h247 } ;
  assign shftamt__h326 =
	     { 471'd0, ff_pipe_reg_first_BITS_64_TO_56_PLUS_1___d7 } ;
  assign shftamt__h397 = { 471'd0, x__h412 } ;
  assign stage0_regf_sign__h4571 =
	     x__h4679 &
	     IF_request_put_BITS_75_TO_74_6_EQ_2_2_THEN_0b1_ETC___d73[0] ;
  assign x__h412 =
	     ff_pipe_reg_first_BITS_64_TO_56_PLUS_1___d7[8] ?
	       -ff_pipe_reg_first_BITS_64_TO_56_PLUS_1___d7 :
	       ff_pipe_reg_first_BITS_64_TO_56_PLUS_1___d7 ;
  assign x__h4679 =
	     x__h4681 &
	     IF_request_put_BITS_75_TO_74_6_EQ_2_2_THEN_0b1_ETC___d73[1] ;
  assign x__h4681 = request_put[73] ^ request_put[35] ;

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23)
	begin
	  v__h5266 = $stime;
	  #0;
	end
    x__h5299 = v__h5266 + 32'd5;
    v__h5258 = x__h5299 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23)
	$display("%0d: %m.request: ", v__h5258);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23 && verbosity == 2'd3)
	$write("   ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23 && verbosity == 2'd3)
	$write("Mul_Stg1_In { ", "nan: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3 &&
	  (request_put[75:74] != 2'd1 || request_put[37:36] != 2'd2) &&
	  (request_put[37:36] != 2'd1 || request_put[75:74] != 2'd2))
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3 &&
	  (request_put[75:74] == 2'd1 && request_put[37:36] == 2'd2 ||
	   request_put[37:36] == 2'd1 && request_put[75:74] == 2'd2))
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23 && verbosity == 2'd3)
	$write(", ", "zi: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3 &&
	  request_put[75:74] != 2'd2 &&
	  request_put[37:36] != 2'd2 &&
	  request_put[75:74] != 2'd1 &&
	  request_put[37:36] != 2'd1)
	$write("REGULAR");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3 &&
	  request_put[75:74] != 2'd2 &&
	  request_put[37:36] != 2'd2 &&
	  (request_put[75:74] == 2'd1 || request_put[37:36] == 2'd1))
	$write("INF");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put &&
	  NOT_verbosity_ULE_1_2_3_AND_verbosity_EQ_3_7_A_ETC___d119)
	$write("ZERO");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23 && verbosity == 2'd3)
	$write(", ", "sign: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23 && verbosity == 2'd3)
	$write("'h%h", stage0_regf_sign__h4571);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23 && verbosity == 2'd3)
	$write(", ", "scale: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23 && verbosity == 2'd3)
	$write("%d",
	       $signed(SEXT_request_put_BITS_72_TO_65_8_9_PLUS_SEXT_r_ETC___d82));
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23 && verbosity == 2'd3)
	$write(", ", "frac: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23 && verbosity == 2'd3)
	$write("'h%h",
	       _0_CONCAT_IF_request_put_BITS_75_TO_74_6_EQ_2_2_ETC___d89[55:0],
	       " }");
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1_2___d23 && verbosity == 2'd3)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23)
	begin
	  v__h500 = $stime;
	  #0;
	end
    x__h533 = v__h500 + 32'd5;
    v__h492 = x__h533 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23)
	$display("%0d: %m.stage_1: ", v__h492);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3)
	$display("   frac_msb  : %0b", 1'b0);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3)
	$display("   frac_zero : %0b", 1'd1);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3)
	$write("   meta      : ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3)
	$write("Quire_Meta { ", "nan: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3 &&
	  ff_pipe_reg$D_OUT[68])
	$write("True");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3 &&
	  !ff_pipe_reg$D_OUT[68])
	$write("False");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3)
	$write(", ", "zi: ");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3 &&
	  ff_pipe_reg$D_OUT[67:66] == 2'd0)
	$write("REGULAR");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3 &&
	  ff_pipe_reg$D_OUT[67:66] == 2'd1)
	$write("INF");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3 &&
	  ff_pipe_reg$D_OUT[67:66] != 2'd0 &&
	  ff_pipe_reg$D_OUT[67:66] != 2'd1)
	$write("ZERO");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3)
	$write(" }");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3)
	$write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3)
	$display("   Quire fields:");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3)
	$display("      sign : %b",
		 SEXT_ff_pipe_reg_first_BIT_65_CONCAT_IF_ff_pip_ETC___d51[511]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3)
	$display("      carry: %0h",
		 SEXT_ff_pipe_reg_first_BIT_65_CONCAT_IF_ff_pip_ETC___d51[510:480]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3)
	$display("      int: %0h",
		 SEXT_ff_pipe_reg_first_BIT_65_CONCAT_IF_ff_pip_ETC___d51[479:240]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1_2___d23 &&
	  verbosity == 2'd3)
	$display("      frac: %0h",
		 SEXT_ff_pipe_reg_first_BIT_65_CONCAT_IF_ff_pip_ETC___d51[239:0]);
  end
  // synopsys translate_on
endmodule  // mkMultiplier

