//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:53 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_request_put                O     1 reg
// response_get                   O    36 reg
// RDY_response_get               O     1 reg
// verbosity                      I     2
// CLK                            I     1 clock
// RST_N                          I     1 reset
// request_put                    I    41
// EN_request_put                 I     1
// EN_response_get                I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkNormalizer(verbosity,
		    CLK,
		    RST_N,

		    request_put,
		    EN_request_put,
		    RDY_request_put,

		    EN_response_get,
		    response_get,
		    RDY_response_get);
  input  [1 : 0] verbosity;
  input  CLK;
  input  RST_N;

  // action method request_put
  input  [40 : 0] request_put;
  input  EN_request_put;
  output RDY_request_put;

  // actionvalue method response_get
  input  EN_response_get;
  output [35 : 0] response_get;
  output RDY_response_get;

  // signals for module outputs
  wire [35 : 0] response_get;
  wire RDY_request_put, RDY_response_get;

  // ports of submodule ff_o
  wire [35 : 0] ff_o$D_IN, ff_o$D_OUT;
  wire ff_o$CLR, ff_o$DEQ, ff_o$EMPTY_N, ff_o$ENQ, ff_o$FULL_N;

  // ports of submodule ff_stg1_in
  wire [69 : 0] ff_stg1_in$D_IN, ff_stg1_in$D_OUT;
  wire ff_stg1_in$CLR,
       ff_stg1_in$DEQ,
       ff_stg1_in$EMPTY_N,
       ff_stg1_in$ENQ,
       ff_stg1_in$FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_stage_1,
       CAN_FIRE_request_put,
       CAN_FIRE_response_get,
       WILL_FIRE_RL_stage_1,
       WILL_FIRE_request_put,
       WILL_FIRE_response_get;

  // remaining internal signals
  reg [31 : 0] output_regf_posit__h3073;
  reg truncated_frac_zero__h3180;
  wire [53 : 0] ext_shift_frac__h250,
		ff_stg1_in_first_BITS_34_TO_8_CONCAT_0_0_SRL_0_ETC___d14,
		long_frac__h249;
  wire [30 : 0] IF_IF_ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CO_ETC___d85,
		IF_ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CONCA_ETC___d61,
		IF_request_put_BIT_36_05_THEN_1_SL_30_MINUS_IN_ETC___d121,
		IF_request_put_BIT_36_05_THEN_1_SL_30_MINUS_IN_ETC___d147,
		b__h1705,
		b__h4409,
		b__h688,
		ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CONCAT_f_ETC___d57,
		k__h3561,
		k__h3601,
		k_expo__h3177,
		x__h3613,
		x__h704,
		y__h705,
		y__h706;
  wire [27 : 0] x__h6138;
  wire [26 : 0] request_put_BITS_28_TO_2__q2;
  wire [5 : 0] INV_request_put_BITS_36_TO_31_PLUS_1__q1;
  wire [4 : 0] IF_30_MINUS_IF_request_put_BIT_36_05_THEN_INV__ETC___d140,
	       IF_request_put_BIT_35_12_AND_NOT_request_put_B_ETC___d118,
	       IF_request_put_BIT_36_05_THEN_INV_request_put__ETC___d124,
	       _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d125,
	       request_put_BITS_35_TO_31_13_PLUS_1___d114,
	       x__h3599,
	       x__h4495,
	       x__h833;
  wire [2 : 0] _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d182,
	       _theResult___snd_snd__h4586,
	       i1__h6239,
	       i__h6184,
	       shift_frac__h3173,
	       shift_new__h4533,
	       x__h4537;
  wire [1 : 0] _theResult___fst__h4440,
	       expo_masked__h3174,
	       expo_new__h4505,
	       expo_new__h4534,
	       mask_e__h4438,
	       request_put_BITS_28_TO_2_56_BIT_IF_30_MINUS_IF_ETC___d180,
	       x__h6157;
  wire IF_NOT_ff_stg1_in_first_BITS_34_TO_8_CONCAT_0__ETC___d82,
       NOT_IF_request_put_BIT_36_05_THEN_1_SL_30_MINU_ETC___d152,
       NOT_ff_stg1_in_first_BIT_2_3_1_OR_IF_27_MINUS__ETC___d81,
       NOT_verbosity_ULE_1___d5,
       _27_MINUS_ff_stg1_in_first_BITS_7_TO_3_1_2_ULT_2___d35,
       _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d126,
       _theResult____h258,
       flag_prev_truncate__h254,
       request_put_BITS_28_TO_2_56_BIT_IF_30_MINUS_IF_ETC___d169,
       request_put_BIT_0_71_AND_INV_request_put_BIT_1_ETC___d178,
       truncated_frac_msb__h3179,
       x__h6171,
       x__h6232,
       y__h6233,
       y__h6235;

  // action method request_put
  assign RDY_request_put = ff_stg1_in$FULL_N ;
  assign CAN_FIRE_request_put = ff_stg1_in$FULL_N ;
  assign WILL_FIRE_request_put = EN_request_put ;

  // actionvalue method response_get
  assign response_get = ff_o$D_OUT ;
  assign RDY_response_get = ff_o$EMPTY_N ;
  assign CAN_FIRE_response_get = ff_o$EMPTY_N ;
  assign WILL_FIRE_response_get = EN_response_get ;

  // submodule ff_o
  FIFO1 #(.width(32'd36), .guarded(1'd1)) ff_o(.RST(RST_N),
					       .CLK(CLK),
					       .D_IN(ff_o$D_IN),
					       .ENQ(ff_o$ENQ),
					       .DEQ(ff_o$DEQ),
					       .CLR(ff_o$CLR),
					       .D_OUT(ff_o$D_OUT),
					       .FULL_N(ff_o$FULL_N),
					       .EMPTY_N(ff_o$EMPTY_N));

  // submodule ff_stg1_in
  FIFO1 #(.width(32'd70), .guarded(1'd1)) ff_stg1_in(.RST(RST_N),
						     .CLK(CLK),
						     .D_IN(ff_stg1_in$D_IN),
						     .ENQ(ff_stg1_in$ENQ),
						     .DEQ(ff_stg1_in$DEQ),
						     .CLR(ff_stg1_in$CLR),
						     .D_OUT(ff_stg1_in$D_OUT),
						     .FULL_N(ff_stg1_in$FULL_N),
						     .EMPTY_N(ff_stg1_in$EMPTY_N));

  // rule RL_stage_1
  assign CAN_FIRE_RL_stage_1 = ff_stg1_in$EMPTY_N && ff_o$FULL_N ;
  assign WILL_FIRE_RL_stage_1 = CAN_FIRE_RL_stage_1 ;

  // submodule ff_o
  assign ff_o$D_IN =
	     { output_regf_posit__h3073,
	       ff_stg1_in$D_OUT[68:66],
	       flag_prev_truncate__h254 - _theResult____h258 ||
	       IF_IF_ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CO_ETC___d85 ==
	       31'd0 &&
	       IF_NOT_ff_stg1_in_first_BITS_34_TO_8_CONCAT_0__ETC___d82 } ;
  assign ff_o$ENQ = CAN_FIRE_RL_stage_1 ;
  assign ff_o$DEQ = EN_response_get ;
  assign ff_o$CLR = 1'b0 ;

  // submodule ff_stg1_in
  assign ff_stg1_in$D_IN =
	     { request_put[40:37],
	       k_expo__h3177,
	       x__h6138[26:0],
	       IF_30_MINUS_IF_request_put_BIT_36_05_THEN_INV__ETC___d140,
	       _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d182 } ;
  assign ff_stg1_in$ENQ = EN_request_put ;
  assign ff_stg1_in$DEQ = CAN_FIRE_RL_stage_1 ;
  assign ff_stg1_in$CLR = 1'b0 ;

  // remaining internal signals
  assign IF_30_MINUS_IF_request_put_BIT_36_05_THEN_INV__ETC___d140 =
	     _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d126 ?
	       5'd0 :
	       _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d125 -
	       5'd2 ;
  assign IF_IF_ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CO_ETC___d85 =
	     (IF_ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CONCA_ETC___d61 ==
	      31'd0) ?
	       (IF_NOT_ff_stg1_in_first_BITS_34_TO_8_CONCAT_0__ETC___d82 ?
		  IF_ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CONCA_ETC___d61 +
		  31'd1 :
		  IF_ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CONCA_ETC___d61) :
	       IF_ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CONCA_ETC___d61 ;
  assign IF_NOT_ff_stg1_in_first_BITS_34_TO_8_CONCAT_0__ETC___d82 =
	     (!ff_stg1_in_first_BITS_34_TO_8_CONCAT_0_0_SRL_0_ETC___d14[26] &&
	      flag_prev_truncate__h254 &&
	      ff_stg1_in$D_OUT[0] &&
	      (ff_stg1_in$D_OUT[7:3] != 5'd0 || ~ff_stg1_in$D_OUT[35])) ?
	       x__h833 != 5'd0 && (x__h833 != 5'd1 || ff_stg1_in$D_OUT[1]) &&
	       (_27_MINUS_ff_stg1_in_first_BITS_7_TO_3_1_2_ULT_2___d35 ||
		ff_stg1_in_first_BITS_34_TO_8_CONCAT_0_0_SRL_0_ETC___d14[24:0] !=
		25'd0 ||
		ff_stg1_in$D_OUT[1]) :
	       NOT_ff_stg1_in_first_BIT_2_3_1_OR_IF_27_MINUS__ETC___d81 ;
  assign IF_ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CONCA_ETC___d61 =
	     (b__h688[30] &&
	      !ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CONCAT_f_ETC___d57[30]) ?
	       31'h7FFFFFFF :
	       ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CONCAT_f_ETC___d57 ;
  assign IF_request_put_BIT_35_12_AND_NOT_request_put_B_ETC___d118 =
	     (request_put[35] &&
	      !request_put_BITS_35_TO_31_13_PLUS_1___d114[4]) ?
	       5'd31 :
	       request_put_BITS_35_TO_31_13_PLUS_1___d114 ;
  assign IF_request_put_BIT_36_05_THEN_1_SL_30_MINUS_IN_ETC___d121 =
	     request_put[36] ? k__h3561 : k__h3601 ;
  assign IF_request_put_BIT_36_05_THEN_1_SL_30_MINUS_IN_ETC___d147 =
	     IF_request_put_BIT_36_05_THEN_1_SL_30_MINUS_IN_ETC___d121 +
	     b__h4409 ;
  assign IF_request_put_BIT_36_05_THEN_INV_request_put__ETC___d124 =
	     request_put[36] ?
	       INV_request_put_BITS_36_TO_31_PLUS_1__q1[4:0] :
	       IF_request_put_BIT_35_12_AND_NOT_request_put_B_ETC___d118 ;
  assign INV_request_put_BITS_36_TO_31_PLUS_1__q1 =
	     ~request_put[36:31] + 6'd1 ;
  assign NOT_IF_request_put_BIT_36_05_THEN_1_SL_30_MINU_ETC___d152 =
	     (!IF_request_put_BIT_36_05_THEN_1_SL_30_MINUS_IN_ETC___d121[30] &&
	      b__h4409[30] ||
	      IF_request_put_BIT_36_05_THEN_1_SL_30_MINUS_IN_ETC___d121[30] &&
	      !b__h4409[30]) &&
	     !IF_request_put_BIT_36_05_THEN_1_SL_30_MINUS_IN_ETC___d147[30] ||
	     IF_request_put_BIT_36_05_THEN_1_SL_30_MINUS_IN_ETC___d121[30] &&
	     b__h4409[30] ;
  assign NOT_ff_stg1_in_first_BIT_2_3_1_OR_IF_27_MINUS__ETC___d81 =
	     (!ff_stg1_in$D_OUT[2] ||
	      ((x__h833 == 5'd0) ?
		 !ff_stg1_in$D_OUT[1] :
		 !ff_stg1_in_first_BITS_34_TO_8_CONCAT_0_0_SRL_0_ETC___d14[26])) &&
	     (ff_stg1_in$D_OUT[65:35] != 31'h7FFFFFFF ||
	      ff_stg1_in$D_OUT[7:3] != 5'd0 ||
	      ff_stg1_in$D_OUT[34:8] != 27'd0 ||
	      !ff_stg1_in$D_OUT[0] ||
	      ff_stg1_in$D_OUT[1]) ;
  assign NOT_verbosity_ULE_1___d5 = verbosity > 2'd1 ;
  assign _27_MINUS_ff_stg1_in_first_BITS_7_TO_3_1_2_ULT_2___d35 =
	     x__h833 < 5'd2 ;
  assign _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d125 =
	     5'd30 -
	     IF_request_put_BIT_36_05_THEN_INV_request_put__ETC___d124 ;
  assign _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d126 =
	     _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d125 <
	     5'd2 ;
  assign _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d182 =
	     { x__h6171,
	       (shift_frac__h3173 == 3'd0) ?
		 request_put[1:0] :
		 request_put_BITS_28_TO_2_56_BIT_IF_30_MINUS_IF_ETC___d180 } ;
  assign _theResult____h258 =
	     (!ff_stg1_in_first_BITS_34_TO_8_CONCAT_0_0_SRL_0_ETC___d14[26] &&
	      flag_prev_truncate__h254 &&
	      ff_stg1_in$D_OUT[0] &&
	      (ff_stg1_in$D_OUT[7:3] != 5'd0 || ~ff_stg1_in$D_OUT[35])) ?
	       x__h833 == 5'd0 || x__h833 == 5'd1 && !ff_stg1_in$D_OUT[1] ||
	       !_27_MINUS_ff_stg1_in_first_BITS_7_TO_3_1_2_ULT_2___d35 &&
	       ff_stg1_in_first_BITS_34_TO_8_CONCAT_0_0_SRL_0_ETC___d14[24:0] ==
	       25'd0 &&
	       !ff_stg1_in$D_OUT[1] :
	       ff_stg1_in$D_OUT[2] && flag_prev_truncate__h254 ||
	       ff_stg1_in$D_OUT[65:35] == 31'h7FFFFFFF &&
	       ff_stg1_in$D_OUT[7:3] == 5'd0 &&
	       ff_stg1_in$D_OUT[34:8] == 27'd0 &&
	       ff_stg1_in$D_OUT[0] &&
	       !ff_stg1_in$D_OUT[1] ;
  assign _theResult___fst__h4440 =
	     ((request_put[30:29] & mask_e__h4438) == 2'd0) ?
	       expo_new__h4505 :
	       expo_new__h4534 ;
  assign _theResult___snd_snd__h4586 =
	     ((request_put[30:29] & mask_e__h4438) == 2'd0) ?
	       3'd0 :
	       shift_new__h4533 ;
  assign b__h1705 = { 30'd0, flag_prev_truncate__h254 } ;
  assign b__h4409 =
	     { 29'd0, expo_masked__h3174 } <<
	     IF_30_MINUS_IF_request_put_BIT_36_05_THEN_INV__ETC___d140 ;
  assign b__h688 = x__h704 - y__h705 ;
  assign expo_masked__h3174 =
	     _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d126 ?
	       _theResult___fst__h4440 :
	       request_put[30:29] ;
  assign expo_new__h4505 =
	     request_put[30:29] >>
	     _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d125 ;
  assign expo_new__h4534 = x__h4537[1:0] & request_put[30:29] ;
  assign ext_shift_frac__h250 = { 49'd0, x__h833 } ;
  assign ff_stg1_in_first_BITS_34_TO_8_CONCAT_0_0_SRL_0_ETC___d14 =
	     long_frac__h249 >> ext_shift_frac__h250 ;
  assign ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CONCAT_f_ETC___d57 =
	     b__h688 + b__h1705 ;
  assign flag_prev_truncate__h254 =
	     (x__h833 == 5'd0) ?
	       ff_stg1_in$D_OUT[1] :
	       ff_stg1_in_first_BITS_34_TO_8_CONCAT_0_0_SRL_0_ETC___d14[26] ;
  assign i1__h6239 = shift_frac__h3173 - 3'd2 ;
  assign i__h6184 = shift_frac__h3173 - 3'd1 ;
  assign k__h3561 = 31'd1 << x__h3599 ;
  assign k__h3601 = ~x__h3613 ;
  assign k_expo__h3177 =
	     NOT_IF_request_put_BIT_36_05_THEN_1_SL_30_MINU_ETC___d152 ?
	       31'h7FFFFFFF :
	       IF_request_put_BIT_36_05_THEN_1_SL_30_MINUS_IN_ETC___d147 ;
  assign long_frac__h249 = { ff_stg1_in$D_OUT[34:8], 27'd0 } ;
  assign mask_e__h4438 = 2'd3 >> x__h4495 ;
  assign request_put_BITS_28_TO_2_56_BIT_IF_30_MINUS_IF_ETC___d169 =
	     request_put_BITS_28_TO_2__q2[i__h6184] ;
  assign request_put_BITS_28_TO_2_56_BIT_IF_30_MINUS_IF_ETC___d180 =
	     { request_put_BITS_28_TO_2_56_BIT_IF_30_MINUS_IF_ETC___d169,
	       (shift_frac__h3173 == 3'd1) ?
		 x__h6232 :
		 request_put_BIT_0_71_AND_INV_request_put_BIT_1_ETC___d178 } ;
  assign request_put_BITS_28_TO_2__q2 = request_put[28:2] ;
  assign request_put_BITS_35_TO_31_13_PLUS_1___d114 =
	     request_put[35:31] + 5'd1 ;
  assign request_put_BIT_0_71_AND_INV_request_put_BIT_1_ETC___d178 =
	     x__h6232 & y__h6233 ;
  assign shift_frac__h3173 =
	     _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d126 ?
	       _theResult___snd_snd__h4586 :
	       3'd0 ;
  assign shift_new__h4533 = { 1'd0, x__h6157 } ;
  assign truncated_frac_msb__h3179 =
	     (shift_frac__h3173 == 3'd0) ?
	       request_put[1] :
	       request_put_BITS_28_TO_2_56_BIT_IF_30_MINUS_IF_ETC___d169 ;
  assign x__h3599 = 5'd30 - INV_request_put_BITS_36_TO_31_PLUS_1__q1[4:0] ;
  assign x__h3613 =
	     31'h7FFFFFFF >>
	     IF_request_put_BIT_35_12_AND_NOT_request_put_B_ETC___d118 ;
  assign x__h4495 =
	     5'd2 -
	     _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d125 ;
  assign x__h4537 =
	     3'd1 <<
	     _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d125 ;
  assign x__h6138 =
	     { _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d125 !=
	       5'd0,
	       request_put[28:2] } >>
	     shift_frac__h3173 ;
  assign x__h6157 = ~request_put[30:29] + 2'd1 ;
  assign x__h6171 =
	     _30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d125 ==
	     5'd0 &&
	     shift_frac__h3173 == 3'd0 ;
  assign x__h6232 = request_put[0] & y__h6235 ;
  assign x__h704 = ff_stg1_in$D_OUT[65:35] + y__h706 ;
  assign x__h833 = 5'd27 - ff_stg1_in$D_OUT[7:3] ;
  assign y__h6233 =
	     { 5'd0,
	       (request_put[28:2] & ~(27'h7FFFFFE << i1__h6239)) >> 0 } ==
	     32'd0 ;
  assign y__h6235 = ~request_put[1] ;
  assign y__h705 = { 30'd0, _theResult____h258 } ;
  assign y__h706 =
	     { 4'd0,
	       ff_stg1_in_first_BITS_34_TO_8_CONCAT_0_0_SRL_0_ETC___d14[53:27] } ;
  always@(ff_stg1_in$D_OUT or
	  IF_IF_ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CO_ETC___d85)
  begin
    case (ff_stg1_in$D_OUT[68:67])
      2'd0:
	  output_regf_posit__h3073 =
	      { ff_stg1_in$D_OUT[69],
		ff_stg1_in$D_OUT[69] ?
		  ~IF_IF_ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CO_ETC___d85 +
		  31'd1 :
		  IF_IF_ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CO_ETC___d85 };
      2'd1: output_regf_posit__h3073 = 32'h80000000;
      default: output_regf_posit__h3073 = 32'd0;
    endcase
  end
  always@(shift_frac__h3173 or
	  request_put_BIT_0_71_AND_INV_request_put_BIT_1_ETC___d178 or
	  request_put or x__h6232)
  begin
    case (shift_frac__h3173)
      3'd0: truncated_frac_zero__h3180 = request_put[0];
      3'd1: truncated_frac_zero__h3180 = x__h6232;
      default: truncated_frac_zero__h3180 =
		   request_put_BIT_0_71_AND_INV_request_put_BIT_1_ETC___d178;
    endcase
  end

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1___d5)
	$display("shift_exp %b shift_frac %b expo_new %b p.frac %b n_2_k %b expo %b truncated_frac_msb %b truncated_frac_zero %b ",
		 $unsigned(IF_30_MINUS_IF_request_put_BIT_36_05_THEN_INV__ETC___d140),
		 shift_frac__h3173,
		 expo_masked__h3174,
		 request_put[28:2],
		 $unsigned(_30_MINUS_IF_request_put_BIT_36_05_THEN_INV_req_ETC___d125),
		 request_put[30:29],
		 truncated_frac_msb__h3179,
		 truncated_frac_zero__h3180);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1___d5)
	$display("k %b",
		 IF_request_put_BIT_36_05_THEN_1_SL_30_MINUS_IN_ETC___d121);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1___d5)
	$display("no_of_bit_k %b",
		 $unsigned(IF_request_put_BIT_36_05_THEN_INV_request_put__ETC___d124));
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1___d5)
	$display("dIn.sign %b", ff_stg1_in$D_OUT[69]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1___d5)
	$display("dIn.k_expo %b dIn.frac %b uint_k_expo_frac %b dIn.flag_endcase %b",
		 ff_stg1_in$D_OUT[65:35],
		 ff_stg1_in$D_OUT[34:8],
		 $unsigned(IF_IF_ff_stg1_in_first_BITS_65_TO_35_PLUS_0_CO_ETC___d85),
		 ff_stg1_in$D_OUT[2]);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1___d5)
	$display(" dIn.shift_exp %b shift_frac %b flag_prev_truncate %b flag_equidistant %b",
		 $unsigned(ff_stg1_in$D_OUT[7:3]),
		 $unsigned(x__h833),
		 flag_prev_truncate__h254,
		 _theResult____h258);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_stage_1 && NOT_verbosity_ULE_1___d5)
	$display(" dIn.zero_infinity_flag %b", ff_stg1_in$D_OUT[68:67]);
  end
  // synopsys translate_on
endmodule  // mkNormalizer

