//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:57 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_server_core_request_put    O     1 reg
// server_core_response_get       O    71 reg
// RDY_server_core_response_get   O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// server_core_request_put        I   138 reg
// EN_server_core_request_put     I     1
// EN_server_core_response_get    I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkPositCore(CLK,
		   RST_N,

		   server_core_request_put,
		   EN_server_core_request_put,
		   RDY_server_core_request_put,

		   EN_server_core_response_get,
		   server_core_response_get,
		   RDY_server_core_response_get);
  input  CLK;
  input  RST_N;

  // action method server_core_request_put
  input  [137 : 0] server_core_request_put;
  input  EN_server_core_request_put;
  output RDY_server_core_request_put;

  // actionvalue method server_core_response_get
  input  EN_server_core_response_get;
  output [70 : 0] server_core_response_get;
  output RDY_server_core_response_get;

  // signals for module outputs
  wire [70 : 0] server_core_response_get;
  wire RDY_server_core_request_put, RDY_server_core_response_get;

  // register rg_inflight
  reg [7 : 0] rg_inflight;
  wire [7 : 0] rg_inflight$D_IN;
  wire rg_inflight$EN;

  // ports of submodule cmd_stg2_f
  wire [2 : 0] cmd_stg2_f$D_IN, cmd_stg2_f$D_OUT;
  wire cmd_stg2_f$CLR,
       cmd_stg2_f$DEQ,
       cmd_stg2_f$EMPTY_N,
       cmd_stg2_f$ENQ,
       cmd_stg2_f$FULL_N;

  // ports of submodule cmd_stg3_f
  wire [2 : 0] cmd_stg3_f$D_IN, cmd_stg3_f$D_OUT;
  wire cmd_stg3_f$CLR,
       cmd_stg3_f$DEQ,
       cmd_stg3_f$EMPTY_N,
       cmd_stg3_f$ENQ,
       cmd_stg3_f$FULL_N;

  // ports of submodule extracter1
  wire [37 : 0] extracter1$response_get;
  wire [31 : 0] extracter1$request_put;
  wire extracter1$EN_request_put,
       extracter1$EN_response_get,
       extracter1$RDY_request_put,
       extracter1$RDY_response_get;

  // ports of submodule extracter2
  wire [37 : 0] extracter2$response_get;
  wire [31 : 0] extracter2$request_put;
  wire extracter2$EN_request_put,
       extracter2$EN_response_get,
       extracter2$RDY_request_put,
       extracter2$RDY_response_get;

  // ports of submodule ffI
  wire [137 : 0] ffI$D_IN, ffI$D_OUT;
  wire ffI$CLR, ffI$DEQ, ffI$EMPTY_N, ffI$ENQ, ffI$FULL_N;

  // ports of submodule ffO
  wire [70 : 0] ffO$D_IN, ffO$D_OUT;
  wire ffO$CLR, ffO$DEQ, ffO$EMPTY_N, ffO$ENQ, ffO$FULL_N;

  // ports of submodule ftop
  wire [40 : 0] ftop$response_get;
  wire [31 : 0] ftop$request_put;
  wire ftop$EN_request_put,
       ftop$EN_response_get,
       ftop$RDY_request_put,
       ftop$RDY_response_get;

  // ports of submodule multiplier
  wire [485 : 0] multiplier$response_get;
  wire [75 : 0] multiplier$request_put;
  wire multiplier$EN_request_put,
       multiplier$EN_response_get,
       multiplier$RDY_request_put,
       multiplier$RDY_response_get;

  // ports of submodule normalizer
  wire [40 : 0] normalizer$request_put;
  wire [35 : 0] normalizer$response_get;
  wire normalizer$EN_request_put,
       normalizer$EN_response_get,
       normalizer$RDY_request_put,
       normalizer$RDY_response_get;

  // ports of submodule ptof
  wire [37 : 0] ptof$request_put;
  wire [34 : 0] ptof$response_get;
  wire ptof$EN_request_put,
       ptof$EN_response_get,
       ptof$RDY_request_put,
       ptof$RDY_response_get;

  // ports of submodule quire
  wire [485 : 0] quire$accumulate_x;
  wire [40 : 0] quire$read_rsp_get;
  wire [37 : 0] quire$init_x;
  wire quire$EN_accumulate,
       quire$EN_init,
       quire$EN_read_req,
       quire$EN_read_rsp_get,
       quire$RDY_accumulate,
       quire$RDY_init,
       quire$RDY_read_req,
       quire$RDY_read_rsp_get;

  // rule scheduling signals
  wire CAN_FIRE_RL_extract_stg1,
       CAN_FIRE_RL_rl_float_to_posit_stg1,
       CAN_FIRE_RL_rl_float_to_posit_stg2,
       CAN_FIRE_RL_rl_float_to_posit_stg3,
       CAN_FIRE_RL_rl_fma_stg2,
       CAN_FIRE_RL_rl_fma_stg3,
       CAN_FIRE_RL_rl_init_quire_stg2,
       CAN_FIRE_RL_rl_posit_to_float_stg2,
       CAN_FIRE_RL_rl_posit_to_float_stg3,
       CAN_FIRE_RL_rl_read_quire_stg1,
       CAN_FIRE_RL_rl_read_quire_stg2,
       CAN_FIRE_RL_rl_read_quire_stg3,
       CAN_FIRE_server_core_request_put,
       CAN_FIRE_server_core_response_get,
       WILL_FIRE_RL_extract_stg1,
       WILL_FIRE_RL_rl_float_to_posit_stg1,
       WILL_FIRE_RL_rl_float_to_posit_stg2,
       WILL_FIRE_RL_rl_float_to_posit_stg3,
       WILL_FIRE_RL_rl_fma_stg2,
       WILL_FIRE_RL_rl_fma_stg3,
       WILL_FIRE_RL_rl_init_quire_stg2,
       WILL_FIRE_RL_rl_posit_to_float_stg2,
       WILL_FIRE_RL_rl_posit_to_float_stg3,
       WILL_FIRE_RL_rl_read_quire_stg1,
       WILL_FIRE_RL_rl_read_quire_stg2,
       WILL_FIRE_RL_rl_read_quire_stg3,
       WILL_FIRE_server_core_request_put,
       WILL_FIRE_server_core_response_get;

  // inputs to muxes for submodule ports
  wire [70 : 0] MUX_ffO$enq_1__VAL_1, MUX_ffO$enq_1__VAL_2;
  wire [7 : 0] MUX_rg_inflight$write_1__VAL_1, MUX_rg_inflight$write_1__VAL_2;
  wire MUX_ffO$enq_1__SEL_1, MUX_rg_inflight$write_1__SEL_1;

  // declarations used by system tasks
  // synopsys translate_off
  reg [31 : 0] v__h1211;
  reg [31 : 0] v__h1515;
  reg [31 : 0] v__h1662;
  reg [31 : 0] v__h1922;
  reg [31 : 0] v__h2141;
  reg [31 : 0] v__h2368;
  reg [31 : 0] v__h2815;
  reg [31 : 0] v__h3075;
  reg [31 : 0] v__h2599;
  reg [31 : 0] v__h3610;
  reg [31 : 0] v__h3841;
  reg [31 : 0] v__h4062;
  reg [31 : 0] x__h1244;
  reg [31 : 0] x__h1548;
  reg [31 : 0] x__h1695;
  reg [31 : 0] x__h1955;
  reg [31 : 0] x__h2174;
  reg [31 : 0] x__h2401;
  reg [31 : 0] x__h2632;
  reg [31 : 0] x__h2848;
  reg [31 : 0] x__h3108;
  reg [31 : 0] x__h3643;
  reg [31 : 0] x__h3874;
  reg [31 : 0] x__h4095;
  reg [31 : 0] v__h1203;
  reg [31 : 0] v__h1507;
  reg [31 : 0] v__h1654;
  reg [31 : 0] v__h1914;
  reg [31 : 0] v__h2133;
  reg [31 : 0] v__h2360;
  reg [31 : 0] v__h2591;
  reg [31 : 0] v__h2807;
  reg [31 : 0] v__h3067;
  reg [31 : 0] v__h3602;
  reg [31 : 0] v__h3833;
  reg [31 : 0] v__h4054;
  // synopsys translate_on

  // action method server_core_request_put
  assign RDY_server_core_request_put = ffI$FULL_N ;
  assign CAN_FIRE_server_core_request_put = ffI$FULL_N ;
  assign WILL_FIRE_server_core_request_put = EN_server_core_request_put ;

  // actionvalue method server_core_response_get
  assign server_core_response_get = ffO$D_OUT ;
  assign RDY_server_core_response_get = ffO$EMPTY_N ;
  assign CAN_FIRE_server_core_response_get = ffO$EMPTY_N ;
  assign WILL_FIRE_server_core_response_get = EN_server_core_response_get ;

  // submodule cmd_stg2_f
  FIFO2 #(.width(32'd3), .guarded(1'd1)) cmd_stg2_f(.RST(RST_N),
						    .CLK(CLK),
						    .D_IN(cmd_stg2_f$D_IN),
						    .ENQ(cmd_stg2_f$ENQ),
						    .DEQ(cmd_stg2_f$DEQ),
						    .CLR(cmd_stg2_f$CLR),
						    .D_OUT(cmd_stg2_f$D_OUT),
						    .FULL_N(cmd_stg2_f$FULL_N),
						    .EMPTY_N(cmd_stg2_f$EMPTY_N));

  // submodule cmd_stg3_f
  FIFO2 #(.width(32'd3), .guarded(1'd1)) cmd_stg3_f(.RST(RST_N),
						    .CLK(CLK),
						    .D_IN(cmd_stg3_f$D_IN),
						    .ENQ(cmd_stg3_f$ENQ),
						    .DEQ(cmd_stg3_f$DEQ),
						    .CLR(cmd_stg3_f$CLR),
						    .D_OUT(cmd_stg3_f$D_OUT),
						    .FULL_N(cmd_stg3_f$FULL_N),
						    .EMPTY_N(cmd_stg3_f$EMPTY_N));

  // submodule extracter1
  mkExtracter extracter1(.verbosity(2'd2),
			 .CLK(CLK),
			 .RST_N(RST_N),
			 .request_put(extracter1$request_put),
			 .EN_request_put(extracter1$EN_request_put),
			 .EN_response_get(extracter1$EN_response_get),
			 .RDY_request_put(extracter1$RDY_request_put),
			 .response_get(extracter1$response_get),
			 .RDY_response_get(extracter1$RDY_response_get));

  // submodule extracter2
  mkExtracter extracter2(.verbosity(2'd2),
			 .CLK(CLK),
			 .RST_N(RST_N),
			 .request_put(extracter2$request_put),
			 .EN_request_put(extracter2$EN_request_put),
			 .EN_response_get(extracter2$EN_response_get),
			 .RDY_request_put(extracter2$RDY_request_put),
			 .response_get(extracter2$response_get),
			 .RDY_response_get(extracter2$RDY_response_get));

  // submodule ffI
  FIFO2 #(.width(32'd138), .guarded(1'd1)) ffI(.RST(RST_N),
					       .CLK(CLK),
					       .D_IN(ffI$D_IN),
					       .ENQ(ffI$ENQ),
					       .DEQ(ffI$DEQ),
					       .CLR(ffI$CLR),
					       .D_OUT(ffI$D_OUT),
					       .FULL_N(ffI$FULL_N),
					       .EMPTY_N(ffI$EMPTY_N));

  // submodule ffO
  FIFO1 #(.width(32'd71), .guarded(1'd1)) ffO(.RST(RST_N),
					      .CLK(CLK),
					      .D_IN(ffO$D_IN),
					      .ENQ(ffO$ENQ),
					      .DEQ(ffO$DEQ),
					      .CLR(ffO$CLR),
					      .D_OUT(ffO$D_OUT),
					      .FULL_N(ffO$FULL_N),
					      .EMPTY_N(ffO$EMPTY_N));

  // submodule ftop
  mkFtoP_PNE ftop(.verbosity(2'd2),
		  .CLK(CLK),
		  .RST_N(RST_N),
		  .request_put(ftop$request_put),
		  .EN_request_put(ftop$EN_request_put),
		  .EN_response_get(ftop$EN_response_get),
		  .RDY_request_put(ftop$RDY_request_put),
		  .response_get(ftop$response_get),
		  .RDY_response_get(ftop$RDY_response_get));

  // submodule multiplier
  mkMultiplier multiplier(.verbosity(2'd2),
			  .CLK(CLK),
			  .RST_N(RST_N),
			  .request_put(multiplier$request_put),
			  .EN_request_put(multiplier$EN_request_put),
			  .EN_response_get(multiplier$EN_response_get),
			  .RDY_request_put(multiplier$RDY_request_put),
			  .response_get(multiplier$response_get),
			  .RDY_response_get(multiplier$RDY_response_get));

  // submodule normalizer
  mkNormalizer normalizer(.verbosity(2'd2),
			  .CLK(CLK),
			  .RST_N(RST_N),
			  .request_put(normalizer$request_put),
			  .EN_request_put(normalizer$EN_request_put),
			  .EN_response_get(normalizer$EN_response_get),
			  .RDY_request_put(normalizer$RDY_request_put),
			  .response_get(normalizer$response_get),
			  .RDY_response_get(normalizer$RDY_response_get));

  // submodule ptof
  mkPtoF_PNE ptof(.verbosity(2'd2),
		  .CLK(CLK),
		  .RST_N(RST_N),
		  .request_put(ptof$request_put),
		  .EN_request_put(ptof$EN_request_put),
		  .EN_response_get(ptof$EN_response_get),
		  .RDY_request_put(ptof$RDY_request_put),
		  .response_get(ptof$response_get),
		  .RDY_response_get(ptof$RDY_response_get));

  // submodule quire
  mkQuire quire(.verbosity(2'd2),
		.CLK(CLK),
		.RST_N(RST_N),
		.accumulate_x(quire$accumulate_x),
		.init_x(quire$init_x),
		.EN_accumulate(quire$EN_accumulate),
		.EN_init(quire$EN_init),
		.EN_read_req(quire$EN_read_req),
		.EN_read_rsp_get(quire$EN_read_rsp_get),
		.RDY_accumulate(quire$RDY_accumulate),
		.RDY_init(quire$RDY_init),
		.RDY_read_req(quire$RDY_read_req),
		.read_rsp_get(quire$read_rsp_get),
		.RDY_read_rsp_get(quire$RDY_read_rsp_get));

  // rule RL_extract_stg1
  assign CAN_FIRE_RL_extract_stg1 =
	     extracter1$RDY_request_put && extracter2$RDY_request_put &&
	     ffI$EMPTY_N &&
	     cmd_stg2_f$FULL_N &&
	     ffI$D_OUT[2:0] != 3'd2 &&
	     ffI$D_OUT[2:0] != 3'd4 ;
  assign WILL_FIRE_RL_extract_stg1 = CAN_FIRE_RL_extract_stg1 ;

  // rule RL_rl_float_to_posit_stg1
  assign CAN_FIRE_RL_rl_float_to_posit_stg1 =
	     ftop$RDY_request_put && ffI$EMPTY_N && cmd_stg2_f$FULL_N &&
	     ffI$D_OUT[2:0] == 3'd2 ;
  assign WILL_FIRE_RL_rl_float_to_posit_stg1 =
	     CAN_FIRE_RL_rl_float_to_posit_stg1 ;

  // rule RL_rl_read_quire_stg1
  assign CAN_FIRE_RL_rl_read_quire_stg1 =
	     quire$RDY_read_req && ffI$EMPTY_N && cmd_stg2_f$FULL_N &&
	     rg_inflight == 8'd0 &&
	     ffI$D_OUT[2:0] == 3'd4 ;
  assign WILL_FIRE_RL_rl_read_quire_stg1 = CAN_FIRE_RL_rl_read_quire_stg1 ;

  // rule RL_rl_fma_stg2
  assign CAN_FIRE_RL_rl_fma_stg2 =
	     extracter1$RDY_response_get && extracter2$RDY_response_get &&
	     multiplier$RDY_request_put &&
	     cmd_stg2_f$EMPTY_N &&
	     cmd_stg3_f$FULL_N &&
	     (cmd_stg2_f$D_OUT == 3'd0 || cmd_stg2_f$D_OUT == 3'd1) ;
  assign WILL_FIRE_RL_rl_fma_stg2 = CAN_FIRE_RL_rl_fma_stg2 ;

  // rule RL_rl_posit_to_float_stg2
  assign CAN_FIRE_RL_rl_posit_to_float_stg2 =
	     extracter1$RDY_response_get && extracter2$RDY_response_get &&
	     ptof$RDY_request_put &&
	     cmd_stg2_f$EMPTY_N &&
	     cmd_stg3_f$FULL_N &&
	     cmd_stg2_f$D_OUT == 3'd3 ;
  assign WILL_FIRE_RL_rl_posit_to_float_stg2 =
	     CAN_FIRE_RL_rl_posit_to_float_stg2 ;

  // rule RL_rl_float_to_posit_stg2
  assign CAN_FIRE_RL_rl_float_to_posit_stg2 =
	     ftop$RDY_response_get && normalizer$RDY_request_put &&
	     cmd_stg2_f$EMPTY_N &&
	     cmd_stg3_f$FULL_N &&
	     cmd_stg2_f$D_OUT == 3'd2 ;
  assign WILL_FIRE_RL_rl_float_to_posit_stg2 =
	     CAN_FIRE_RL_rl_float_to_posit_stg2 ;

  // rule RL_rl_read_quire_stg2
  assign CAN_FIRE_RL_rl_read_quire_stg2 =
	     normalizer$RDY_request_put && quire$RDY_read_rsp_get &&
	     cmd_stg2_f$EMPTY_N &&
	     cmd_stg3_f$FULL_N &&
	     cmd_stg2_f$D_OUT == 3'd4 ;
  assign WILL_FIRE_RL_rl_read_quire_stg2 = CAN_FIRE_RL_rl_read_quire_stg2 ;

  // rule RL_rl_fma_stg3
  assign CAN_FIRE_RL_rl_fma_stg3 =
	     multiplier$RDY_response_get && quire$RDY_accumulate &&
	     cmd_stg3_f$EMPTY_N &&
	     (cmd_stg3_f$D_OUT == 3'd0 || cmd_stg3_f$D_OUT == 3'd1) ;
  assign WILL_FIRE_RL_rl_fma_stg3 =
	     CAN_FIRE_RL_rl_fma_stg3 && !WILL_FIRE_RL_rl_init_quire_stg2 &&
	     !WILL_FIRE_RL_rl_read_quire_stg1 &&
	     !WILL_FIRE_RL_extract_stg1 ;

  // rule RL_rl_init_quire_stg2
  assign CAN_FIRE_RL_rl_init_quire_stg2 =
	     quire$RDY_init && extracter1$RDY_response_get &&
	     extracter2$RDY_response_get &&
	     cmd_stg2_f$EMPTY_N &&
	     cmd_stg2_f$D_OUT == 3'd5 ;
  assign WILL_FIRE_RL_rl_init_quire_stg2 =
	     CAN_FIRE_RL_rl_init_quire_stg2 &&
	     !WILL_FIRE_RL_rl_read_quire_stg1 &&
	     !WILL_FIRE_RL_extract_stg1 ;

  // rule RL_rl_posit_to_float_stg3
  assign CAN_FIRE_RL_rl_posit_to_float_stg3 =
	     ptof$RDY_response_get && cmd_stg3_f$EMPTY_N && ffO$FULL_N &&
	     cmd_stg3_f$D_OUT == 3'd3 ;
  assign WILL_FIRE_RL_rl_posit_to_float_stg3 =
	     CAN_FIRE_RL_rl_posit_to_float_stg3 ;

  // rule RL_rl_float_to_posit_stg3
  assign CAN_FIRE_RL_rl_float_to_posit_stg3 =
	     normalizer$RDY_response_get && cmd_stg3_f$EMPTY_N &&
	     ffO$FULL_N &&
	     cmd_stg3_f$D_OUT == 3'd2 ;
  assign WILL_FIRE_RL_rl_float_to_posit_stg3 =
	     CAN_FIRE_RL_rl_float_to_posit_stg3 ;

  // rule RL_rl_read_quire_stg3
  assign CAN_FIRE_RL_rl_read_quire_stg3 =
	     normalizer$RDY_response_get && cmd_stg3_f$EMPTY_N &&
	     ffO$FULL_N &&
	     cmd_stg3_f$D_OUT == 3'd4 ;
  assign WILL_FIRE_RL_rl_read_quire_stg3 = CAN_FIRE_RL_rl_read_quire_stg3 ;

  // inputs to muxes for submodule ports
  assign MUX_ffO$enq_1__SEL_1 =
	     WILL_FIRE_RL_rl_read_quire_stg3 ||
	     WILL_FIRE_RL_rl_float_to_posit_stg3 ;
  assign MUX_rg_inflight$write_1__SEL_1 =
	     WILL_FIRE_RL_extract_stg1 &&
	     (ffI$D_OUT[2:0] == 3'd0 || ffI$D_OUT[2:0] == 3'd1 ||
	      ffI$D_OUT[2:0] == 3'd5) ;
  assign MUX_ffO$enq_1__VAL_1 =
	     { 2'd2,
	       32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ,
	       normalizer$response_get[35:4],
	       normalizer$response_get[1],
	       1'd0,
	       normalizer$response_get[3:2] == 2'd1,
	       normalizer$response_get[3:2] == 2'd2 &&
	       normalizer$response_get[0],
	       normalizer$response_get[0] } ;
  assign MUX_ffO$enq_1__VAL_2 =
	     { 2'd1,
	       32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ,
	       ptof$response_get[34:3],
	       2'd0,
	       ptof$response_get[2:1] == 2'd1,
	       ptof$response_get[2:1] == 2'd2 && ptof$response_get[0],
	       ptof$response_get[0] } ;
  assign MUX_rg_inflight$write_1__VAL_1 = rg_inflight + 8'd1 ;
  assign MUX_rg_inflight$write_1__VAL_2 = rg_inflight - 8'd1 ;

  // register rg_inflight
  assign rg_inflight$D_IN =
	     MUX_rg_inflight$write_1__SEL_1 ?
	       MUX_rg_inflight$write_1__VAL_1 :
	       MUX_rg_inflight$write_1__VAL_2 ;
  assign rg_inflight$EN =
	     WILL_FIRE_RL_extract_stg1 &&
	     (ffI$D_OUT[2:0] == 3'd0 || ffI$D_OUT[2:0] == 3'd1 ||
	      ffI$D_OUT[2:0] == 3'd5) ||
	     WILL_FIRE_RL_rl_fma_stg3 ||
	     WILL_FIRE_RL_rl_init_quire_stg2 ;

  // submodule cmd_stg2_f
  assign cmd_stg2_f$D_IN = ffI$D_OUT[2:0] ;
  assign cmd_stg2_f$ENQ =
	     WILL_FIRE_RL_rl_read_quire_stg1 ||
	     WILL_FIRE_RL_rl_float_to_posit_stg1 ||
	     WILL_FIRE_RL_extract_stg1 ;
  assign cmd_stg2_f$DEQ =
	     WILL_FIRE_RL_rl_read_quire_stg2 ||
	     WILL_FIRE_RL_rl_init_quire_stg2 ||
	     WILL_FIRE_RL_rl_float_to_posit_stg2 ||
	     WILL_FIRE_RL_rl_posit_to_float_stg2 ||
	     WILL_FIRE_RL_rl_fma_stg2 ;
  assign cmd_stg2_f$CLR = 1'b0 ;

  // submodule cmd_stg3_f
  assign cmd_stg3_f$D_IN = cmd_stg2_f$D_OUT ;
  assign cmd_stg3_f$ENQ =
	     WILL_FIRE_RL_rl_read_quire_stg2 ||
	     WILL_FIRE_RL_rl_float_to_posit_stg2 ||
	     WILL_FIRE_RL_rl_posit_to_float_stg2 ||
	     WILL_FIRE_RL_rl_fma_stg2 ;
  assign cmd_stg3_f$DEQ =
	     WILL_FIRE_RL_rl_read_quire_stg3 ||
	     WILL_FIRE_RL_rl_float_to_posit_stg3 ||
	     WILL_FIRE_RL_rl_posit_to_float_stg3 ||
	     WILL_FIRE_RL_rl_fma_stg3 ;
  assign cmd_stg3_f$CLR = 1'b0 ;

  // submodule extracter1
  assign extracter1$request_put = ffI$D_OUT[103:72] ;
  assign extracter1$EN_request_put = CAN_FIRE_RL_extract_stg1 ;
  assign extracter1$EN_response_get =
	     WILL_FIRE_RL_rl_init_quire_stg2 ||
	     WILL_FIRE_RL_rl_posit_to_float_stg2 ||
	     WILL_FIRE_RL_rl_fma_stg2 ;

  // submodule extracter2
  assign extracter2$request_put =
	     (ffI$D_OUT[2:0] == 3'd1) ?
	       ~ffI$D_OUT[37:6] + 32'd1 :
	       ffI$D_OUT[37:6] ;
  assign extracter2$EN_request_put = CAN_FIRE_RL_extract_stg1 ;
  assign extracter2$EN_response_get =
	     WILL_FIRE_RL_rl_init_quire_stg2 ||
	     WILL_FIRE_RL_rl_posit_to_float_stg2 ||
	     WILL_FIRE_RL_rl_fma_stg2 ;

  // submodule ffI
  assign ffI$D_IN = server_core_request_put ;
  assign ffI$ENQ = EN_server_core_request_put ;
  assign ffI$DEQ =
	     WILL_FIRE_RL_rl_read_quire_stg1 ||
	     WILL_FIRE_RL_rl_float_to_posit_stg1 ||
	     WILL_FIRE_RL_extract_stg1 ;
  assign ffI$CLR = 1'b0 ;

  // submodule ffO
  assign ffO$D_IN =
	     MUX_ffO$enq_1__SEL_1 ?
	       MUX_ffO$enq_1__VAL_1 :
	       MUX_ffO$enq_1__VAL_2 ;
  assign ffO$ENQ =
	     WILL_FIRE_RL_rl_read_quire_stg3 ||
	     WILL_FIRE_RL_rl_float_to_posit_stg3 ||
	     WILL_FIRE_RL_rl_posit_to_float_stg3 ;
  assign ffO$DEQ = EN_server_core_response_get ;
  assign ffO$CLR = 1'b0 ;

  // submodule ftop
  assign ftop$request_put = ffI$D_OUT[103:72] ;
  assign ftop$EN_request_put = CAN_FIRE_RL_rl_float_to_posit_stg1 ;
  assign ftop$EN_response_get = CAN_FIRE_RL_rl_float_to_posit_stg2 ;

  // submodule multiplier
  assign multiplier$request_put =
	     { extracter1$response_get, extracter2$response_get } ;
  assign multiplier$EN_request_put = CAN_FIRE_RL_rl_fma_stg2 ;
  assign multiplier$EN_response_get = WILL_FIRE_RL_rl_fma_stg3 ;

  // submodule normalizer
  assign normalizer$request_put =
	     WILL_FIRE_RL_rl_float_to_posit_stg2 ?
	       ftop$response_get :
	       quire$read_rsp_get ;
  assign normalizer$EN_request_put =
	     WILL_FIRE_RL_rl_float_to_posit_stg2 ||
	     WILL_FIRE_RL_rl_read_quire_stg2 ;
  assign normalizer$EN_response_get = MUX_ffO$enq_1__SEL_1 ;

  // submodule ptof
  assign ptof$request_put = extracter1$response_get ;
  assign ptof$EN_request_put = CAN_FIRE_RL_rl_posit_to_float_stg2 ;
  assign ptof$EN_response_get = CAN_FIRE_RL_rl_posit_to_float_stg3 ;

  // submodule quire
  assign quire$accumulate_x = multiplier$response_get ;
  assign quire$init_x = extracter1$response_get ;
  assign quire$EN_accumulate = WILL_FIRE_RL_rl_fma_stg3 ;
  assign quire$EN_init = WILL_FIRE_RL_rl_init_quire_stg2 ;
  assign quire$EN_read_req = CAN_FIRE_RL_rl_read_quire_stg1 ;
  assign quire$EN_read_rsp_get = CAN_FIRE_RL_rl_read_quire_stg2 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        rg_inflight <= `BSV_ASSIGNMENT_DELAY 8'd0;
      end
    else
      begin
        if (rg_inflight$EN)
	  rg_inflight <= `BSV_ASSIGNMENT_DELAY rg_inflight$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    rg_inflight = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_extract_stg1)
	begin
	  v__h1211 = $stime;
	  #0;
	end
    x__h1244 = v__h1211 + 32'd5;
    v__h1203 = x__h1244 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_extract_stg1)
	$write("%0d: %m: rl_extract_stg1: ", v__h1203);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_extract_stg1 && ffI$D_OUT[2:0] == 3'd0)
	$write("FMA_P");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_extract_stg1 && ffI$D_OUT[2:0] == 3'd1)
	$write("FMS_P");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_extract_stg1 && ffI$D_OUT[2:0] == 3'd3)
	$write("FCVT_S_P");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_extract_stg1 && ffI$D_OUT[2:0] != 3'd0 &&
	  ffI$D_OUT[2:0] != 3'd1 &&
	  ffI$D_OUT[2:0] != 3'd3)
	$write("FCVT_R_P");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_extract_stg1) $write("\n");
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_float_to_posit_stg1)
	begin
	  v__h1515 = $stime;
	  #0;
	end
    x__h1548 = v__h1515 + 32'd5;
    v__h1507 = x__h1548 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_float_to_posit_stg1)
	$display("%0d: %m.rl_float_to_posit_stg1: convert ", v__h1507);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_read_quire_stg1)
	begin
	  v__h1662 = $stime;
	  #0;
	end
    x__h1695 = v__h1662 + 32'd5;
    v__h1654 = x__h1695 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_read_quire_stg1)
	$display("%0d: %m.rl_read_quire_stg1: read ", v__h1654);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_fma_stg2)
	begin
	  v__h1922 = $stime;
	  #0;
	end
    x__h1955 = v__h1922 + 32'd5;
    v__h1914 = x__h1955 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_fma_stg2)
	$display("%0d: %m.rl_fma_stg2: multiply ", v__h1914);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_posit_to_float_stg2)
	begin
	  v__h2141 = $stime;
	  #0;
	end
    x__h2174 = v__h2141 + 32'd5;
    v__h2133 = x__h2174 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_posit_to_float_stg2)
	$display("%0d: %m.rl_posit_to_float_stg2: convert ", v__h2133);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_float_to_posit_stg2)
	begin
	  v__h2368 = $stime;
	  #0;
	end
    x__h2401 = v__h2368 + 32'd5;
    v__h2360 = x__h2401 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_float_to_posit_stg2)
	$display("%0d: %m.rl_float_to_posit_stg2: normalize ", v__h2360);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_read_quire_stg2)
	begin
	  v__h2815 = $stime;
	  #0;
	end
    x__h2848 = v__h2815 + 32'd5;
    v__h2807 = x__h2848 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_read_quire_stg2)
	$display("%0d: %m.rl_read_quire_stg2: normalize ", v__h2807);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_fma_stg3)
	begin
	  v__h3075 = $stime;
	  #0;
	end
    x__h3108 = v__h3075 + 32'd5;
    v__h3067 = x__h3108 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_fma_stg3)
	$display("%0d: %m.rl_fma_stg3: accumulate ", v__h3067);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_init_quire_stg2)
	begin
	  v__h2599 = $stime;
	  #0;
	end
    x__h2632 = v__h2599 + 32'd5;
    v__h2591 = x__h2632 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_init_quire_stg2)
	$display("%0d: %m.rl_init_quire_stg2: initialize ", v__h2591);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_posit_to_float_stg3)
	begin
	  v__h3610 = $stime;
	  #0;
	end
    x__h3643 = v__h3610 + 32'd5;
    v__h3602 = x__h3643 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_posit_to_float_stg3)
	$display("%0d: %m.rl_posit_to_float_stg3: out ", v__h3602);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_float_to_posit_stg3)
	begin
	  v__h3841 = $stime;
	  #0;
	end
    x__h3874 = v__h3841 + 32'd5;
    v__h3833 = x__h3874 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_float_to_posit_stg3)
	$display("%0d: %m.rl_float_to_posit_stg3: out ", v__h3833);
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_read_quire_stg3)
	begin
	  v__h4062 = $stime;
	  #0;
	end
    x__h4095 = v__h4062 + 32'd5;
    v__h4054 = x__h4095 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (WILL_FIRE_RL_rl_read_quire_stg3)
	$display("%0d: %m.rl_read_quire_stg3: out ", v__h4054);
  end
  // synopsys translate_on
endmodule  // mkPositCore

