//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:52 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_request_put                O     1 reg
// response_get                   O    35 reg
// RDY_response_get               O     1 reg
// verbosity                      I     2
// CLK                            I     1 clock
// RST_N                          I     1 reset
// request_put                    I    38
// EN_request_put                 I     1
// EN_response_get                I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkPtoF_PNE(verbosity,
		  CLK,
		  RST_N,

		  request_put,
		  EN_request_put,
		  RDY_request_put,

		  EN_response_get,
		  response_get,
		  RDY_response_get);
  input  [1 : 0] verbosity;
  input  CLK;
  input  RST_N;

  // action method request_put
  input  [37 : 0] request_put;
  input  EN_request_put;
  output RDY_request_put;

  // actionvalue method response_get
  input  EN_response_get;
  output [34 : 0] response_get;
  output RDY_response_get;

  // signals for module outputs
  wire [34 : 0] response_get;
  wire RDY_request_put, RDY_response_get;

  // ports of submodule ffO
  wire [34 : 0] ffO$D_IN, ffO$D_OUT;
  wire ffO$CLR, ffO$DEQ, ffO$EMPTY_N, ffO$ENQ, ffO$FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_request_put,
       CAN_FIRE_response_get,
       WILL_FIRE_request_put,
       WILL_FIRE_response_get;

  // declarations used by system tasks
  // synopsys translate_off
  reg [31 : 0] v__h215;
  reg [31 : 0] v__h959;
  reg [31 : 0] x__h248;
  reg [31 : 0] x__h992;
  reg [31 : 0] v__h207;
  reg [31 : 0] v__h951;
  // synopsys translate_on

  // remaining internal signals
  reg [31 : 0] float_no__h170;
  reg [1 : 0] CASE_float_no70_0_2_4286578688_1_0__q3;
  wire [31 : 0] float_no__h167;
  wire [23 : 0] frac__h160, x__h453;
  wire [22 : 0] frac_f__h166;
  wire [8 : 0] SEXT_IF_request_put_BITS_34_TO_27_SLT_129_THEN_ETC___d11,
	       x__h386;
  wire [7 : 0] IF_request_put_BITS_34_TO_27_MINUS_127_9_SLE_3_ETC__q2,
	       IF_request_put_BITS_34_TO_27_MINUS_129_5_SLE_2_ETC__q1,
	       IF_request_put_BITS_34_TO_27_SLT_129_THEN_129__ETC___d10,
	       request_put_BITS_34_TO_27_MINUS_127___d19,
	       request_put_BITS_34_TO_27_MINUS_129___d15;
  wire [5 : 0] IF_IF_request_put_BITS_34_TO_27_SLT_129_THEN_I_ETC___d29,
	       IF_request_put_BITS_34_TO_27_SLT_129_THEN_IF_r_ETC___d24,
	       x__h550;
  wire NOT_verbosity_ULE_1___d2,
       add_round__h168,
       request_put_BITS_34_TO_27_SLE_127___d8,
       request_put_BITS_34_TO_27_SLT_129___d7,
       truncated_frac_msb__h162,
       truncated_frac_zero__h161,
       x__h620,
       x__h621,
       x__h639,
       y__h640;

  // action method request_put
  assign RDY_request_put = ffO$FULL_N ;
  assign CAN_FIRE_request_put = ffO$FULL_N ;
  assign WILL_FIRE_request_put = EN_request_put ;

  // actionvalue method response_get
  assign response_get = ffO$D_OUT ;
  assign RDY_response_get = ffO$EMPTY_N ;
  assign CAN_FIRE_response_get = ffO$EMPTY_N ;
  assign WILL_FIRE_response_get = EN_response_get ;

  // submodule ffO
  FIFO2 #(.width(32'd35), .guarded(1'd1)) ffO(.RST(RST_N),
					      .CLK(CLK),
					      .D_IN(ffO$D_IN),
					      .ENQ(ffO$ENQ),
					      .DEQ(ffO$DEQ),
					      .CLR(ffO$CLR),
					      .D_OUT(ffO$D_OUT),
					      .FULL_N(ffO$FULL_N),
					      .EMPTY_N(ffO$EMPTY_N));

  // submodule ffO
  assign ffO$D_IN =
	     { float_no__h170,
	       (request_put[37:36] == 2'd0) ?
		 CASE_float_no70_0_2_4286578688_1_0__q3 :
		 request_put[37:36],
	       add_round__h168 } ;
  assign ffO$ENQ = EN_request_put ;
  assign ffO$DEQ = EN_response_get ;
  assign ffO$CLR = 1'b0 ;

  // remaining internal signals
  assign IF_IF_request_put_BITS_34_TO_27_SLT_129_THEN_I_ETC___d29 =
	     IF_request_put_BITS_34_TO_27_SLT_129_THEN_IF_r_ETC___d24[5] ?
	       -IF_request_put_BITS_34_TO_27_SLT_129_THEN_IF_r_ETC___d24 :
	       IF_request_put_BITS_34_TO_27_SLT_129_THEN_IF_r_ETC___d24 ;
  assign IF_request_put_BITS_34_TO_27_MINUS_127_9_SLE_3_ETC__q2 =
	     ((request_put_BITS_34_TO_27_MINUS_127___d19 ^ 8'h80) <= 8'd159) ?
	       request_put_BITS_34_TO_27_MINUS_127___d19 :
	       8'd31 ;
  assign IF_request_put_BITS_34_TO_27_MINUS_129_5_SLE_2_ETC__q1 =
	     ((request_put_BITS_34_TO_27_MINUS_129___d15 ^ 8'h80) <= 8'd97) ?
	       8'd225 :
	       request_put_BITS_34_TO_27_MINUS_129___d15 ;
  assign IF_request_put_BITS_34_TO_27_SLT_129_THEN_129__ETC___d10 =
	     request_put_BITS_34_TO_27_SLT_129___d7 ?
	       8'd129 :
	       (request_put_BITS_34_TO_27_SLE_127___d8 ?
		  request_put[34:27] :
		  8'd127) ;
  assign IF_request_put_BITS_34_TO_27_SLT_129_THEN_IF_r_ETC___d24 =
	     request_put_BITS_34_TO_27_SLT_129___d7 ?
	       IF_request_put_BITS_34_TO_27_MINUS_129_5_SLE_2_ETC__q1[5:0] :
	       (request_put_BITS_34_TO_27_SLE_127___d8 ?
		  6'd0 :
		  IF_request_put_BITS_34_TO_27_MINUS_127_9_SLE_3_ETC__q2[5:0]) ;
  assign NOT_verbosity_ULE_1___d2 = verbosity > 2'd1 ;
  assign SEXT_IF_request_put_BITS_34_TO_27_SLT_129_THEN_ETC___d11 =
	     { IF_request_put_BITS_34_TO_27_SLT_129_THEN_129__ETC___d10[7],
	       IF_request_put_BITS_34_TO_27_SLT_129_THEN_129__ETC___d10 } ;
  assign add_round__h168 = x__h620 & truncated_frac_msb__h162 ;
  assign float_no__h167 = { request_put[35], x__h386[7:0], frac_f__h166 } ;
  assign frac__h160 = { 1'd1, request_put[26:4] } ;
  assign frac_f__h166 =
	     IF_request_put_BITS_34_TO_27_SLT_129_THEN_IF_r_ETC___d24[5] ?
	       x__h453[22:0] :
	       ((IF_request_put_BITS_34_TO_27_SLT_129_THEN_IF_r_ETC___d24 ==
		 6'd0) ?
		  request_put[26:4] :
		  23'd8388607) ;
  assign request_put_BITS_34_TO_27_MINUS_127___d19 =
	     request_put[34:27] - 8'd127 ;
  assign request_put_BITS_34_TO_27_MINUS_129___d15 =
	     request_put[34:27] - 8'd129 ;
  assign request_put_BITS_34_TO_27_SLE_127___d8 =
	     (request_put[34:27] ^ 8'h80) <= 8'd255 ;
  assign request_put_BITS_34_TO_27_SLT_129___d7 =
	     (request_put[34:27] ^ 8'h80) < 8'd1 ;
  assign truncated_frac_msb__h162 =
	     IF_request_put_BITS_34_TO_27_SLT_129_THEN_IF_r_ETC___d24[5] ?
	       frac__h160[x__h550[4:0]] :
	       IF_request_put_BITS_34_TO_27_SLT_129_THEN_IF_r_ETC___d24 !=
	       6'd0 ||
	       request_put[3] ;
  assign truncated_frac_zero__h161 =
	     IF_request_put_BITS_34_TO_27_SLT_129_THEN_IF_r_ETC___d24[5] ?
	       x__h639 & y__h640 :
	       IF_request_put_BITS_34_TO_27_SLT_129_THEN_IF_r_ETC___d24 ==
	       6'd0 &&
	       request_put[2:0] == 3'd0 ;
  assign x__h386 =
	     SEXT_IF_request_put_BITS_34_TO_27_SLT_129_THEN_ETC___d11 +
	     9'd127 ;
  assign x__h453 = frac__h160 >> x__h550 ;
  assign x__h550 =
	     IF_IF_request_put_BITS_34_TO_27_SLT_129_THEN_I_ETC___d29 + 6'd1 ;
  assign x__h620 = x__h621 | frac_f__h166[0] ;
  assign x__h621 = ~truncated_frac_zero__h161 ;
  assign x__h639 = ~request_put[3] ;
  assign y__h640 =
	     { 8'd0,
	       (frac__h160 &
		~(24'hFFFFFE <<
		  IF_IF_request_put_BITS_34_TO_27_SLT_129_THEN_I_ETC___d29[4:0])) >>
	       0 } ==
	     32'd0 ;
  always@(request_put or float_no__h167 or add_round__h168)
  begin
    case (request_put[37:36])
      2'd1: float_no__h170 = 32'hFF800000;
      2'd2: float_no__h170 = 32'd0;
      default: float_no__h170 = float_no__h167 + { 31'd0, add_round__h168 };
    endcase
  end
  always@(float_no__h170)
  begin
    case (float_no__h170)
      32'd0: CASE_float_no70_0_2_4286578688_1_0__q3 = 2'd2;
      32'hFF800000: CASE_float_no70_0_2_4286578688_1_0__q3 = 2'd1;
      default: CASE_float_no70_0_2_4286578688_1_0__q3 = 2'd0;
    endcase
  end

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1___d2)
	begin
	  v__h215 = $stime;
	  #0;
	end
    x__h248 = v__h215 + 32'd5;
    v__h207 = x__h248 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1___d2)
	$display("%0d: %m: request.fa_extract_float: ", v__h207);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1___d2)
	$display("   scale_f %b scale_plus_bias %b frac_f %b",
		 $signed(SEXT_IF_request_put_BITS_34_TO_27_SLT_129_THEN_ETC___d11),
		 x__h386[7:0],
		 frac_f__h166);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1___d2)
	$display("   float_no %b add_round %b ",
		 float_no__h170,
		 add_round__h168);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1___d2)
	$display("   truncated_frac_zero %b truncated_frac_msb %b lsbfrac_f %b",
		 truncated_frac_zero__h161,
		 truncated_frac_msb__h162,
		 frac_f__h166[0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1___d2)
	begin
	  v__h959 = $stime;
	  #0;
	end
    x__h992 = v__h959 + 32'd5;
    v__h951 = x__h992 / 32'd10;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1___d2)
	$display("%0d: %m: request: ", v__h951);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1___d2)
	$display("   Inputs: sign %b scale %b frac %b",
		 request_put[35],
		 $signed(request_put[34:27]),
		 request_put[26:0]);
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_request_put && NOT_verbosity_ULE_1___d2)
	$display("   Adjusted: frac %b scale %b frac_change %b",
		 request_put[26:4],
		 $signed(IF_request_put_BITS_34_TO_27_SLT_129_THEN_129__ETC___d10),
		 $signed(IF_request_put_BITS_34_TO_27_SLT_129_THEN_IF_r_ETC___d24));
  end
  // synopsys translate_on
endmodule  // mkPtoF_PNE

