//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:45 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_rvfi_Int                   O     1 reg
// RDY_rvfi_Control               O     1 reg
// RDY_rvfi_DMem                  O     1 reg
// RDY_rvfi_CSRRxx                O     1 reg
// RDY_rvfi_MRET                  O     1 reg
// RDY_rvfi_Exception             O     1 reg
// fo_rvfi_reports_first          O   418 reg
// RDY_fo_rvfi_reports_first      O     1 reg
// RDY_fo_rvfi_reports_deq        O     1 reg
// fo_rvfi_reports_notEmpty       O     1 reg
// RDY_fo_rvfi_reports_notEmpty   O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// rvfi_Int_x                     I   301
// rvfi_Int_x2                    I   197
// rvfi_Int_inum                  I    64
// rvfi_Int_epoch                 I     2
// rvfi_Control_x                 I   301
// rvfi_Control_x2                I   229
// rvfi_Control_inum              I    64
// rvfi_Control_epoch             I     2
// rvfi_DMem_x                    I   301
// rvfi_DMem_x2                   I   265
// rvfi_DMem_rd_val               I    32
// rvfi_DMem_inum                 I    64
// rvfi_DMem_epoch                I     2
// rvfi_CSRRxx_x                  I   301
// rvfi_CSRRxx_rd_val             I    32
// rvfi_CSRRxx_inum               I    64
// rvfi_CSRRxx_epoch              I     2
// rvfi_MRET_x                    I   301
// rvfi_MRET_pc_wdata             I    32
// rvfi_MRET_inum                 I    64
// rvfi_MRET_epoch                I     2
// rvfi_Exception_x               I   301
// rvfi_Exception_tvec            I    32
// rvfi_Exception_inum            I    64
// rvfi_Exception_epoch           I     2
// EN_rvfi_Int                    I     1
// EN_rvfi_Control                I     1
// EN_rvfi_DMem                   I     1
// EN_rvfi_CSRRxx                 I     1
// EN_rvfi_MRET                   I     1
// EN_rvfi_Exception              I     1
// EN_fo_rvfi_reports_deq         I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkRVFI_Report(CLK,
		     RST_N,

		     rvfi_Int_x,
		     rvfi_Int_x2,
		     rvfi_Int_inum,
		     rvfi_Int_epoch,
		     EN_rvfi_Int,
		     RDY_rvfi_Int,

		     rvfi_Control_x,
		     rvfi_Control_x2,
		     rvfi_Control_inum,
		     rvfi_Control_epoch,
		     EN_rvfi_Control,
		     RDY_rvfi_Control,

		     rvfi_DMem_x,
		     rvfi_DMem_x2,
		     rvfi_DMem_rd_val,
		     rvfi_DMem_inum,
		     rvfi_DMem_epoch,
		     EN_rvfi_DMem,
		     RDY_rvfi_DMem,

		     rvfi_CSRRxx_x,
		     rvfi_CSRRxx_rd_val,
		     rvfi_CSRRxx_inum,
		     rvfi_CSRRxx_epoch,
		     EN_rvfi_CSRRxx,
		     RDY_rvfi_CSRRxx,

		     rvfi_MRET_x,
		     rvfi_MRET_pc_wdata,
		     rvfi_MRET_inum,
		     rvfi_MRET_epoch,
		     EN_rvfi_MRET,
		     RDY_rvfi_MRET,

		     rvfi_Exception_x,
		     rvfi_Exception_tvec,
		     rvfi_Exception_inum,
		     rvfi_Exception_epoch,
		     EN_rvfi_Exception,
		     RDY_rvfi_Exception,

		     fo_rvfi_reports_first,
		     RDY_fo_rvfi_reports_first,

		     EN_fo_rvfi_reports_deq,
		     RDY_fo_rvfi_reports_deq,

		     fo_rvfi_reports_notEmpty,
		     RDY_fo_rvfi_reports_notEmpty);
  input  CLK;
  input  RST_N;

  // action method rvfi_Int
  input  [300 : 0] rvfi_Int_x;
  input  [196 : 0] rvfi_Int_x2;
  input  [63 : 0] rvfi_Int_inum;
  input  [1 : 0] rvfi_Int_epoch;
  input  EN_rvfi_Int;
  output RDY_rvfi_Int;

  // action method rvfi_Control
  input  [300 : 0] rvfi_Control_x;
  input  [228 : 0] rvfi_Control_x2;
  input  [63 : 0] rvfi_Control_inum;
  input  [1 : 0] rvfi_Control_epoch;
  input  EN_rvfi_Control;
  output RDY_rvfi_Control;

  // action method rvfi_DMem
  input  [300 : 0] rvfi_DMem_x;
  input  [264 : 0] rvfi_DMem_x2;
  input  [31 : 0] rvfi_DMem_rd_val;
  input  [63 : 0] rvfi_DMem_inum;
  input  [1 : 0] rvfi_DMem_epoch;
  input  EN_rvfi_DMem;
  output RDY_rvfi_DMem;

  // action method rvfi_CSRRxx
  input  [300 : 0] rvfi_CSRRxx_x;
  input  [31 : 0] rvfi_CSRRxx_rd_val;
  input  [63 : 0] rvfi_CSRRxx_inum;
  input  [1 : 0] rvfi_CSRRxx_epoch;
  input  EN_rvfi_CSRRxx;
  output RDY_rvfi_CSRRxx;

  // action method rvfi_MRET
  input  [300 : 0] rvfi_MRET_x;
  input  [31 : 0] rvfi_MRET_pc_wdata;
  input  [63 : 0] rvfi_MRET_inum;
  input  [1 : 0] rvfi_MRET_epoch;
  input  EN_rvfi_MRET;
  output RDY_rvfi_MRET;

  // action method rvfi_Exception
  input  [300 : 0] rvfi_Exception_x;
  input  [31 : 0] rvfi_Exception_tvec;
  input  [63 : 0] rvfi_Exception_inum;
  input  [1 : 0] rvfi_Exception_epoch;
  input  EN_rvfi_Exception;
  output RDY_rvfi_Exception;

  // value method fo_rvfi_reports_first
  output [417 : 0] fo_rvfi_reports_first;
  output RDY_fo_rvfi_reports_first;

  // action method fo_rvfi_reports_deq
  input  EN_fo_rvfi_reports_deq;
  output RDY_fo_rvfi_reports_deq;

  // value method fo_rvfi_reports_notEmpty
  output fo_rvfi_reports_notEmpty;
  output RDY_fo_rvfi_reports_notEmpty;

  // signals for module outputs
  wire [417 : 0] fo_rvfi_reports_first;
  wire RDY_fo_rvfi_reports_deq,
       RDY_fo_rvfi_reports_first,
       RDY_fo_rvfi_reports_notEmpty,
       RDY_rvfi_CSRRxx,
       RDY_rvfi_Control,
       RDY_rvfi_DMem,
       RDY_rvfi_Exception,
       RDY_rvfi_Int,
       RDY_rvfi_MRET,
       fo_rvfi_reports_notEmpty;

  // ports of submodule f_reports
  reg [417 : 0] f_reports$D_IN;
  wire [417 : 0] f_reports$D_OUT;
  wire f_reports$CLR,
       f_reports$DEQ,
       f_reports$EMPTY_N,
       f_reports$ENQ,
       f_reports$FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_fo_rvfi_reports_deq,
       CAN_FIRE_rvfi_CSRRxx,
       CAN_FIRE_rvfi_Control,
       CAN_FIRE_rvfi_DMem,
       CAN_FIRE_rvfi_Exception,
       CAN_FIRE_rvfi_Int,
       CAN_FIRE_rvfi_MRET,
       WILL_FIRE_fo_rvfi_reports_deq,
       WILL_FIRE_rvfi_CSRRxx,
       WILL_FIRE_rvfi_Control,
       WILL_FIRE_rvfi_DMem,
       WILL_FIRE_rvfi_Exception,
       WILL_FIRE_rvfi_Int,
       WILL_FIRE_rvfi_MRET;

  // inputs to muxes for submodule ports
  wire [417 : 0] MUX_f_reports$enq_1__VAL_1,
		 MUX_f_reports$enq_1__VAL_2,
		 MUX_f_reports$enq_1__VAL_3,
		 MUX_f_reports$enq_1__VAL_4,
		 MUX_f_reports$enq_1__VAL_5,
		 MUX_f_reports$enq_1__VAL_6;

  // remaining internal signals
  reg [31 : 0] x__h1615, x__h1618;
  reg [7 : 0] r___1_rvfi_mem_rmask__h1289;
  reg [4 : 0] x__h1553, x__h1594;
  wire [180 : 0] IF_rvfi_DMem_x2_BITS_198_TO_194_7_EQ_0b11110_8_ETC___d87;
  wire [63 : 0] r___1_rvfi_mem_wdata__h1409, x1_avValue_rvfi_mem_wdata__h1190;
  wire [31 : 0] x1_avValue_rvfi_mem_addr__h1193,
		x__h1630,
		x__h2056,
		x__h2081,
		x__h2270,
		x__h2558,
		x__h519,
		x__h544,
		x__h921,
		x__h965;
  wire [7 : 0] x1_avValue_rvfi_mem_wmask__h1195;
  wire [4 : 0] x__h2060, x__h2562, x__h523, x__h944;

  // action method rvfi_Int
  assign RDY_rvfi_Int = f_reports$FULL_N ;
  assign CAN_FIRE_rvfi_Int = f_reports$FULL_N ;
  assign WILL_FIRE_rvfi_Int = EN_rvfi_Int ;

  // action method rvfi_Control
  assign RDY_rvfi_Control = f_reports$FULL_N ;
  assign CAN_FIRE_rvfi_Control = f_reports$FULL_N ;
  assign WILL_FIRE_rvfi_Control = EN_rvfi_Control ;

  // action method rvfi_DMem
  assign RDY_rvfi_DMem = f_reports$FULL_N ;
  assign CAN_FIRE_rvfi_DMem = f_reports$FULL_N ;
  assign WILL_FIRE_rvfi_DMem = EN_rvfi_DMem ;

  // action method rvfi_CSRRxx
  assign RDY_rvfi_CSRRxx = f_reports$FULL_N ;
  assign CAN_FIRE_rvfi_CSRRxx = f_reports$FULL_N ;
  assign WILL_FIRE_rvfi_CSRRxx = EN_rvfi_CSRRxx ;

  // action method rvfi_MRET
  assign RDY_rvfi_MRET = f_reports$FULL_N ;
  assign CAN_FIRE_rvfi_MRET = f_reports$FULL_N ;
  assign WILL_FIRE_rvfi_MRET = EN_rvfi_MRET ;

  // action method rvfi_Exception
  assign RDY_rvfi_Exception = f_reports$FULL_N ;
  assign CAN_FIRE_rvfi_Exception = f_reports$FULL_N ;
  assign WILL_FIRE_rvfi_Exception = EN_rvfi_Exception ;

  // value method fo_rvfi_reports_first
  assign fo_rvfi_reports_first = f_reports$D_OUT ;
  assign RDY_fo_rvfi_reports_first = f_reports$EMPTY_N ;

  // action method fo_rvfi_reports_deq
  assign RDY_fo_rvfi_reports_deq = f_reports$EMPTY_N ;
  assign CAN_FIRE_fo_rvfi_reports_deq = f_reports$EMPTY_N ;
  assign WILL_FIRE_fo_rvfi_reports_deq = EN_fo_rvfi_reports_deq ;

  // value method fo_rvfi_reports_notEmpty
  assign fo_rvfi_reports_notEmpty = f_reports$EMPTY_N ;
  assign RDY_fo_rvfi_reports_notEmpty = 1'd1 ;

  // submodule f_reports
  FIFO2 #(.width(32'd418), .guarded(1'd1)) f_reports(.RST(RST_N),
						     .CLK(CLK),
						     .D_IN(f_reports$D_IN),
						     .ENQ(f_reports$ENQ),
						     .DEQ(f_reports$DEQ),
						     .CLR(f_reports$CLR),
						     .D_OUT(f_reports$D_OUT),
						     .FULL_N(f_reports$FULL_N),
						     .EMPTY_N(f_reports$EMPTY_N));

  // inputs to muxes for submodule ports
  assign MUX_f_reports$enq_1__VAL_1 =
	     { rvfi_Int_inum,
	       3'd0,
	       rvfi_Int_x[161:130],
	       rvfi_Int_x[149:145],
	       rvfi_Int_x[154:150],
	       rvfi_Int_x[129:98],
	       rvfi_Int_x[31:0],
	       rvfi_Int_x[297:266],
	       x__h519,
	       64'd0,
	       x__h523,
	       x__h544,
	       80'd0 } ;
  assign MUX_f_reports$enq_1__VAL_2 =
	     { rvfi_Control_inum,
	       3'd0,
	       rvfi_Control_x[161:130],
	       rvfi_Control_x[149:145],
	       rvfi_Control_x[154:150],
	       rvfi_Control_x[129:98],
	       rvfi_Control_x[31:0],
	       rvfi_Control_x[297:266],
	       x__h921,
	       64'd0,
	       x__h944,
	       x__h965,
	       80'd0 } ;
  assign MUX_f_reports$enq_1__VAL_3 =
	     { rvfi_DMem_inum,
	       3'd0,
	       rvfi_DMem_x[161:130],
	       x__h1553,
	       x__h1594,
	       x__h1615,
	       x__h1618,
	       rvfi_DMem_x[297:266],
	       x__h1630,
	       IF_rvfi_DMem_x2_BITS_198_TO_194_7_EQ_0b11110_8_ETC___d87 } ;
  assign MUX_f_reports$enq_1__VAL_4 =
	     { rvfi_CSRRxx_inum,
	       3'd0,
	       rvfi_CSRRxx_x[161:130],
	       rvfi_CSRRxx_x[149:145],
	       5'd0,
	       rvfi_CSRRxx_x[129:98],
	       32'd0,
	       rvfi_CSRRxx_x[297:266],
	       x__h2056,
	       64'd0,
	       x__h2060,
	       x__h2081,
	       80'd0 } ;
  assign MUX_f_reports$enq_1__VAL_5 =
	     { rvfi_MRET_inum,
	       3'd0,
	       rvfi_MRET_x[161:130],
	       74'd0,
	       rvfi_MRET_x[297:266],
	       x__h2270,
	       181'd0 } ;
  assign MUX_f_reports$enq_1__VAL_6 =
	     { rvfi_Exception_inum,
	       3'd4,
	       rvfi_Exception_x[161:130],
	       74'd0,
	       rvfi_Exception_x[297:266],
	       x__h2558,
	       64'd0,
	       x__h2562,
	       112'd0 } ;

  // submodule f_reports
  always@(EN_rvfi_Int or
	  MUX_f_reports$enq_1__VAL_1 or
	  EN_rvfi_Control or
	  MUX_f_reports$enq_1__VAL_2 or
	  EN_rvfi_DMem or
	  MUX_f_reports$enq_1__VAL_3 or
	  EN_rvfi_CSRRxx or
	  MUX_f_reports$enq_1__VAL_4 or
	  EN_rvfi_MRET or
	  MUX_f_reports$enq_1__VAL_5 or
	  EN_rvfi_Exception or MUX_f_reports$enq_1__VAL_6)
  begin
    case (1'b1) // synopsys parallel_case
      EN_rvfi_Int: f_reports$D_IN = MUX_f_reports$enq_1__VAL_1;
      EN_rvfi_Control: f_reports$D_IN = MUX_f_reports$enq_1__VAL_2;
      EN_rvfi_DMem: f_reports$D_IN = MUX_f_reports$enq_1__VAL_3;
      EN_rvfi_CSRRxx: f_reports$D_IN = MUX_f_reports$enq_1__VAL_4;
      EN_rvfi_MRET: f_reports$D_IN = MUX_f_reports$enq_1__VAL_5;
      EN_rvfi_Exception: f_reports$D_IN = MUX_f_reports$enq_1__VAL_6;
      default: f_reports$D_IN =
		   418'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */ ;
    endcase
  end
  assign f_reports$ENQ =
	     EN_rvfi_Int || EN_rvfi_Control || EN_rvfi_DMem ||
	     EN_rvfi_CSRRxx ||
	     EN_rvfi_MRET ||
	     EN_rvfi_Exception ;
  assign f_reports$DEQ = EN_fo_rvfi_reports_deq ;
  assign f_reports$CLR = 1'b0 ;

  // remaining internal signals
  assign IF_rvfi_DMem_x2_BITS_198_TO_194_7_EQ_0b11110_8_ETC___d87 =
	     (rvfi_DMem_x2[198:194] == 5'b11110) ?
	       { 64'd0,
		 rvfi_DMem_x[141:137],
		 rvfi_DMem_rd_val,
		 rvfi_DMem_x2[159:128],
		 r___1_rvfi_mem_rmask__h1289,
		 8'd0,
		 rvfi_DMem_x2[230:199] } :
	       { x1_avValue_rvfi_mem_wdata__h1190,
		 37'd0,
		 x1_avValue_rvfi_mem_addr__h1193,
		 8'd0,
		 x1_avValue_rvfi_mem_wmask__h1195,
		 32'd0 } ;
  assign r___1_rvfi_mem_wdata__h1409 = { 32'd0, rvfi_DMem_x[31:0] } ;
  assign x1_avValue_rvfi_mem_addr__h1193 =
	     (rvfi_DMem_x2[198:194] == 5'b11111) ?
	       rvfi_DMem_x2[159:128] :
	       32'd0 ;
  assign x1_avValue_rvfi_mem_wdata__h1190 =
	     (rvfi_DMem_x2[198:194] == 5'b11111) ?
	       r___1_rvfi_mem_wdata__h1409 :
	       64'd0 ;
  assign x1_avValue_rvfi_mem_wmask__h1195 =
	     (rvfi_DMem_x2[198:194] == 5'b11111) ?
	       r___1_rvfi_mem_rmask__h1289 :
	       8'd0 ;
  assign x__h1630 = rvfi_DMem_x[193:162] | { 30'd0, rvfi_DMem_epoch } ;
  assign x__h2056 = rvfi_CSRRxx_x[193:162] | { 30'd0, rvfi_CSRRxx_epoch } ;
  assign x__h2060 = rvfi_CSRRxx_x[97] ? rvfi_CSRRxx_x[141:137] : 5'd0 ;
  assign x__h2081 =
	     rvfi_CSRRxx_x[97] ?
	       ((rvfi_CSRRxx_x[141:137] == 5'd0) ?
		  32'd0 :
		  rvfi_CSRRxx_rd_val) :
	       32'd0 ;
  assign x__h2270 = rvfi_MRET_pc_wdata | { 30'd0, rvfi_MRET_epoch } ;
  assign x__h2558 = rvfi_Exception_tvec | { 30'd0, rvfi_Exception_epoch } ;
  assign x__h2562 = rvfi_Exception_x[97] ? rvfi_Exception_x[141:137] : 5'd0 ;
  assign x__h519 = rvfi_Int_x[193:162] | { 30'd0, rvfi_Int_epoch } ;
  assign x__h523 = rvfi_Int_x[97] ? rvfi_Int_x[141:137] : 5'd0 ;
  assign x__h544 =
	     rvfi_Int_x[97] ?
	       ((rvfi_Int_x[141:137] == 5'd0) ?
		  32'd0 :
		  rvfi_Int_x2[159:128]) :
	       32'd0 ;
  assign x__h921 = rvfi_Control_x2[191:160] | { 30'd0, rvfi_Control_epoch } ;
  assign x__h944 = rvfi_Control_x[97] ? rvfi_Control_x[141:137] : 5'd0 ;
  assign x__h965 =
	     rvfi_Control_x[97] ?
	       ((rvfi_Control_x[141:137] == 5'd0) ?
		  32'd0 :
		  rvfi_Control_x2[159:128]) :
	       32'd0 ;
  always@(rvfi_DMem_x2 or rvfi_DMem_x)
  begin
    case (rvfi_DMem_x2[198:194])
      5'b11110, 5'b11111: x__h1553 = rvfi_DMem_x[149:145];
      default: x__h1553 = 5'd0;
    endcase
  end
  always@(rvfi_DMem_x2 or rvfi_DMem_x)
  begin
    case (rvfi_DMem_x2[198:194])
      5'b11110: x__h1594 = 5'd0;
      5'b11111: x__h1594 = rvfi_DMem_x[154:150];
      default: x__h1594 = 5'd0;
    endcase
  end
  always@(rvfi_DMem_x2 or rvfi_DMem_x)
  begin
    case (rvfi_DMem_x2[198:194])
      5'b11110, 5'b11111: x__h1615 = rvfi_DMem_x[129:98];
      default: x__h1615 = 32'd0;
    endcase
  end
  always@(rvfi_DMem_x2 or rvfi_DMem_x)
  begin
    case (rvfi_DMem_x2[198:194])
      5'b11110: x__h1618 = 32'd0;
      5'b11111: x__h1618 = rvfi_DMem_x[31:0];
      default: x__h1618 = 32'd0;
    endcase
  end
  always@(rvfi_DMem_x)
  begin
    case (rvfi_DMem_x[143:142])
      2'b0: r___1_rvfi_mem_rmask__h1289 = 8'b00000001;
      2'b01: r___1_rvfi_mem_rmask__h1289 = 8'b00000011;
      2'b10: r___1_rvfi_mem_rmask__h1289 = 8'b00001111;
      2'd3: r___1_rvfi_mem_rmask__h1289 = 8'b11111111;
    endcase
  end
endmodule  // mkRVFI_Report

