//
// Generated by Bluespec Compiler, version 2024.01 (build ae2a2fc6)
//
// On Mon Jul 13 21:42:56 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// fn_twosC_quire                 O   511
// fn_twosC_quire_quire           I   512
// fn_twosC_quire_quire_seg_zero  I    16
//
// Combinational paths from inputs to outputs:
//   (fn_twosC_quire_quire, fn_twosC_quire_quire_seg_zero) -> fn_twosC_quire
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_fn_twosC_quire(fn_twosC_quire_quire,
			     fn_twosC_quire_quire_seg_zero,
			     fn_twosC_quire);
  // value method fn_twosC_quire
  input  [511 : 0] fn_twosC_quire_quire;
  input  [15 : 0] fn_twosC_quire_quire_seg_zero;
  output [510 : 0] fn_twosC_quire;

  // signals for module outputs
  wire [510 : 0] fn_twosC_quire;

  // remaining internal signals
  wire [31 : 0] IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_0__ETC___d137,
		IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_10_ETC___d52,
		IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_11_ETC___d44,
		IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_12_ETC___d35,
		IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_13_ETC___d27,
		IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_14_ETC___d18,
		IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_15_ETC___d9,
		IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_1__ETC___d129,
		IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_2__ETC___d120,
		IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_3__ETC___d112,
		IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_4__ETC___d103,
		IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_5__ETC___d95,
		IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_6__ETC___d86,
		IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_7__ETC___d78,
		IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_8__ETC___d69,
		IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_9__ETC___d61;
  wire [15 : 0] fn_twosC_quire_quire_seg_zero_PLUS_1___d1;

  // value method fn_twosC_quire
  assign fn_twosC_quire =
	     { IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_15_ETC___d9[30:0],
	       IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_14_ETC___d18,
	       IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_13_ETC___d27,
	       IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_12_ETC___d35,
	       IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_11_ETC___d44,
	       IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_10_ETC___d52,
	       IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_9__ETC___d61,
	       IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_8__ETC___d69,
	       IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_7__ETC___d78,
	       IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_6__ETC___d86,
	       IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_5__ETC___d95,
	       IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_4__ETC___d103,
	       IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_3__ETC___d112,
	       IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_2__ETC___d120,
	       IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_1__ETC___d129,
	       IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_0__ETC___d137 } ;

  // remaining internal signals
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_0__ETC___d137 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[0] ==
	      fn_twosC_quire_quire_seg_zero[0]) ?
	       ~fn_twosC_quire_quire[31:0] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[0] ?
		  ~fn_twosC_quire_quire[31:0] + 32'd1 :
		  fn_twosC_quire_quire[31:0]) ;
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_10_ETC___d52 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[10] ==
	      fn_twosC_quire_quire_seg_zero[10]) ?
	       ~fn_twosC_quire_quire[351:320] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[10] ?
		  ~fn_twosC_quire_quire[351:320] + 32'd1 :
		  fn_twosC_quire_quire[351:320]) ;
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_11_ETC___d44 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[11] ==
	      fn_twosC_quire_quire_seg_zero[11]) ?
	       ~fn_twosC_quire_quire[383:352] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[11] ?
		  ~fn_twosC_quire_quire[383:352] + 32'd1 :
		  fn_twosC_quire_quire[383:352]) ;
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_12_ETC___d35 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[12] ==
	      fn_twosC_quire_quire_seg_zero[12]) ?
	       ~fn_twosC_quire_quire[415:384] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[12] ?
		  ~fn_twosC_quire_quire[415:384] + 32'd1 :
		  fn_twosC_quire_quire[415:384]) ;
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_13_ETC___d27 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[13] ==
	      fn_twosC_quire_quire_seg_zero[13]) ?
	       ~fn_twosC_quire_quire[447:416] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[13] ?
		  ~fn_twosC_quire_quire[447:416] + 32'd1 :
		  fn_twosC_quire_quire[447:416]) ;
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_14_ETC___d18 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[14] ==
	      fn_twosC_quire_quire_seg_zero[14]) ?
	       ~fn_twosC_quire_quire[479:448] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[14] ?
		  ~fn_twosC_quire_quire[479:448] + 32'd1 :
		  fn_twosC_quire_quire[479:448]) ;
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_15_ETC___d9 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[15] ==
	      fn_twosC_quire_quire_seg_zero[15]) ?
	       ~fn_twosC_quire_quire[511:480] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[15] ?
		  ~fn_twosC_quire_quire[511:480] + 32'd1 :
		  fn_twosC_quire_quire[511:480]) ;
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_1__ETC___d129 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[1] ==
	      fn_twosC_quire_quire_seg_zero[1]) ?
	       ~fn_twosC_quire_quire[63:32] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[1] ?
		  ~fn_twosC_quire_quire[63:32] + 32'd1 :
		  fn_twosC_quire_quire[63:32]) ;
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_2__ETC___d120 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[2] ==
	      fn_twosC_quire_quire_seg_zero[2]) ?
	       ~fn_twosC_quire_quire[95:64] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[2] ?
		  ~fn_twosC_quire_quire[95:64] + 32'd1 :
		  fn_twosC_quire_quire[95:64]) ;
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_3__ETC___d112 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[3] ==
	      fn_twosC_quire_quire_seg_zero[3]) ?
	       ~fn_twosC_quire_quire[127:96] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[3] ?
		  ~fn_twosC_quire_quire[127:96] + 32'd1 :
		  fn_twosC_quire_quire[127:96]) ;
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_4__ETC___d103 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[4] ==
	      fn_twosC_quire_quire_seg_zero[4]) ?
	       ~fn_twosC_quire_quire[159:128] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[4] ?
		  ~fn_twosC_quire_quire[159:128] + 32'd1 :
		  fn_twosC_quire_quire[159:128]) ;
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_5__ETC___d95 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[5] ==
	      fn_twosC_quire_quire_seg_zero[5]) ?
	       ~fn_twosC_quire_quire[191:160] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[5] ?
		  ~fn_twosC_quire_quire[191:160] + 32'd1 :
		  fn_twosC_quire_quire[191:160]) ;
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_6__ETC___d86 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[6] ==
	      fn_twosC_quire_quire_seg_zero[6]) ?
	       ~fn_twosC_quire_quire[223:192] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[6] ?
		  ~fn_twosC_quire_quire[223:192] + 32'd1 :
		  fn_twosC_quire_quire[223:192]) ;
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_7__ETC___d78 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[7] ==
	      fn_twosC_quire_quire_seg_zero[7]) ?
	       ~fn_twosC_quire_quire[255:224] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[7] ?
		  ~fn_twosC_quire_quire[255:224] + 32'd1 :
		  fn_twosC_quire_quire[255:224]) ;
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_8__ETC___d69 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[8] ==
	      fn_twosC_quire_quire_seg_zero[8]) ?
	       ~fn_twosC_quire_quire[287:256] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[8] ?
		  ~fn_twosC_quire_quire[287:256] + 32'd1 :
		  fn_twosC_quire_quire[287:256]) ;
  assign IF_fn_twosC_quire_quire_seg_zero_PLUS_1_BIT_9__ETC___d61 =
	     (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[9] ==
	      fn_twosC_quire_quire_seg_zero[9]) ?
	       ~fn_twosC_quire_quire[319:288] :
	       (fn_twosC_quire_quire_seg_zero_PLUS_1___d1[9] ?
		  ~fn_twosC_quire_quire[319:288] + 32'd1 :
		  fn_twosC_quire_quire[319:288]) ;
  assign fn_twosC_quire_quire_seg_zero_PLUS_1___d1 =
	     fn_twosC_quire_quire_seg_zero + 16'd1 ;
endmodule  // module_fn_twosC_quire

